### ISSUE TITLE
Don't hardcode install paths

### ISSUE THREAD

**Issue by uartie** [intel/media-driver#1]
Currently, various cmake install targets are installed into hardcoded paths that only follow Ubuntu's directory layout.  This burdens developers and packagers on other Linux distros and also makes it impossible to override install destination/prefix.  Often, developers prefer to isolate installs into custom locations for various reasons, too.

Instead of hardcoded paths, the install targets should use the GNU standard installation directories.  This allows for developers to override specific install paths (e.g. `-DCMAKE_INSTALL_LIBDIR=<somedir>`).  Also, the developer could set `-DCMAKE_INSTALL_PREFIX=<somedir>`  to customize the prefix for all target types.

https://cmake.org/cmake/help/v3.5/module/GNUInstallDirs.html

**Comment by oliver-sang** [comment]
thanks for reporting this issue and thanks for the PR. I ran into some problem while trying your PR which I added comments in PR. Could you help? Thanks
