### ISSUE TITLE
typo: (re)souce->(re)source

### ISSUE THREAD

**Issue by francoisbertelatschrodinger** [intel/media-driver#1010]
This is a typo in many files not only in comments but also in method names.

Collected with:
```
$ find . -name '*' -print0 | xargs -0 grep -n ouce > ~/typo.txt
```
[typo.txt](https://github.com/intel/media-driver/files/4975735/typo.txt)

**Comment by XinfengZhang** [comment]
thanks, will check it. but it is not urgent, right?

**Comment by francoisbertelatschrodinger** [comment]
Not urgent. Just reporting.

**Comment by FurongZhang** [comment]
@XinfengZhang , I will assign this issue.

**Comment by FurongZhang** [comment]
We have already had a plan to fix this issue. Will update it if any progress.
