### ISSUE TITLE
build error

### ISSUE THREAD

**Issue by quiricada** [intel/media-driver#1033]
/intel/media-driver-master/media_driver/linux/common/vp/ddi/media_libva_vp.c:1031:10: error: ‘VA_FILTER_INTERPOLATION_NEAREST_NEIGHBOR’ was not declared in this scope                    
 1031 |     case VA_FILTER_INTERPOLATION_NEAREST_NEIGHBOR:         
      |          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~          
/intel/media-driver-master/media_driver/linux/common/vp/ddi/media_libva_vp.c:1034:10: error: ‘VA_FILTER_INTERPOLATION_BILINEAR’ was not declared in this scope                            
 1034 |     case VA_FILTER_INTERPOLATION_BILINEAR:                 
      |          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/intel/media-driver-master/media_driver/linux/common/vp/ddi/media_libva_vp.c:1037:10: error: ‘VA_FILTER_INTERPOLATION_ADVANCED’ was not declared in this scope                             
1037 |     case VA_FILTER_INTERPOLATION_ADVANCED:
      |          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/intel/media-driver-master/media_driver/linux/common/vp/ddi/media_libva_vp.c:1038:10: error: ‘VA_FILTER_INTERPOLATION_DEFAULT’ was not declared in this scope; did you mean ‘VA_FILTER_SCALING_DEFAULT’?
 1038 |     case VA_FILTER_INTERPOLATION_DEFAULT:
      |          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
      |          VA_FILTER_SCALING_DEFAULT
/intel/media-driver-master/media_driver/linux/common/vp/ddi/media_libva_vp.c: In function ‘VAStatus DdiVp_SetProcPipelineParams(VADriverContextP, PDDI_VP_CONTEXT, VAProcPipelineParameter
Buffer*)’:
/intel/media-driver-master/media_driver/linux/common/vp/ddi/media_libva_vp.c:1345:71: error: ‘VA_FILTER_INTERPOLATION_MASK’ was not declared in this scope
 1345 |     uInterpolationflags              = pPipelineParam->filter_flags & VA_FILTER_INTERPOLATION_MASK;
      |         
           ^~~~~~~~~~~~~~~~~~~~~~~~~~~~

**Comment by XinfengZhang** [comment]
it related with libva version , you could compile it basing on latest libva. or build the driver after b828bdc8ea408b404a94c772b9d1e6b5df567f1e --- it add some protection code to avoid such build issue by detecting libva version
