### ISSUE TITLE
Can decode H264 GDR(intra-refresh) stream?

### ISSUE THREAD

**Issue by hxl-dy** [intel/media-driver#1046]

**Comment by XinfengZhang** [comment]
intra refresh insert some I blocks in inter frames, media driver could decode it

**Comment by hxl-dy** [comment]
> intra refresh insert some I blocks in inter frames, media driver could decode it

Any sample code to test my video file?

https://1drv.ms/u/s!AtcnNSjUJHaDlyv6737MjlGz0ry8?e=4TfCXg
