### ISSUE TITLE
The attribute vaCreateSurfaces query of VASurfaceAttribPixelFormat  for VPP lose some formats.

### ISSUE THREAD

**Issue by HeJunyan** [intel/media-driver#1047]
It only returns "NV12, I420, YV12, YUY2, ABGR, ARGB, xBGR, P010_10LE, BGRA, RGBA, BGR10A2_LE", some format such as VUYA is missing.

**Comment by HeJunyan** [comment]
Accord to @XinfengZhang and @xhaihao, this should contain all formats of input and output of VPP.

**Comment by XinfengZhang** [comment]
@FurongZhang , could you help to check it?

**Comment by MicroYY** [comment]
Hi @HeJunyan 
Fix check in done. https://github.com/intel/media-driver/commit/026924fd08570b372333caac97a190ed8aa78216

**Comment by XinfengZhang** [comment]
@HeJunyan , could you help to check the patch. if no other problem, please help to close it

**Comment by XinfengZhang** [comment]
@HeJunyan , it should already been fixed, if you still need to add more format, or , some format is still missed. please re-open it and tell the format. thanks
