### ISSUE TITLE
build: driver build with -DENABLE_KERNELS=OFF is broken

### ISSUE THREAD

**Issue by dvrogozh** [intel/media-driver#1049]
Broken since commit https://github.com/intel/media-driver/commit/fefa9ecd7a3720078e6ace56bedf9da75ffd150c.

Broken configuration:
```
cmake -DENABLE_KERNELS=OFF ..
```

See http://mediasdk.intel.com/buildbot/#builders/61/builds/2403 build log.

**Comment by Alex1Zhang** [comment]
The fix is #1050 , please help review the change. Thanks a lot in advance!
