### ISSUE TITLE
Can't support VAConfigAttribEncPackedHeaders query for HEVC ENC.

### ISSUE THREAD

**Issue by mypopydev** [intel/media-driver#106]
Now media-driver only support VAConfigAttribEncPackedHeaders query for AVC/MPGE2 ENC, need to support this query for HEVC ENC.

https://github.com/intel/media-driver/blob/43a84e7a893ebf0433a8efc6bb7ab6a3e325a3fa/media_driver/linux/common/ddi/media_libva_caps.cpp#L435

**Comment by XinfengZhang** [comment]
sure, will fix

**Comment by XinfengZhang** [comment]
https://github.com/intel/media-driver/commit/35fbaa2472c83967e693c9925999a4a77e208cd1

**Comment by XinfengZhang** [comment]
fixed by https://github.com/intel/media-driver/commit/35fbaa2472c83967e693c9925999a4a77e208cd1
