### ISSUE TITLE
[regression][gstreamer] VPP rotation 90/270 YV12 corruption

### ISSUE THREAD

**Issue by uartie** [intel/media-driver#1071]
Since commit 450fcc06c0eb4a61a2f5f73b3e07e0e875a484d6 (#1064):

```
commit 450fcc06c0eb4a61a2f5f73b3e07e0e875a484d6
Author: Sreerenj Balachandran <sreerenj.balachandran@intel.com>
Date:   Tue Oct 13 18:38:00 2020 -0700

    media_libva_util: Fix odd resolution handling of yuv420 formats
    
    Ensure 2-byte width & height alignment for I420/YV12/IYUV surfaces
    when there is no usage hint set for Encode or VPP write operations.
    It seems the  odd resolution surface post-processing operation
    (eg: nv12 to i420 conversion via vaGetImage API), causing a green
    column on the right side of the video without this alignment.
    
    Fixing #1037
```

YV12 rotation at 90 or 270 degress with vaapipostproc and msdkvpp produces corrupted output.

```
gst-launch-1.0 -vf videotestsrc num-buffers=1 ! video/x-raw,format=YV12,width=1920,height=1080 \
  ! vaapipostproc video-direction=90r ! video/x-raw,format=YV12 \
  ! checksumsink2 file-checksum=false qos=false frame-checksum=false \
  plane-checksum=false dump-output=true dump-location=gst-vaapi-1080x1920_YV12.yuv

gst-launch-1.0 -vf videotestsrc num-buffers=1 ! video/x-raw,format=YV12,width=1920,height=1080 \
  ! msdkvpp video-direction=90r ! video/x-raw,format=YV12 \
  ! checksumsink2 file-checksum=false qos=false frame-checksum=false \
  plane-checksum=false dump-output=true dump-location=gst-msdk-1080x1920_YV12.yuv
```

Actual Result:
<p><img src="https://user-images.githubusercontent.com/677859/97481833-9a136480-1912-11eb-875d-928a9a9430f8.jpg" width="25%"/></p>

Expected Result:
<p><img src="https://user-images.githubusercontent.com/677859/97481887-ad263480-1912-11eb-8d8a-d66044b24157.jpg" width="25%"/></p>

cc: @sreerenjb

**Comment by sreerenjb** [comment]
Ouch! we should revert immediately then.
@Jister @XinfengZhang 

Quickly tested with xvimagesink but didn't see any issue. Probably the conversion involved in the middle is hiding the actual issue.
Originally I proposed 8 byte alignment to match with i965.  Any chance to test with 
--- a/media_driver/linux/common/ddi/media_libva_util.cpp
+++ b/media_driver/linux/common/ddi/media_libva_util.cpp
@@ -208,8 +208,8 @@ VAStatus DdiMediaUtil_AllocateSurface(
                 !(mediaSurface->surfaceUsageHint & VA_SURFACE_ATTRIB_USAGE_HINT_VPP_WRITE))
             {
                 tileformat = I915_TILING_NONE;
-                alignedWidth = MOS_ALIGN_CEIL(width, 2);
-                alignedHeight = MOS_ALIGN_CEIL(height, 2);
+                alignedWidth = MOS_ALIGN_CEIL(width, 8);
+                alignedHeight = MOS_ALIGN_CEIL(height, 8);
                 break;
             }

**Comment by sreerenjb** [comment]
Aha, formatting issue.
Change **alignedWidth = MOS_ALIGN_CEIL(width, 2);  to  alignedWidth = MOS_ALIGN_CEIL(width, 8);**
and  **alignedHeight = MOS_ALIGN_CEIL(height, 2); to  alignedHeight = MOS_ALIGN_CEIL(height, 8);**

**Comment by sreerenjb** [comment]
@uartie 
I tested with 
gst-launch-1.0 -vf videotestsrc num-buffers=1 ! video/x-raw,format=YV12,width=1920,height=1080   ! vaapipostproc video-direction=90r ! video/x-raw,format=YV12   ! checksumsink2 file-checksum=false qos=false frame-checksum=false   plane-checksum=false dump-output=true dump-location=gst-vaapi-1080x1920_YV12.yuv

and play with ffmpeg:
ffplay -f rawvideo -pixel_format yuv420p -video_size 1080x1920 gst-vaapi-1080x1920_YV12.yuv

**Not seeing any corruption.** But since ffmpeg doesn't have any YV12 option , I provided yuv420p. So color mismatch is there in chroma.

**Comment by uartie** [comment]
> @uartie
> I tested with
> gst-launch-1.0 -vf videotestsrc num-buffers=1 ! video/x-raw,format=YV12,width=1920,height=1080 ! vaapipostproc video-direction=90r ! video/x-raw,format=YV12 ! checksumsink2 file-checksum=false qos=false frame-checksum=false plane-checksum=false dump-output=true dump-location=gst-vaapi-1080x1920_YV12.yuv
> 
> and play with ffmpeg:
> ffplay -f rawvideo -pixel_format yuv420p -video_size 1080x1920 gst-vaapi-1080x1920_YV12.yuv
> 
> **Not seeing any corruption.** But since ffmpeg doesn't have any YV12 option , I provided yuv420p. So color mismatch is there in chroma.

You mean you're not seeing any corruption *with* your aforementioned changes or *without* your changes?

**Comment by sreerenjb** [comment]
Without any changes. I mean, use the iHD master which has https://github.com/intel/media-driver/commit/450fcc06c0eb4a61a2f5f73b3e07e0e875a484d6

**Comment by uartie** [comment]
@sreerenjb I just tried with your change in https://github.com/intel/media-driver/issues/1071#issuecomment-718233128.  But it did not seem to fix the issue.

@XinfengZhang @Sherry-Lin can you please revert 450fcc06c0eb4a61a2f5f73b3e07e0e875a484d6 commit.  I'm seeing more use-cases failing in our full testing too.

**Comment by XinfengZhang** [comment]
sure， will revert it

**Comment by sreerenjb** [comment]
Ya, revert and investigate is the option :)

**Comment by uartie** [comment]
reverted in ca794cb70bdd5faf134324310b7054f240dd77f9 and fixes this issue.
