### ISSUE TITLE
[Gen12 regression][sample_vpp]The md5 of input file and output file are same through sample_vpp sharpen for I420 and YV12 on Gen12.   

### ISSUE THREAD

**Issue by yefengxx** [intel/media-driver#1083]
The md5 of input file and output file are same through sample_vpp sharpen for **I420** and **YV12** on **Gen12**.   

for example:
sample_vpp -sw 3840 -sh 2160 -scc yv12 -dw 3840 -dh 2160 -dcc yv12 -detail 75 -i input -o output
On ICL platform, we can get different input and output files for **I420** and **YV12**, and we confirm that this is the correct result. But on **Gen12** the md5 of input file and output file are same.

software stack:
libva: https://github.com/intel/libva.git (commit id: 8ed365dcefdcb699661a88f2dda236aeac52815a)
gmmlib: https://github.com/intel/gmmlib (commit id: 1598c1b46fb911cb9060d1a5380aec1ca1ef2c19)
media-driver: https://github.com/intel/media-driver (commit id: 3a4a038e12c10b2e913cdffdd3101df4574e16ab)
MediaSDK: https://github.com/Intel-Media-SDK/MediaSDK (commit id: 0dbaea1bf8d09f4b266f69e317a7450a85a9d485)

**Comment by Sherry-Lin** [comment]
You mentioned it's regression. Could you provide the good stack commit list? Thanks.

**Comment by yefengxx** [comment]
> You mentioned it's regression. Could you provide the good stack commit list? Thanks.

I'm sorry, maybe I didn't express it clearly enough. I want to say that there is no issue with the ICL platform, but GEN12(TGL&DG1) found this issue.

**Comment by XinfengZhang** [comment]
@FurongZhang , please help to check the issue

**Comment by MicroYY** [comment]
Hi @yefengxx 
This is expected, as VPP BLT doesn't gives bit match result even in/out is the same. 
This case is using render kernel. For ICL and TGL, different kernels are used. 
So there may be results that ICL in/out bit match while TGL not.
