### ISSUE TITLE
Question about latest skl_dmc_ver1_27.bin and kernel version.

### ISSUE THREAD

**Issue by pauldotknopf** [intel/media-driver#109]
I am trying to setup Intel's new open-source iHD driver on a Yocto environment.

https://software.intel.com/en-us/articles/build-and-debug-open-source-media-stack

The documentation says that skl_dmc_ver1_27.bin is required. Their documentation updates a symlink (skl_dmc_ver1.bin), as if the kernel loads it, but starting at kernel 4.8, it stopped loading the symlink and instead loads a specific version of the dmc (see here: https://github.com/torvalds/linux/blob/v4.8/drivers/gpu/drm/i915/intel_csr.c#L48). Is the Intel documentation accurate? It is confusing because the guide refers to 4.14.16 specifically, which doesn't use the symlink file skl_dmc_ver1.bin.

Any ways, I tried replacing skl_dmc_ver1_26.bin with skl_dmc_ver1_27.bin to have the same effect, but I got a segfault on boot.

https://pastebin.com/amW9vDdC

Should I even bother updating the DMC? Should the iHD driver work on most kernels, even with 1_26 version of DMC?

By the way, this is the kernel I am using (with Yocto).

https://github.com/intel/linux-intel-lts/tree/4.14/yocto/base/drivers/gpu/drm/i915

Any help would be greatly appreciated. There is no documentation on this stuff.

**Comment by dvrogozh** [comment]
Hi,

Thank you for pointing the inconsistency out. You are right that 4.14 LTS kernel does not require DMC v1.27 on SKL, instead it requires v1.26. And looks like you are right about symbolic link, though some OS versions still set it to the latest DMC.
For 4.14 LTS DMC requirements from the i915 driver are:
```
# fgrep -rsn dmc_ver  drivers/gpu/drm/i915/
drivers/gpu/drm/i915/intel_csr.c:37:#define I915_CSR_GLK "i915/glk_dmc_ver1_04.bin"
drivers/gpu/drm/i915/intel_csr.c:40:#define I915_CSR_CNL "i915/cnl_dmc_ver1_04.bin"
drivers/gpu/drm/i915/intel_csr.c:43:#define I915_CSR_KBL "i915/kbl_dmc_ver1_01.bin"
drivers/gpu/drm/i915/intel_csr.c:47:#define I915_CSR_SKL "i915/skl_dmc_ver1_26.bin"
drivers/gpu/drm/i915/intel_csr.c:51:#define I915_CSR_BXT "i915/bxt_dmc_ver1_07.bin"
```
iHD driver does not uses DMC as far as I know. However, some media use cases can still be affected by bugs in and around DMC. For example, see: https://bugs.freedesktop.org/show_bug.cgi?id=100572. That's example of the issue why you may wish to update to the v1.27 DMC on SKL and consider the following patches applied for i915 driver (landed upstream 4.16 I believe):
- https://patchwork.freedesktop.org/patch/msgid/1510276712-29590-2-git-send-email-anusha.srivatsa@intel.com (similar patches exists for kbl and other platforms bumping DMC version)
- https://patchwork.freedesktop.org/patch/msgid/20171205132854.26380-1-tvrtko.ursulin@linux.intel.com
However, consider your use case. If you don't work with the headless mode, probably you are fine to stay with v1.26.

` I tried replacing skl_dmc_ver1_26.bin with skl_dmc_ver1_27.bin`
"Replace" sounds incorrect. Normally you need to have dmc v1.27 placed alongside v1.26 and patch i915 driver to use v1.27 instead (see the patch I pointed to above). I am not sure which side effects you can expect if you will fake v1.27 to look as v1.26.

Regards,
Dmitry.
