### ISSUE TITLE
Mpeg2 decoder crash because of missing reference.

### ISSUE THREAD

**Issue by HeJunyan** [intel/media-driver#1119]
The gstreamer pipeline 
gst-launch-1.0 -vf filesrc location=~/koncercik.mpg ! parsebin ! vaapimpeg2dec ! fakesink
crashes because missing the reference.

This stream have group of picture header. It is an optional header that can be used immediately before a coded I-frame to indicate to the decoder if the first consecutive B-pictures immediately following the coded I-frame can be reconstructed properly in the case of a random access.
   
In that case, the B frames may miss the previous reference and can still be correctly decoded. 
We set   forward_reference_picture = VA_INVALID_ID, but driver crashes when access the reference frame.

Even we really misses the reference frame, some manner such as inserting grey picture should be used to handle these cases, rather than crash.

**Comment by HeJunyan** [comment]
CC: @XinfengZhang & @xhaihao

**Comment by XinfengZhang** [comment]
two questions:
1.  you are talking about IBBBB, why forward reference picture is invalid?  backward reference picture should be invalid
2.  the consecutive B frame just have one reference frame?

**Comment by HeJunyan** [comment]
Yes, the B is in the stream header, and has no forward reference frame. I can send you the stream to analyze it if you want.
And, more important, even the B frame missing the forward_reference_picture  or back_reference_picture, and we set VA_INVALID_ID for these field, the driver should not crash.

**Comment by XinfengZhang** [comment]
> Yes, the B is in the stream header, and has no forward reference frame. I can send you the stream to analyze it if you want.
> And, more important, even the B frame missing the forward_reference_picture or back_reference_picture, and we set VA_INVALID_ID for these field, the driver should not crash.

you mean, the driver should not crash, but could add some protection code (condition check) and return failure?

**Comment by HeJunyan** [comment]
What is the behaviour of H264/265 and other codecs when missing some reference? The same behaviour is OK.

**Comment by HeJunyan** [comment]
It's better to insert some. for example, grey surface for missing reference surface. That kind of B frame I mentioned can be decoded successfully with just back_reference_picture. So, return failure is not a good option.

**Comment by XinfengZhang** [comment]
it means all of prediction is from back_reference_picture, no any prediction is from forward_reference_picture.  is it a common usage case?

**Comment by Jexu** [comment]
> Yes, the B is in the stream header, and has no forward reference frame. I can send you the stream to analyze it if you want.
> And, more important, even the B frame missing the forward_reference_picture or back_reference_picture, and we set VA_INVALID_ID for these field, the driver should not crash.

Hi @HeJunyan, by checking the driver, when there is no forward or backward reference, driver will set the reference index to be destination frame. That means driver can always get non-null reference. can you share the bitstream to me and i can double check that.
