### ISSUE TITLE
Use VPP convert VA_FOURCC_BGRA to VA_FOURCC_NV12

### ISSUE THREAD

**Issue by samuel100u** [intel/media-driver#1120]
I noticed that `VA_FOURCC_BGRA `, `VA_FOURCC_ARGB`, `VA_FOURCC_RGBA`  and `VA_FOURCC_ABGR` is identical because no matter what `fourcc` I choose the output is always the same.

I use `iHD_drv_video.so` as encode driver.

**Comment by XinfengZhang** [comment]
@FurongZhang  @Jister , suppose it is not an real issue, please help to comment it. about current HW restriction and history , why we export these format. thanks
