### ISSUE TITLE
HEVC only VA_RC_CQP works

### ISSUE THREAD

**Issue by samuel100u** [intel/media-driver#1135]
ffplay.exe 
CBR ↓ 
![](https://imgur.com/qyXNfee.gif)

**Comment by XinfengZhang** [comment]
could you provide more information?  platform, version, command  etc.

**Comment by samuel100u** [comment]
I use DG1 at CentOS8.

H264 is correct, but h265 will produce the weird result above.

resolution : 1280x720
CBR
