### ISSUE TITLE
[gstreamer-vaapi][h265enc] h265enc doesn't work.

### ISSUE THREAD

**Issue by feiwan1** [intel/media-driver#115]
System Environment
OS Ubuntu 17.04
Kernel 4.10
Hardware Skylake Intel(R) Core(TM) i5-6600K CPU @ 3.50GHz
libva tag 2.1.0
intel-media-driver 48f33e5
gst-vaapi tag 1.13.90

Reproduce Steps
$LIBVA_TRACE=./h265enc gst-launch-1.0 videotestsrc num-buffers=100 ! vaapih265enc ! fakesink
Setting pipeline to PAUSED ...
Pipeline is PREROLLING ...
Got context from element 'vaapiencodeh265-0': gst.vaapi.Display=context, gst.vaapi.Display=(GstVaapiDisplay)"\(GstVaapiDisplayX11\)\ vaapidisplayx11-1";
ERROR: from element /GstPipeline:pipeline0/GstVideoTestSrc:videotestsrc0: Internal data stream error.
Additional debug info:
gstbasesrc.c(3055): gst_base_src_loop (): /GstPipeline:pipeline0/GstVideoTestSrc:videotestsrc0:
streaming stopped, reason not-negotiated (-4)
ERROR: pipeline doesn't want to preroll.
Setting pipeline to NULL ...
Freeing pipeline ...

**Comment by feiwan1** [comment]
[h265enc.074241.thd-0x00003e53.log](https://github.com/intel/media-driver/files/1822463/h265enc.074241.thd-0x00003e53.log)
[h265enc.074241.thd-0x00003e54.log](https://github.com/intel/media-driver/files/1822464/h265enc.074241.thd-0x00003e54.log)

**Comment by jcescamilla** [comment]
This caused because Gstreamer tries checking for ROI QP delta support flag. Added a PR that fixes this. #132
