### ISSUE TITLE
Very bad artifacts at specific quality levels with jpegenc

### ISSUE THREAD

**Issue by linkmauve** [intel/media-driver#1152]
Here is an encoding at quality 90:
![sunshine-90](https://user-images.githubusercontent.com/7755816/109823855-9719df00-7c38-11eb-95f5-3d33d81b3736.jpeg)
Quality 94:
![sunshine-94](https://user-images.githubusercontent.com/7755816/109824681-55d5ff00-7c39-11eb-8a59-ab56f0f8bb44.jpeg)
Quality 95:
![sunshine-95](https://user-images.githubusercontent.com/7755816/109823875-9b45fc80-7c38-11eb-9292-c3e524bfa46e.jpeg)
Quality 100:
![sunshine-100](https://user-images.githubusercontent.com/7755816/109823932-a8fb8200-7c38-11eb-844b-9e255fc71a88.jpeg)

As we can see, at quality 94 and 95, iHD generates terrible blocking artifacts everywhere, and neither luma nor chroma are anywhere near correct. This also happens at lower quality (not pictured here) but is less and less present.

This issue doesn’t happen with the older i965 driver.

I’ve reproduced with every YUV image I’ve tried, using:
- libva 2.10.0
- libva-utils 2.10.0
- intel-media-driver 20.4.5
- (libva-intel-driver 2.4.1 for comparison)

All from ArchLinux’s repositories.

**Comment by uartie** [comment]
Seems related to #281

**Comment by linkmauve** [comment]
Indeed, but that coarse testing in #281 doesn’t seem to exhibit the periodicity (per quality) of the issue.

Here is my data for this one sample from quality 1 to quality 100: [psnr.csv](https://github.com/intel/media-driver/files/6077966/psnr.csv.txt)

And as a chart:
![psnr](https://user-images.githubusercontent.com/7755816/109847551-9e98b280-7c4f-11eb-8081-f6a776d240c3.png)

**Comment by XinfengZhang** [comment]
@aleonenk @Alexandr-Konovalov could you help to check the issue

**Comment by ivan-losev** [comment]
Hi @linkmauve,
Could you, please, share what environment (platform, driver version, etc.) you are using and steps to reproduce this quality drop issue.
I tried to reproduce issue on KBL on the latest driver using sample_encode (as in #281 ) but didn't observe quality drop

**Comment by ivan-losev** [comment]
Hi @linkmauve,
Could you, please, share steps to reproduce quality drop issue?

**Comment by ivan-losev** [comment]
Thanks, I'll take a look, what is wrong.

Could you, also try to reproduce issue using MSDK samples?
sample_encode jpeg -i input.yuv -n 1 -hw -vaapi -w 1280 -h 720 -device /dev/dri/renderD128 -q 96 -o se_1280x720_q96.jpeg &> log.txt; echo Quality 96; ffmpeg -pix_fmt yuv420p -s:v 1280x720 -i input.yuv -i se_1280x720_q96.jpeg      -frames:v 1 -lavfi psnr=stats_file=psnr_logfile.txt -f null - 2>&1 | grep PSNR; echo

**Comment by linkmauve** [comment]
I just did, and here are my observations:
- this `sample_encode` tool seems to prefer y4m files to yuv, here is its log output when I give it a raw yuv file:

**Comment by ivan-losev** [comment]
Hmm, this is strange,
For sample encode, by default it expected I420/NV12 surface as input (type 0 and 1 in jpegenc)

Related to jpegenc, it's media-driver issue related to different quantization matrix scaling
jpegenc formula:
`(quantLuma.Qk[i] * quality)/100;`

media-driver formula (with round up):
`quantValue = ( ((uint32_t)(quantMatrix->m_quantTable[qMatrixCount].m_qm[i])) * quality + 50) / 100;`

As a result, jpeg header use one qmatrix, while driver - another and quality drop occurs

**Comment by ivan-losev** [comment]
Hi @linkmauve,
Sorry for delay, we expect that commit will be merged till the end of the next week (16 Apr 2021)

**Comment by XinfengZhang** [comment]
thanks @ivan-losev , please add "fixes" keyword in your commit , or link the issue with your commit , thanks

**Comment by linkmauve** [comment]
Thanks! I’ll test that once it gets merged!

**Comment by ivan-losev** [comment]
Hi @linkmauve,
Could you, please, try to reproduce quality issue on the latest master?
Fix commit: https://github.com/intel/media-driver/commit/1ec93f2888860ef992595e33c49e7b7d4f94fc86

**Comment by Xiaogangli-intel** [comment]
Hi @linkmauve, did you try the fix [1ec93f2](https://github.com/intel/media-driver/commit/1ec93f2888860ef992595e33c49e7b7d4f94fc86)? Can it fix your issue?

**Comment by Xiaogangli-intel** [comment]
@linkmauve I will close this issue. If you have other concern, let us know. Thank you.
