### ISSUE TITLE
errors of so files while building the media-driver

### ISSUE THREAD

**Issue by troy818** [intel/media-driver#1158]
I'm building media-driver on Ubuntu 18.04.2 LTS TGL i5, and I find that in step 7 of "Building", $ make -j"$(nproc)".
If I do "make" in root user, the result is ok;  but if I do "make" not in root, there will be bugs:
```
ERROR: dlopen of ../../../iHD_drv_video.so failed.
ERROR: ../../../iHD_drv_video.so: undefined symbol: _ZN6GmmLib16GmmClientContext25CreateCustomResInfoObjectEP32GMM_RESCREATE_CUSTOM_PARAMS__REC
media-driver/media_driver/linux/ult/ult_app/ddi_test_caps.cpp:99: Failure
      Expected: 0x00000000
      Which is: 0
To be equal to: ret
      Which is: -1
Platform = SKL, Failed function = m_driverLoader.InitDriver
Segmentation fault (core dumped)
```
Is it correct or not? Besides, I can't find igfxcmrt64.so in /usr/lib/x86_64-linux-gnu/

Please let me know if any more details are required, thanks!

**Comment by dvrogozh** [comment]
Take a look on #1130. In particular, https://github.com/intel/media-driver/issues/1130#issuecomment-769287383. I think you might have 2 gmmlibs installed on the system and you get slightly different environments under root vs. generic users where root don't see the bad gmmlib while generic user does see it.

Anyhow, your undefined symbols comes from bad gmmlib. You need to identify where it is located on the system and prune. Then rebuild and reinstall gmmlib from master.

**Comment by XinfengZhang** [comment]
@troy818 suppose Dmitry already answered your question.  is there additional question, if no , please help to close the issue.

**Comment by troy818** [comment]
Thanks！
