### ISSUE TITLE
HDR Tonemapping doesn't seem to be enabled for Apollo Lake

### ISSUE THREAD

**Issue by StableNarwhal** [intel/media-driver#1159]
It appears to have been added to [Kabylake](https://github.com/intel/media-driver/commit/15038615da2e5714ef86ebbbe752692b53acac84) and [Gemini Lake](https://github.com/intel/media-driver/commit/15038615da2e5714ef86ebbbe752692b53acac84).

Is there a specific reason it hasn't been added for Apollo Lake?

**Comment by softworkz** [comment]
Apollo Lake has the graphics from SkyLake and AFAIK, KabyLake is the minimum platform supporting HDHR tone mapping.

**Comment by StableNarwhal** [comment]
Oh, I was assuming that APL would support HDR tone mapping. Thank you for the quick response!

**Comment by softworkz** [comment]
It was accidental as I had thought this would be one of our repositories. But the answer should be accurate 😆

**Comment by XinfengZhang** [comment]
yes, the answer is accurate. thanks
