### ISSUE TITLE
[gstreamer-vaapi][vp8enc] no vaapivp8enc element.

### ISSUE THREAD

**Issue by feiwan1** [intel/media-driver#117]
System Environment
OS Ubuntu 17.04
Kernel 4.10
Hardware Skylake Intel(R) Core(TM) i5-6600K CPU @ 3.50GHz
libva tag 2.1.0
intel-media-driver 48f33e5
gst-vaapi tag 1.13.90

Reproduce Steps
With media-driver:
root@yami-kbl02:/encoderbitstreams_quality/otc_media-val_smoke_vpg/media_gstreamer_smoke# gst-inspect-1.0 vaapi
Plugin Details:
  Name                     vaapi
  Description              VA-API based elements
  Filename                 /opt/yami.vpg/gstreamer10/lib/gstreamer-1.0/libgstvaapi.so
  Version                  1.13.90
  License                  LGPL
  Source module            gstreamer-vaapi
  Source release date      2018-03-03
  Binary package           gstreamer-vaapi
  Origin URL               http://bugzilla.gnome.org/enter_bug.cgi?product=GStreamer

  vaapih264feienc: VA-API H264 FEI Advanced encoder (Experimental)
  vaapih264enc: VA-API H264 encoder
  vaapijpegenc: VA-API JPEG encoder
  vaapih265enc: VA-API H265 encoder
  vaapimpeg2enc: VA-API MPEG-2 encoder
  vaapisink: VA-API sink
  vaapidecodebin: VA-API Decode Bin
  vaapipostproc: VA-API video postprocessing
  vaapih265dec: VA-API H265 decoder
  vaapivp8dec: VA-API VP8 decoder
  vaapivc1dec: VA-API VC1 decoder
  vaapih264dec: VA-API H264 decoder
  vaapimpeg2dec: VA-API MPEG2 decoder
  vaapijpegdec: VA-API JPEG decoder

With vaapi-driver:
root@yami-kbl02:~# gst-inspect-1.0 vaapi
Plugin Details:
  Name                     vaapi
  Description              VA-API based elements
  Filename                 /opt/yami/gstreamer10/lib/gstreamer-1.0/libgstvaapi.so
  Version                  1.13.90
  License                  LGPL
  Source module            gstreamer-vaapi
  Source release date      2018-03-03
  Binary package           gstreamer-vaapi
  Origin URL               http://bugzilla.gnome.org/enter_bug.cgi?product=GStreamer

  vaapih264feienc: VA-API H264 FEI Advanced encoder (Experimental)
  vaapih264enc: VA-API H264 encoder
  vaapijpegenc: VA-API JPEG encoder
  vaapivp8enc: VA-API VP8 encoder
  vaapih265enc: VA-API H265 encoder
  vaapimpeg2enc: VA-API MPEG-2 encoder
  vaapisink: VA-API sink
  vaapidecodebin: VA-API Decode Bin
  vaapipostproc: VA-API video postprocessing
  vaapih265dec: VA-API H265 decoder
  vaapivp8dec: VA-API VP8 decoder
  vaapivc1dec: VA-API VC1 decoder
  vaapih264dec: VA-API H264 decoder
  vaapimpeg2dec: VA-API MPEG2 decoder
  vaapijpegdec: VA-API JPEG decoder

**Comment by XinfengZhang** [comment]
media-driver does not support VP8 encode on SKL. VP8 encode support is from CNL
