### ISSUE TITLE
h265 encoding with intra refresh failed due to GPU hang (SKL)

### ISSUE THREAD

**Issue by yskuridi** [intel/media-driver#1179]
platform GEN 9
MediaSDK 77f673853c23a91241
Driver: Intel iHD driver for Intel(R) Gen Graphics - 21.1.3-6097 (e5b8ffd)

command line:
`sample_encode h265 -i 1920x1080.yuv -o sample_output.265 -ir_type 1 -ir_cycle_size 4 -ir_qp_delta -20 -ir_cycle_dist 20 -w 1920 -h 1080 -r 1`

`./mfx_transcoder h265 -i 1920x1072_250.yuv -o output.265 -w 1920 -h 1072 -f 25 -b 600000 -u 4 -hw -d3d -s 0 -async 1 -async_depth 1 -IntRefType 1 -IntRefCycleSize 20 -IntRefCycleDist 20 -n 40 -IntRefQPDelta -20 -r 1`

error:
```
ERROR: Hardware device was lost or returned an unexpected error. Recovering...

[ERROR], sts=MFX_ERR_DEVICE_FAILED(-17), SynchronizeFirstTask, SyncOperation failed at /home/wenbin/software/media/src/MediaSDK/samples/sample_encode/src/pipeline_encode.cpp:168

[ERROR], sts=MFX_ERR_DEVICE_FAILED(-17), GetFreeTask, m_TaskPool.SynchronizeFirstTask failed at /home/wenbin/software/media/src/MediaSDK/samples/sample_encode/src/pipeline_encode.cpp:2193

[ERROR], sts=MFX_ERR_DEVICE_FAILED(-17), Run, m_pmfxENC->EncodeFrameAsync failed at /home/wenbin/software/media/src/MediaSDK/samples/sample_encode/src/pipeline_encode.cpp:2497
```

**Comment by wenbinc-Bin** [comment]
@Xiaogangli-intel Any progress on this issue?
Thanks
Wenbin

**Comment by Xiaogangli-intel** [comment]
@wenbinc-Bin Won't this issue be fixed by [https://github.com/Intel-Media-SDK/MediaSDK/pull/2667](url)?

**Comment by wenbinc-Bin** [comment]
@Xiaogangli-intel Yes, this issue is fixed. Now this issue can be closed.

**Comment by Sherry-Lin** [comment]
Close this issue which has been fixed.
