### ISSUE TITLE
List for supported format for encoding requires update

### ISSUE THREAD

**Issue by djie1** [intel/media-driver#1181]
1. In the documentation, for example, https://github.com/intel/media-driver/blob/master/docs/media_features.md#hardware-encoding-low-power-encodingvdenchuc, the supported format list does not comply with that in the code: https://github.com/intel/media-driver/blob/master/media_driver/linux/gen12/ddi/media_libva_caps_g12.h#L52 . For example, RGB32 is not listed in the documentation.
2. on Gen12, for DualPipe HEVC encoding path, seems RGB32 is also supported, but it's not listed in the code: https://github.com/intel/media-driver/blob/master/media_driver/linux/gen12/ddi/media_libva_caps_g12.h#L50

**Comment by XinfengZhang** [comment]
will update the document , thanks @djie1

**Comment by Xiaogangli-intel** [comment]
#1393 will fix this issue. And for  DualPipe HEVC, RGB is not supported.

**Comment by djie1** [comment]
>  for DualPipe HEVC, RGB is not supported.
 I tried RGB32 input, looks like it's supported for DualPipe HEVC encoding.

**Comment by Xiaogangli-intel** [comment]
> > for DualPipe HEVC, RGB is not supported.
> 
> I tried RGB32 input, looks like it's supported for DualPipe HEVC encoding.

:) Yes, but we cannot ensure it works properly.
