### ISSUE TITLE
!!! compile failed ,media-driver-intel-media-21.1.3【centos7,gcc (GCC) 8.3.1 20190311 (Red Hat 8.3.1-3)】!!!,

### ISSUE THREAD

**Issue by xcj123** [intel/media-driver#1188]
HI：
i'm getting the following build error ,[media-driver-intel-media-21.1.3]
///////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
[root@localhost build]# make
[  2%] Built target igfxcmrt
[  2%] Built target iHD_drv_video_SSE4
[  6%] Built target igfx_gmmumd_dll
[  6%] Building CXX object media_driver/CMakeFiles/iHD_drv_video_OBJ.dir/agnostic/common/cm/cm_array.cpp.o
In file included from /home/oscar/IntelMedia2113/media-driver-intel-media-21.1.3/media_driver/linux/common/cm/hal/cm_mem_os.h:30:0,
                 from /home/oscar/IntelMedia2113/media-driver-intel-media-21.1.3/media_driver/agnostic/common/cm/cm_mem.h:122,
                 from /home/oscar/IntelMedia2113/media-driver-intel-media-21.1.3/media_driver/agnostic/common/cm/cm_array.cpp:28:
/usr/lib/gcc/x86_64-redhat-linux/4.8.5/include/smmintrin.h:31:3: error: #error "SSE4.1 instruction set not enabled"
 # error "SSE4.1 instruction set not enabled"
   ^
cc1plus: error: unrecognized command line option "-Wno-delete-incomplete" [-Werror]
cc1plus: all warnings being treated as errors
make[2]: *** [media_driver/CMakeFiles/iHD_drv_video_OBJ.dir/build.make:63: media_driver/CMakeFiles/iHD_drv_video_OBJ.dir/agnostic/common/cm/cm_array.cpp.o] Error 1
make[1]: *** [CMakeFiles/Makefile2:249: media_driver/CMakeFiles/iHD_drv_video_OBJ.dir/all] Error 2
make: *** [Makefile:150: all] Error 2

////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////

**Comment by dvrogozh** [comment]
https://github.com/intel/media-driver/blob/cf7085734994dcb0e5cb982d81adac938022a16b/cmrtlib/linux/CMakeLists.txt#L36
https://github.com/intel/media-driver/blob/cf7085734994dcb0e5cb982d81adac938022a16b/cmrtlib/linux/CMakeLists.txt#L37

Are you building on 32-bit or 64-bit?
