### ISSUE TITLE
Mosaic in the background if the rendered picture is smaller than output VASurface size

### ISSUE THREAD

**Issue by Nicki-fu** [intel/media-driver#1195]
Hi, 
I meet an issue that There is Mosaic in the background if the rendered picture is scaled smaller than the output VASurface size when using EU for scaling engine.
I verified on the latest master branch of Media-driver, libva, libva-utils, gmmlib, it also exists this issue. 

**How to reproduce:**
**Step 1.** Download Media-driver, libva, libva-utils, gmmlib from github and checkout to latest master branch and build.
**Step 2**. change code in videoprocess/vavpp.cpp in libva-utils to change the pipeline buffer output_region parameter to a small size in video_frame_process.
Change from:
    _output_region.width = g_out_pic_width;
    output_region.height = g_out_pic_height;_
to:
    _output_region.width = 128;
    output_region.height = 127;_
**Step 3.** Set the right parameters in process.cfg.template.
**Step 4.** Rebuild libva-utils and run ./vavpp process.cfg.template

**Tested and founding:**
We validated NV12, YUY2 and RGBA output color format, here are our founding:

-  NV12, YUY2, RGBA are almost the same behaviors for this issue, The only different is the Mosaic is colorful for RGBA, but the Mosaic likes small pieces of video for NV12 and YUY2. You can check from attached screenshot.

- When setting the Filter_Flags to VA_FILTER_SCALING_DEFAULT, this issue is happening when the output region size is smaller than 1/8 src video size. Or the output region size is smaller than 128*128.

- When setting the Filter_Flags to VA_FILTER_SCALING_HQ, this issue is happening when the output region size scaling to any size.

- When the issue is happenning in item 2 and item 3, we can see that the EU is using for the scaling engine. In the other word, this issue always exists for EU scaling engine, and it does not exist for SFC scaling engine.

-  If we set the VAProcPipelineParameterBuffer’s output_backgound_color to a non-transparent (such as 0xff000000), the Mosaic can not be seen. But if we set the output_backgound_color to a non-transparent for the first frame, then set the output_backgound_color to transparent for the second frame, the Mosaic still exists in the second frame. Why we do this is because we want to set the background color to transparent so that other Images under the surface should be seen.

<html xmlns:v="urn:schemas-microsoft-com:vml"
xmlns:o="urn:schemas-microsoft-com:office:office"
xmlns:w="urn:schemas-microsoft-com:office:word"
xmlns:x="urn:schemas-microsoft-com:office:excel"
xmlns:m="http://schemas.microsoft.com/office/2004/12/omml"
xmlns="http://www.w3.org/TR/REC-html40">

<head>

<meta name=ProgId content=Word.Document>
<meta name=Generator content="Microsoft Word 15">
<meta name=Originator content="Microsoft Word 15">
<link rel=File-List
href="file:///C:/Users/fuqiaoni/AppData/Local/Temp/msohtmlclip1/01/clip_filelist.xml">
<link rel=themeData
href="file:///C:/Users/fuqiaoni/AppData/Local/Temp/msohtmlclip1/01/clip_themedata.thmx">
<link rel=colorSchemeMapping
href="file:///C:/Users/fuqiaoni/AppData/Local/Temp/msohtmlclip1/01/clip_colorschememapping.xml">

<style>

</style>

</head>

<body lang=EN-US style='tab-interval:.5in;word-wrap:break-word'>

src video Resolution | src frame format | Scaling output region | dst video resolution | dst frame format | Filter_Flags | Result | Scaling engine | Comment
-- | -- | -- | -- | -- | -- | -- | -- | --
1920*1080 | NV12 | 960*540 | 1920*1080 | NV12 | VA_FILTER_SCALING_DEFAULT | Pass | SFC | The output region size is bigger   to 1/8 src video size
1920*1080 | NV12 | 240*135 | 1920*1080 | NV12 | VA_FILTER_SCALING_DEFAULT | Pass | SFC | The output region size is equal   to 1/8 src video size
1920*1080 | NV12 | 240*134 | 1920*1080 | NV12 | VA_FILTER_SCALING_DEFAULT | Failed | EU | The output region size is   smaller than 1/8 src video size caused failed
1920*1080 | NV12 | 239*135 | 1920*1080 | NV12 | VA_FILTER_SCALING_DEFAULT | Failed | EU | The output region size is   smaller than 1/8 src video size caused failed
1920*1080 | NV12 | 960*540 | 1920*1080 | NV12 | VA_FILTER_SCALING_HQ | Failed | EU | The Filter Flags set to   VA_FILTER_SCALING_HQ that  the scaling engine is using EU and it    caused failed
704*480 | NV12 | 128*128 | 704*480 | NV12 | VA_FILTER_SCALING_DEFAULT | Pass | SFC | The output region size is bigger   to 1/8 src video size and bigger than 128*128
704*480 | NV12 | 128*127 | 704*480 | NV12 | VA_FILTER_SCALING_DEFAULT | Failed | SFC | The output region size is   smaller than 128*128

</body>

</html>

![scaling](https://user-images.githubusercontent.com/59425766/118109353-a6c15b00-b413-11eb-8722-ed5ca14adead.png)

Below are the screen shots with below params, we can see the different between YUY2&NV12 and RGBA:
output_region.x = 500;
output_region.y = 500;
output_region.width = 500;
output_region.height = 500;
pipeline_param.filter_flags = VA_FILTER_SCALING_HQ;

NV12&YUY2:
![nv12](https://user-images.githubusercontent.com/59425766/118108360-7cbb6900-b412-11eb-9134-5817faee6be0.jpg)

RGBA:
![rgba](https://user-images.githubusercontent.com/59425766/118108423-8e047580-b412-11eb-8ce1-2e61f5a34375.jpg)

**Comment by FurongZhang** [comment]
I rooted cause this issue. In DdiVp_SetProcPipelineParams, if Alpha !=0, driver will color Fill; otherwise, will not fill color. That is why you see corruption

**Comment by FurongZhang** [comment]
@Nicki-fu is communicating with customers. @Nicki-fu , any update?

**Comment by FurongZhang** [comment]
// Background Colorfill
    // According to libva  definition, if alpha in output background color is zero, then colorfill is not needed
    if ((pPipelineParam->output_background_color >> 24) != 0)
    {
        if (pVpHalRenderParams->pColorFillParams == nullptr)
        {
            pVpHalRenderParams->pColorFillParams = (PVPHAL_COLORFILL_PARAMS)MOS_AllocAndZeroMemory(sizeof(VPHAL_COLORFILL_PARAMS));
        }

        DDI_CHK_NULL(pVpHalRenderParams->pColorFillParams, "Null pColorFillParams.", VA_STATUS_ERROR_UNKNOWN);

        // set background colorfill option
        pVpHalRenderParams->pColorFillParams->Color     = pPipelineParam->output_background_color;
        pVpHalRenderParams->pColorFillParams->bYCbCr    = false;
        pVpHalRenderParams->pColorFillParams->CSpace    = CSpace_sRGB;
    }else
    {
        MOS_FreeMemAndSetNull(pVpHalRenderParams->pColorFillParams);
    }

**Comment by Nicki-fu** [comment]
The customer has checked that if set the alpha of background to 01 value(0x01000000) , the background is black but not transparent as expected, and the image under it can’t be seen at all. 
Then we provided the customer another solution that to render all the videos' frame to a same picture at one VPP API time(Can see below example code to get more detail). This solution can resolve the customer’s issue.


Example code of the VPP calling:
//Create buffer for video0
    va_status = vaCreateBuffer(va_dpy,
                               context_id,
                               VAProcPipelineParameterBufferType,
                               sizeof(pipeline_param),
                               1,
                               &pipeline_param,
                               &pipeline_param_buf_id);
//Create buffer for video1  
  va_status = vaCreateBuffer(va_dpy,
                               context_id,
                               VAProcPipelineParameterBufferType,
                               sizeof(pipeline_param_1),
                               1,
                              &pipeline_param_1,
                               &pipeline_param_buf_id_1);

//Begin picture
    va_status = vaBeginPicture(va_dpy,
                               context_id,
                               out_surface_id);
    CHECK_VASTATUS(va_status, "vaBeginPicture");
//Render Picture for video0
    va_status = vaRenderPicture(va_dpy,
                                context_id,
                                &pipeline_param_buf_id,
                                1);

//Render Picture for video1
    va_status = vaRenderPicture(va_dpy,
                               context_id,
                              &pipeline_param_buf_id_1,
                             1);


    va_status = vaEndPicture(va_dpy, context_id);
//Distory Buffer for video0
    if (filter_param_buf_id != VA_INVALID_ID)
        vaDestroyBuffer(va_dpy,filter_param_buf_id);
    if (pipeline_param_buf_id != VA_INVALID_ID)
        vaDestroyBuffer(va_dpy,pipeline_param_buf_id);

//Distory Buffer for video1
    if (filter_param_buf_id_1 != VA_INVALID_ID)
        vaDestroyBuffer(va_dpy,filter_param_buf_id_1);
