### ISSUE TITLE
video screen become black after I stop the video

### ISSUE THREAD

**Issue by widon1104** [intel/media-driver#1198]
I use chrome 90.0.4430.212 for linux. My cpu is i5 8350U hd620, after I use this driver I can use hardware accelerate now.
But when I play video in bilibili.com or ixigua.com, after I stop the video the video screen will become all black.
Sometimes I stop the video because I want to see the frame clearly I do not want the screen become black.

Thanks.

**Comment by XinfengZhang** [comment]
hi thanks for reporting, but I suppose it is not a decoder issue, it looks like a webrtc or browser  issue.  because media_driver just decode the pictures.

**Comment by XinfengZhang** [comment]
hi @widon1104 , could we close it, if no other concern?

**Comment by widon1104** [comment]
@XinfengZhang You can close this issue.
