### ISSUE TITLE
[Regression] HEVC 10bit Encode have different R2R output stream size

### ISSUE THREAD

**Issue by egorovdanil** [intel/media-driver#1206]
Platform: DG1
libva: 8803fc5363b635f950dc904e880a35f1c13eae88
MediaSDK: 31693415c3aa58dc826748990a59981cbaa9c6fa

Command line:
`sample_encode h265 -i 1080P_1920x1080.P010 -o output1.265 -p010 -w 1920 -h 1080 -b 5000 -lowpower:off -vaapi`

From run to run, the output stream size is different:
```
-rw-r--r-- 1 root root    6284844 Apr  1 09:33 output1.265
-rw-r--r-- 1 root root    6285693 Apr  1 09:33 output2.265
-rw-r--r-- 1 root root    6285727 Apr  1 09:33 output3.265
```
This issue starts from c383f7ef2d65f523b8b8c70a71c94a296541d5be and is reproduced on the current master 66fa14da59ba6a81f1d604d1c71fa93502884599

**Comment by XinfengZhang** [comment]
looks r2r with VEbox copy, @Xiaogang-Li , could you help to take a look?

**Comment by xhaihao** [comment]
@XinfengZhang any progression on this issue?

**Comment by wenbinc-Bin** [comment]
Hi @Xiaogang-Li and @XinfengZhang, Any plan to fix this issue? Could you give me a date and I can check this issue at that day, which helps me to better track this issue.
Thanks
Wenbin

**Comment by Xiaogangli-intel** [comment]
Sorry @wenbinc-Bin, will sync with the team about the status, will let you know once I get feedback.

**Comment by FocusLuo** [comment]
@Xiaogang-Li @XinfengZhang  This is a Run 2 Run encode issue. May I check with you whether there is any progress on this issue fixing?

**Comment by Xiaogangli-intel** [comment]
we tried latest driver, the issue should be fixed.
> Kernel 5.10.54+prerelease3052
Latest libva/gmmlib/media-driver/MediaSDK

> 256c5b0cf16bc29a89fcb0a165a01c60  output1.265
256c5b0cf16bc29a89fcb0a165a01c60  output2.265
256c5b0cf16bc29a89fcb0a165a01c60  output3.265
256c5b0cf16bc29a89fcb0a165a01c60  output4.265
256c5b0cf16bc29a89fcb0a165a01c60  output5.265

**Comment by Xiaogangli-intel** [comment]
Hi @egorovdanil , @xhaihao, not sure if you tried the latest driver. If no more concern about this issue, I will close it. Thank you.
