### ISSUE TITLE
License headers for vphal_render_fast1ton.h,cpp

### ISSUE THREAD

**Issue by cdotstout** [intel/media-driver#1216]
We're interested in using media-driver as part of a Fuchsia driver for media acceleration on Intel hardware.

The license headers in these files:
https://github.com/intel/media-driver/blob/master/media_driver/agnostic/common/vp/hal/vphal_render_fast1ton.cpp
https://github.com/intel/media-driver/blob/master/media_driver/agnostic/common/vp/hal/vphal_render_fast1ton.h

don't match the rest of the files in that directory, for example:
https://github.com/intel/media-driver/blob/master/media_driver/agnostic/common/vp/hal/vphal.h

Is there a reason for the discrepancy or is it possible to update the license headers for those two files?

Thanks.

**Comment by XinfengZhang** [comment]
sure, will check it and update the license. suppose just because it is missed when update the license.

**Comment by cdotstout** [comment]
Thank you.

I raised a similar issue in gmmlib, could you please take a look?

https://github.com/intel/gmmlib/issues/85
