### ISSUE TITLE
[SKL][VPP] Scaling the picture will lead to colour incorrect

### ISSUE THREAD

**Issue by mypopydev** [intel/media-driver#123]
Use the command: 
**ffmpeg -y -hwaccel vaapi -hwaccel_device /dev/dri/renderD128 -hwaccel_output_format vaapi -i input.mp4 -vf 'scale_vaapi=w=640:h=-2' -c:v h264_vaapi output_scale.mp4** , then use ffplay check the file output_scale.mp4 to reproduce this issue.

media@s0n0c0:~/Souces/umd_dev/FFmpeg$ uname -a
Linux s0n0c0 4.13.0-37-generic #42-Ubuntu SMP Wed Mar 7 14:13:23 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux

media@s0n0c0:~/Souces/umd_dev/FFmpeg$ lsb_release -a
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 17.10
Release:	17.10
Codename:	artful

media@s0n0c0:~/Souces/umd_dev/FFmpeg$ lscpu
Architecture:        x86_64
CPU op-mode(s):      32-bit, 64-bit
Byte Order:          Little Endian
CPU(s):              8
On-line CPU(s) list: 0-7
Thread(s) per core:  2
Core(s) per socket:  4
Socket(s):           1
NUMA node(s):        1
Vendor ID:           GenuineIntel
CPU family:          6
Model:               94
Model name:          Intel(R) Core(TM) i7-6770HQ CPU @ 2.60GHz
Stepping:            3
CPU MHz:             2600.000
CPU max MHz:         3500.0000
CPU min MHz:         800.0000
BogoMIPS:            5184.00
Virtualization:      VT-x
L1d cache:           32K
L1i cache:           32K
L2 cache:            256K
L3 cache:            6144K
NUMA node0 CPU(s):   0-7
Flags:               fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush dts acpi mmx fxsr sse sse2 ss ht tm pbe syscall nx pdpe1gb rdtscp lm constant_tsc art arch_perfmon pebs bts rep_good nopl xtopology nonstop_tsc cpuid aperfmperf tsc_known_freq pni pclmulqdq dtes64 monitor ds_cpl vmx est tm2 ssse3 sdbg fma cx16 xtpr pdcm pcid sse4_1 sse4_2 x2apic movbe popcnt aes xsave avx f16c rdrand lahf_lm abm 3dnowprefetch cpuid_fault epb invpcid_single pti retpoline intel_pt rsb_ctxsw tpr_shadow vnmi flexpriority ept vpid fsgsbase tsc_adjust bmi1 hle avx2 smep bmi2 erms invpcid rtm mpx rdseed adx smap clflushopt xsaveopt xsavec xgetbv1 xsaves dtherm ida arat pln pts hwp hwp_notify hwp_act_window hwp_epp

**Comment by XinfengZhang** [comment]
@FurongZhang please check it, thanks

**Comment by FurongZhang** [comment]
We are working in progress to reproduce this issue. Will update the progress if any.

**Comment by FurongZhang** [comment]
We have aleady reproduced this issue. Working in progress to debug this issue.

**Comment by FurongZhang** [comment]
Root caused this issue and Fixed it.

**Comment by mypopydev** [comment]
@FurongZhang  can you update the commit ID for this issue.

**Comment by FurongZhang** [comment]
commit f67843c8955a72536c01d99a0cabe7c741443cb5
