### ISSUE TITLE
[gmm] Incorrect assertion in debug mode

### ISSUE THREAD

**Issue by lakulako** [intel/media-driver#125]
The driver is built with __debug__.
Command line, for example:
> sample_hevc_fei -encode -i input.yuv -o out.h265 -w 1920 -h 1080 -r 4 -g 12 -qp 30 -n 24  -EncodedOrder

during creating contexts assertion fails:
MEMORY_OBJECT_CONTROL_STATE GMM_STDCALL GmmLib::GmmCachePolicyCommon::CachePolicyGetMemoryObject(GMM_RESOURCE_INFO *pResInfo, GMM_RESOURCE_USAGE_TYPE Usage)
{
    const GMM_CACHE_POLICY_ELEMENT *CachePolicy = NULL;
    __GMM_ASSERT(pGmmGlobalContext->GetCachePolicyElement(Usage).Initialized);
...
Here Usage is 128, obtained from GmmResourceUsage[MosUsage=29]

Probably __GMM_ASSERT is defined only in debug and the code is obsolete, because commenting it out leads to normal execution.

**Comment by oliver-sang** [comment]
sorry for inconvenience. We've known about this debug build issue. Currently, we are working on fix. Will update when we get progress.

**Comment by oliver-sang** [comment]
@lakulako could you please try whether 1013df31b00b516097ac87da7599f16564e9690d fix your case? Thanks

**Comment by lakulako** [comment]
It does help. Thank you!
