### ISSUE TITLE
[gmm] Deletes same pointer twice

### ISSUE THREAD

**Issue by lakulako** [intel/media-driver#126]
The driver is built with debug.
Command line, for example:
> sample_hevc_fei -encode -i input.yuv -o out.h265 -w 1920 -h 1080 -r 4 -g 12 -qp 30 -n 24 -EncodedOrder

after all frames are encoded in destruction time at
extern "C" void GMM_STDCALL GmmDeleteClientContext(GMM_CLIENT_CONTEXT *pGmmClientContext)
{
    if(pGmmClientContext)
    {
        __delete pGmmClientContext;__
        pGmmClientContext = NULL;
    }
}
At the fourth time call pointer to be deleted is the same as at the first.
Look like something is first destroyed implicitly, and second time inside destructors chain.

First:
Thread #1 [sample_hevc_fei] 7796 [core: 1] (Suspended : Breakpoint)       
               GmmDeleteClientContext() at GmmClientContext.cpp:516 0x7ffff1ff8cfe 
               OsContextSpecific::Destroy() at mos_context_specific.cpp:639 0x7ffff1f8559b     
               OsContext::CleanUp() at mos_context.cpp:44 0x7ffff1beb5d7      
               Mos_Specific_Destroy() at mos_os_specific.c:1,380 0x7ffff1f8999e          
               HalCm_Destroy() at cm_hal.cpp:10,310 0x7ffff196c36e   
               CMRT_UMD::CmDeviceRT::DestroyAuxDevice() at cm_device_rt_os.cpp:123 0x7ffff1edc98a  
               CMRT_UMD::CmDeviceRT::~CmDeviceRT() at cm_device_rt_os.cpp:49 0x7ffff1edbfca     
               CMRT_UMD::CmDeviceRT::Destroy() at cm_device_rt.cpp:151 0x7ffff193bcda     
               DestroyCmDevice() at cm_global_api_os.cpp:85 0x7ffff1ee5460 
               CMRTKernelBase::Destroy() at CMRTKernelBase.cpp:288 0x7ffff1dc28c6 
               <...more frames...>         

Fourth:
Thread #1 [sample_hevc_fei] 7796 [core: 1] (Suspended : Breakpoint)       
               GmmDeleteClientContext() at GmmClientContext.cpp:516 0x7ffff1ff8cfe 
               Linux_Destroy() at mos_os_specific.c:996 0x7ffff1f88994              
               Mos_Specific_Destroy() at mos_os_specific.c:1,401 0x7ffff1f89aa3          
               Codechal::~Codechal() at codechal.cpp:90 0x7ffff19de20f             
               CodechalEncoderState::~CodechalEncoderState() at codechal_encoder_base.cpp:4,472 0x7ffff1ac6121  
               CodechalEncodeHevcBase::~CodechalEncodeHevcBase() at codechal_encode_hevc_base.h:986 0x7ffff1b37c20         
               CodechalEncHevcState::~CodechalEncHevcState() at codechal_encode_hevc.cpp:1,000 0x7ffff1b3ced1  
               CodechalEncHevcStateG9::~CodechalEncHevcStateG9() at codechal_encode_hevc_g9.h:1,547 0x7ffff1d0068e         
               CodechalFeiHevcStateG9Skl::~CodechalFeiHevcStateG9Skl() at codechal_fei_hevc_g9_skl.h:592 0x7ffff1dacc68 
               CodechalFeiHevcStateG9Skl::~CodechalFeiHevcStateG9Skl() at codechal_fei_hevc_g9_skl.h:592 0x7ffff1dacc98 
               <...more frames...>

**Comment by oliver-sang** [comment]
thanks for reporting this issue. We will look at it.

**Comment by walter-bai** [comment]
Seems like a similar issue I fixed before, could you try [6ceda4b](https://github.com/intel/media-driver/commit/6ceda4b1dfce6e38e3e1c616ebd1d577cf196e08)? Thanks

**Comment by lakulako** [comment]
Right, it works in later revisions. Thank you!
