### ISSUE TITLE
VP9 FFmpeg encoding outputs garbage via both vaapi and qsv

### ISSUE THREAD

**Issue by lat9nq** [intel/media-driver#1279]
## System information
Output of `inxi -GSC -xx`: 
```
System:    Host: Qykopi Kernel: 5.14.10-300.fc35.x86_64 x86_64 bits: 64 compiler: gcc v: 2.37-10.fc35 
           Desktop: GNOME 41.0 tk: GTK 3.24.30 wm: gnome-shell dm: GDM 
           Distro: Fedora release 35 (Thirty Five) 
CPU:       Info: 6-Core model: 11th Gen Intel Core i5-11600K bits: 64 type: MT MCP arch: Rocket Lake 
           rev: 1 cache: L2: 12 MiB 
           flags: avx avx2 lm nx pae sse sse2 sse3 sse4_1 sse4_2 ssse3 vmx bogomips: 93888 
           Speed: 4911 MHz min/max: 800/5000 MHz Core speeds (MHz): 1: 4911 2: 4912 3: 4889 4: 4953 
           5: 4912 6: 4912 7: 4020 8: 4046 9: 4812 10: 2305 11: 2036 12: 4806 
Graphics:  Device-1: Intel RocketLake-S GT1 [UHD Graphics 750] vendor: ASUSTeK driver: i915 v: kernel 
           bus-ID: 00:02.0 chip-ID: 8086:4c8a 
           Device-2: NVIDIA GM200 [GeForce GTX 980 Ti] vendor: ZOTAC driver: nvidia v: 470.74 
           bus-ID: 01:00.0 chip-ID: 10de:17c8 
           Device-3: AMD Tonga PRO [Radeon R9 285/380] vendor: XFX Pine driver: amdgpu v: kernel 
           bus-ID: 04:00.0 chip-ID: 1002:6939 
           Display: x11 server: X.Org 1.20.11 compositor: gnome-shell driver: 
           loaded: amdgpu,ati,modesetting,nvidia unloaded: fbdev,nouveau,vesa alternate: nv 
           resolution: 1920x1200~60Hz s-dpi: 96 
           OpenGL: renderer: Mesa Intel Graphics (RKL GT1) v: 4.6 Mesa 21.2.3 direct render: Yes 
```

This issue was present in the previous Linux installation I was running.

### Describe the current behavior
Output of `ffmpeg -vaapi_device /dev/dri/renderD128 -hwaccel vaapi -hwaccel_output_format vaapi -i 2021102322202600-CBA841B50A92A904E313AE06DF4EF71A.mp4 -c:v vp9_vaapi -b:v 2M -bf 2 -bsf:v vp9_raw_reorder,vp9_superframe -c:a libopus -b:a 64k -ss 20 -t 10 2021102322202600-CBA841B50A92A904E313AE06DF4EF71A.vp9.mp4`:

https://user-images.githubusercontent.com/22451773/138858092-42b0fa97-08ba-41a8-8ffe-9284f86550ad.mp4

Removing `-bf 2 -bsf:v vp9_raw_reorder,vp9_superframe` does not help.

### Describe the expected behavior
Probably something similar to this, output of `ffmpeg -vaapi_device /dev/dri/renderD128 -hwaccel vaapi -hwaccel_output_format vaapi -i 2021102322202600-CBA841B50A92A904E313AE06DF4EF71A.mp4 -c:v h264_vaapi -b:v 2M -c:a libopus -b:a 64k -ss 20 -t 10 2021102322202600-CBA841B50A92A904E313AE06DF4EF71A.h264.mp4`:

https://user-images.githubusercontent.com/22451773/138858381-eebcd790-953b-4001-996c-0d7060b7290b.mp4

## Debug information
- What's libva/libva-utils/gmmlib/media-driver version?
```
$ dnf list installed | grep libva
libva.i686                                        2.13.0-1.fc35                          @fedora                                    
libva.x86_64                                      2.13.0-1.fc35                          @fedora                                    
libva-intel-driver.x86_64                         2.4.1-6.fc35                           @rpmfusion-free                            
libva-utils.x86_64                                2.13.0-1.fc35                          @fedora                                    
libva-vdpau-driver.x86_64                         0.7.4-110.fc35                         @fedora
$ dnf list installed | grep gmmlib
intel-gmmlib.x86_64                               21.3.1-1.fc35                          @fedora
$ dnf list installed | grep media-driver
intel-media-driver.x86_64                         21.3.4-1.fc35                          @rpmfusion-nonfree
```
- Could you confirm whether GPU hardware exist or not by `ls /dev/dri`?
```
$ ls /dev/dri
by-path  card0  card1  card2  renderD128  renderD129  renderD130
```
- Could you provide vainfo log if possible by `vainfo >vainfo.log 2>&1`?
[vainfo.log](https://github.com/intel/media-driver/files/7417207/vainfo.log)
- Could you provide libva trace log if possible? Run cmd `export LIBVA_TRACE=/tmp/libva_trace.log` first then execute the case.
[libva_trace.log.tar.gz](https://github.com/intel/media-driver/files/7417218/libva_trace.log.tar.gz)
- Could you attach dmesg log if it's GPU hang by `dmesg >dmesg.log 2>&1`? N/A
- Do you want to contribute a PR? (yes/no): I don't understand the issue, so no.

**Comment by vvbuzove** [comment]
@XinfengZhang we will look into this.

**Comment by lat9nq** [comment]
I was poking around with FFmpeg, and I've found a corner case where the VP9 driver actually works.

Here's the source video (too large to upload to GitHub directly, so apologies for Google Drive link): https://drive.google.com/file/d/1IC_tljreBW2CrKtDl2sOSv87s2SMQhAU/view?usp=sharing

Output of `ffmpeg -hwaccel vaapi -vaapi_device /dev/dri/renderD128 -hwaccel_output_format vaapi -i 2022010814233700-CBA841B50A92A904E313AE06DF4EF71A.mp4 -r 30 -vf scale_vaapi=-1:360 -c:v vp9_vaapi -rc_mode 1 -q:v 1.7 -b:v 0 -c:a libopus -b:a 64k -ss 20 -t 9 2022010814233700-CBA841B50A92A904E313AE06DF4EF71A.vp9.mp4` :

https://user-images.githubusercontent.com/22451773/148676880-46ea46c8-b9e2-4bfb-a8f2-ff91904c5a24.mp4


If I play with `-q:v` values from 0 to (a large number), it works fine. These are the cases where I once again get garbage:
- `-r 60`
- `-vf scale_vaapi=-1:[anything larger than 360]`
- Removing `-ss 20 -t 9` thus transcoding the entire clip
- `-q:v 1.4` for some reason
- `-rc_mode [anything other than 1]` -- there doesn't seem to be any working bit rate with any other mode.
- Any combination of the above

System specifications have not changed since I originally made this issue. Software versions have:
```
$ dnf list installed | grep libva
libva.i686                                        2.13.0-3.fc35                          @updates                                              
libva.x86_64                                      2.13.0-3.fc35                          @updates                                              
libva-intel-driver.x86_64                         2.4.1-6.fc35                           @rpmfusion-free                                       
libva-utils.x86_64                                2.13.0-1.fc35                          @fedora                                               
libva-vdpau-driver.x86_64                         0.7.4-110.fc35                         @fedora
$ dnf list installed | grep gmmlib
intel-gmmlib.x86_64                               21.3.5-1.fc35                          @updates
$ dnf list installed | grep media-driver
intel-media-driver.x86_64                         21.4.3-1.fc35                          @rpmfusion-nonfree-updates
```

**Comment by lat9nq** [comment]
Setting `-loop_filter_level` to 0 or 1 increases the chance that the output will be usable. 480p 30 fps or 360p 60 fps works better with short clips (less than 10s) in this situation.

**Comment by aidan2020sh** [comment]
@lat9nq the corruption issue looks to be a known issue which has been fixed by updating the IFWI since ww33 2021. You can update the IFWI(include BIOS) to the latest version and have a try. Usually in intel lab, it's updated with a device named "dediprog"

**Comment by lat9nq** [comment]
Updating the BIOS fixed it for VP9. HEVC via VAAPI is a mess but that's a separate issue (and seems already to be an Issue here.)

**Comment by aidan2020sh** [comment]
@lat9nq Glad to see the VP9 issue was gone! About the HEVC issue, is there any link? Can you share the reproducing details?  Thanks!

**Comment by lat9nq** [comment]
@aidan2020sh I was mistaken: the HEVC issue was not relevant to this repository, and there seems to be no equivalent here.

It's very similar to the initial issue here. A key difference however is `hevc_qsv` *does* work, while `hevc_vaapi` does not. Replaying the output in mpv results in effectively garbage. I will create a new issue for this.
