### ISSUE TITLE
Does CSC input NV12 to output RGBA support up to 8k resolution?

### ISSUE THREAD

**Issue by SiewHoon** [intel/media-driver#1280]
## System information
TGL-U and ADL-S/P platform.

### Describe the current behavior
CSC input NV12 to output RGBA is not working at 8K (7680x4320) resolution.
CSC input NV12 to output RGBA is working at small  (1080x720) resolution. 

### Describe the expected behavior
CSC input NV12 to output RGBA should be also working on 8k resolution.

## Debug information
- What's libva/libva-utils/gmmlib/media-driver version?
- Media stack Q2'2021 release.
- Could you confirm whether GPU hardware exist or not by `ls /dev/dri`?
- yes.

Gstreamer-vaapi Command:
gst-launch-1.0 -ev videotestsrc num-buffers=30 ! video/x-raw,format=NV12,width=7680,height=4320 ! vaapipostproc ! 'video/x-raw(memory:DMABuf),format=RGBA' ! glimagesink -> not working

gst-launch-1.0 -ev videotestsrc num-buffers=30 ! video/x-raw,format=NV12,width=1080,height=720 ! vaapipostproc ! 'video/x-raw(memory:DMABuf),format=RGBA' ! glimagesink -> working.

**Comment by MicroYY** [comment]
Hi @SiewHoon 
I debugged and found that in this case, the input is BT2020 NV12, which is unsupported in media-driver. 
Seems this issue shares the same root-cause with this one https://github.com/intel/media-driver/issues/1225.
Will discuss with @FurongZhang  on how to handle this situation.

**Comment by FurongZhang** [comment]
Will check the current API if it is good for this case.

**Comment by MicroYY** [comment]
The same root-cause of https://github.com/intel/media-driver/issues/1225.

Updated docs. Pls refer to https://github.com/intel/media-driver/pull/1351
RGB 444 planar is only supported by composition path, but composition path doesn't support bt2020 color space. So in this case driver returns failure.
Currently Linux caps can't query color format and space simultaneous in one function, so a short term solution is to avoid using this format and BT2020 in apps. Long term solution need new API in Libva.
Close this issue.
