### ISSUE TITLE
GPU hang when using ffmpeg and gstreamer for h265 decoding on SG1

### ISSUE THREAD

**Issue by xhaihao** [intel/media-driver#1282]
## System information
- Impacted GPU platform: SG1 (PCI id: 0x4907)
- Host machine if it's descreted card: CFL machine but iGPU is disabled)
- Good libva/libva-utils/gmmlib/media-driver version?  It worked with production kernel and media-driver without upstream kerenel support.
- Bad libva/libva-utils/gmmlib/media-driver version? 
  libva: bc5c4b0e30ff426d7b9d6611098d02fc5c7d45d1
  gmmlib: 70d68b9f7146ef18a2522ecf1ece8075e8d8c207
  media-driver: be925680c5b03b87aab4bea8e0ea9fac65d892f9
  kernel: drm-tip: 9959c5de92d04f2336d749a5a331799aa41cfb1f ( drm-tip: 2021y-10m-28d-19h-00m-29s UTC integration manifest)

### Describe the current behavior

$> fmpeg -hwaccel qsv -c:v hevc_qsv -i input.h265 -f null -
$> gst-launch-1.0 filesrc location=input.h265 ! h265parse ! msdkh265dec ! fakesink

GPU hang  in dmesg output:
[   85.748706] i915 0000:03:00.0: [drm] Resetting vcs0 for preemption time out
[   85.748754] i915 0000:03:00.0: [drm] ffmpeg[6529] context reset due to GPU hang
[   85.759529] i915 0000:03:00.0: [drm] GPU HANG: ecode 12:4:28fffffd, in ffmpeg [6529]

### Describe the expected behavior
No GPU hang.

**Comment by Jexu** [comment]
Some questions:
It is single session or  multi-session decode?
Only hang with your h265 bitstream or any one can reproduce it? If only with your bitstream, does your h265 have realtile? i mean you can try if it works with scalability disabled.

**Comment by Jexu** [comment]
It maybe same issue as #1151 and I915 driver has plan to fix the issue by droping the bond extention in the future.

**Comment by Jexu** [comment]
btw, do you check if the bistream is slice data missing. In this case, media driver cannot handle it as it mentioned in #1373 .
I will close this issue this moment, it is kind for you to re-open it again if still having any questions.
