### ISSUE TITLE
Webkit fails to play the video correctly.

### ISSUE THREAD

**Issue by HeJunyan** [intel/media-driver#1287]
## System information
- Impacted GPU platform: Mesa Intel® HD Graphics 620 (KBL GT2)

### Describe the current behavior
The video output has garbage and artifact.

### Describe the expected behavior
Should play the video well.

You can see
https://gitlab.freedesktop.org/gstreamer/gstreamer/-/issues/877
for more details.

21.3.2-1 is OK but 21.3.5-1 is not good.

**Comment by HeJunyan** [comment]
It's a bug found by the gstreamer community.

**Comment by Sherry-Lin** [comment]
Is it related to format support issue in gst-inspect-1.0 vaapipostproc? Could you provide the cmdline to reproduce this issue?

**Comment by Jexu** [comment]
>>>21.3.2-1 is OK but 21.3.5-1 is not good.
It is umd driver regression?

**Comment by HeJunyan** [comment]
Please wait for more info from the community, I just get it from the community but I can not produce it locally. We need other maintainers root cause it.

**Comment by Jexu** [comment]
So far, any update from community?

**Comment by HeJunyan** [comment]
I think we can close it now.
