### ISSUE TITLE
Missing 21.4.2 tag?

### ISSUE THREAD

**Issue by mattst88** [intel/media-driver#1290]
https://github.com/intel/media-driver/commit/9aef03e7c1a45b49f177926559f00f34e8314e7b bumped the version to 21.4.2, but there's no corresponding git tag.

Is this intentional, or is it an oversight?

**Comment by XinfengZhang** [comment]
@Sherry-Lin

**Comment by Sherry-Lin** [comment]
Yes, the flow is bump up to new version first, once it pass bi-weekly rolling release cycle, we will tag it.

**Comment by Sherry-Lin** [comment]
21.4.2 tagged just now(https://github.com/intel/media-driver/releases/tag/intel-media-21.4.2) after passing qualification, so I will close this issue.
