### ISSUE TITLE
Missing "releases" for "tags"

### ISSUE THREAD

**Issue by Karlson2k** [intel/media-driver#1297]
This repository has many [tags](https://github.com/intel/media-driver/tags) without matching [releases](https://github.com/intel/media-driver/releases).
21.4.1, 21.4.2, 21.3.0, 21.3.1, 21.3.2, 21.3.4, 21.3.4 are all tags without releases.
It was mentioned In https://github.com/intel/media-driver/issues/1290, that code is tagged only after proper testing.

Does it mean that releases are made only after a deeper testing? 
Or the difference between "tag" and "release" is only additional files, created specially for release, and "tags" and "releases" have similar code quality and level of testing?

**Comment by mattst88** [comment]
Ping?

**Comment by Sherry-Lin** [comment]
Media-driver supports two release model
- Bi-weekly rolling release, to support some faster integration. That's the `tags` you see in GitHub.
- Quarterly release, OSV is major pick up this one. That's the `releases` you see in GitHub.

Basically these two release qualification cycles are similar but release scope may be different.

**Comment by mattst88** [comment]
Thanks, this makes sense. Feel free to close.
