### ISSUE TITLE
media-driver: hitting double free running with gst-vaapi decode pipeline with multiple decode

### ISSUE THREAD

**Issue by SiewHoon** [intel/media-driver#1300]
## System information
- CPU information(`cat /proc/cpuinfo | grep "model name" | uniq`):
model name      : Genuine Intel(R) CPU 0000 @ 1.70GHz
- GPU information(`lspci -nn | grep -E 'VGA|isplay`):
 00:02.0 VGA compatible controller [0300]: Intel Corporation Device [8086:9a78] (rev 01)
- Display server if rendering to display(X or wayland): X
- OS Ubuntu: 20.04

## Issue behavior
Every time running same command. Hitting double free.

Errror:
Pipeline is PREROLLED ...
Setting pipeline to PLAYING ...
Redistribute latency...
New clock: GstSystemClock
malloc_consolidate(): invalid chunk size
./ifpd1.sh: line 18: 215113 Aborted                 (core dumped) gst-launch-1.0 filesrc location=remote_1080_8bit_3mbps_noB.265 ! ....

Command pipeline to reproduce the issue:

**shell scripting :**
#!/bin/bash
export DISPLAY=:0
WIDTH=960
HEIGHT=720

gst-launch-1.0 \
    filesrc location=remote_1080_8bit_3mbps_noB.265 ! h265parse ! vaapih265dec ! vaapipostproc width=960 height=720 ! vaapisink \
    filesrc location=remote_1080_8bit_3mbps_noB.265 ! h265parse ! vaapih265dec ! vaapipostproc width=960 height=720 ! vaapisink \
    filesrc location=remote_1080_8bit_3mbps_noB.265 ! h265parse ! vaapih265dec ! vaapipostproc width=960 height=720 ! vaapisink \
    filesrc location=remote_1080_8bit_3mbps_noB.265 ! h265parse ! vaapih265dec ! vaapipostproc width=960 height=720 ! vaapisink \
    filesrc location=remote_1080_8bit_3mbps_noB.265 ! h265parse ! vaapih265dec ! vaapipostproc width=960 height=720 ! vaapisink \
    filesrc location=remote_1080_8bit_3mbps_noB.265 ! h265parse ! vaapih265dec ! vaapipostproc width=960 height=720 ! vaapisink \
    filesrc location=remote_1080_8bit_3mbps_noB.265 ! h265parse ! vaapih265dec ! vaapipostproc width=960 height=720 ! vaapisink \
    filesrc location=remote_1080_8bit_3mbps_noB.265 ! h265parse ! vaapih265dec ! vaapipostproc width=960 height=720 ! vaapisink \
    filesrc location=remote_1080_8bit_3mbps_noB.265 ! h265parse ! vaapih265dec ! vaapipostproc width=960 height=720 ! vaapisink \
    filesrc location=remote_1080_8bit_3mbps_noB.265 ! h265parse ! vaapih265dec ! vaapipostproc width=960 height=720 ! vaapisink \
    filesrc location=remote_1080_8bit_3mbps_noB.265 ! h265parse ! vaapih265dec ! vaapipostproc width=960 height=720 ! vaapisink \
    filesrc location=remote_1080_8bit_3mbps_noB.265 ! h265parse ! vaapih265dec ! vaapipostproc width=960 height=720 ! vaapisink

It also can reproduce using this command:
gst-launch-1.0 \
    filesrc location=remote_1080_8bit_3mbps_noB.265 ! h265parse ! vaapih265dec ! vaapisink \
    filesrc location=remote_1080_8bit_3mbps_noB.265 ! h265parse ! vaapih265dec ! vaapisink \
    filesrc location=remote_1080_8bit_3mbps_noB.265 ! h265parse ! vaapih265dec ! vaapisink

Callstack:
#0  [33m__GI_raise[m (sig=sig@entry=6) at [32m../sysdeps/unix/sysv/linux/raise.c[m:50
#1  [34m0x00007ffff7adc859[m in [33m__GI_abort[m () at [32mabort.c[m:79
#2  [34m0x00007ffff7b473ee[m in [33m__libc_message[m (action=action@entry=do_abort, fmt=fmt@entry=0x7ffff7c71285 "%s\n") at [32m../sysdeps/posix/libc_fatal.c[m:155
#3  [34m0x00007ffff7b4f47c[m in [33mmalloc_printerr[m (str=str@entry=0x7ffff7c73628 "double free or corruption (fasttop)") at [32mmalloc.c[m:5347
#4  [34m0x00007ffff7b50de5[m in [33m_int_free[m (av=0x7fffe0000020, p=0x7fffe003f2a0, have_lock=0) at [32mmalloc.c[m:4266
#5  [34m0x00007ffff3f4ba62[m in [33mMosUtilitiesSpecificNext::UserFeatureSet(_MOS_UF_KEY_NODE_T**, _MOS_UF_KEY)[m (pKeyList=pKeyList@entry=0x7ffff5cf2410 <MosUtilitiesSpecificNext::m_ufKeyList>, NewKey=...) at [32m/home/tglu205/gfx_compo
nents/drivers.gpu.virtualization.ubuntu-manifest/media/media-driver/media_softlet/linux/common/os/mos_utilities_specific_next.cpp[m:633
#6  [34m0x00007ffff3f4bcc4[m in [33mMosUtilitiesSpecificNext::UserFeatureSetValue(char*, char const*, unsigned int, void*, int)[m (strKey=0x7ffff05f9a00 "UFKEY_INTERNAL\\Report", pcValueName=pcValueName@entry=0x7ffff3f6c5b1 "Enable Vebox
 Scalability", uiValueType=uiValueType@entry=4, pData=pData@entry=0x7ffff05f9d68, nDataSize=nDataSize@entry=4) at [32m/home/tglu205/gfx_components/drivers.gpu.virtualization.ubuntu-manifest/media/media-driver/media_softlet/linux/common/o
s/mos_utilities_specific_next.cpp[m:1078
#7  [34m0x00007ffff3f4d422[m in [33mMosUtilitiesSpecificNext::UserFeatureSetValue(char*, char const*, unsigned int, void*, int)[m (nDataSize=4, pData=0x7ffff05f9d68, uiValueType=4, pcValueName=0x7ffff3f6c5b1 "Enable Vebox Scalability", s
trKey=0x7ffff05f9a00 "UFKEY_INTERNAL\\Report") at [32m/home/tglu205/gfx_components/drivers.gpu.virtualization.ubuntu-manifest/media/media-driver/media_softlet/linux/common/os/mos_utilities_specific_next.cpp[m:1292
#8  [33mMosUtilitiesSpecificNext::MosUserFeatureSetValueExFile(void*, char const*, unsigned int, unsigned int, unsigned char*, unsigned int)[m (cbData=4, lpData=0x7ffff05f9d68 "", dwType=4, Reserved=0, lpValueName=0x7ffff3f6c5b1 "Enable
Vebox Scalability", UFKey=0x4) at [32m/home/tglu205/gfx_components/drivers.gpu.virtualization.ubuntu-manifest/media/media-driver/media_softlet/linux/common/os/mos_utilities_specific_next.cpp[m:1292
#9  [33mMosUtilities::MosUserFeatureSetValueEx(void*, char const*, unsigned int, unsigned int, unsigned char*, unsigned int)[m (UFKey=UFKey@entry=0x2, lpValueName=0x7ffff3f6c5b1 "Enable Vebox Scalability", Reserved=Reserved@entry=0, dwTy
pe=4, lpData=0x7ffff05f9d68 "", cbData=4) at [32m/home/tglu205/gfx_components/drivers.gpu.virtualization.ubuntu-manifest/media/media-driver/media_softlet/linux/common/os/mos_utilities_specific_next.cpp[m:1464
#10 [34m0x00007ffff3f01a58[m in [33mMosUtilities::MosUserFeatureWriteValueBinary(void*, MOS_USER_FEATURE_VALUE*, _MOS_USER_FEATURE_VALUE_DATA*)[m (pDataValue=<optimized out>, pFeatureValue=<optimized out>, UFKey=<optimized out>) at [32m/
home/tglu205/gfx_components/drivers.gpu.virtualization.ubuntu-manifest/media/media-driver/media_softlet/agnostic/common/os/mos_utilities_next.cpp[m:1886
#11 [33mMosUtilities::MosUserFeatureWriteValuesTblID(_MOS_USER_FEATURE_VALUE_WRITE_DATA*, unsigned int, MOS_USER_FEATURE_KEY_PATH_INFO*)[m (pWriteValues=pWriteValues@entry=0x7ffff05f9d60, uiNumOfValues=uiNumOfValues@entry=1, ufInfo=0x0)
at [32m/home/tglu205/gfx_components/drivers.gpu.virtualization.ubuntu-manifest/media/media-driver/media_softlet/agnostic/common/os/mos_utilities_next.cpp[m:2163
#12 [34m0x00007ffff3f01ced[m in [33mMosUtilities::MosUserFeatureWriteValuesID(_MOS_USER_FEATURE_INTERFACE*, _MOS_USER_FEATURE_VALUE_WRITE_DATA*, unsigned int, void*)[m (pOsUserFeatureInterface=pOsUserFeatureInterface@entry=0x0, pWriteVal
ues=pWriteValues@entry=0x7ffff05f9d60, uiNumOfValues=uiNumOfValues@entry=1, mosCtx=<optimized out>) at [32m/home/tglu205/gfx_components/drivers.gpu.virtualization.ubuntu-manifest/media/media-driver/media_softlet/agnostic/common/os/mos_ut
ilities_next.cpp[m:2213
#13 [34m0x00007ffff3ba5569[m in [33mMOS_UserFeature_WriteValues_ID(PMOS_USER_FEATURE_INTERFACE, PMOS_USER_FEATURE_VALUE_WRITE_DATA, uint32_t, MOS_CONTEXT_HANDLE)[m (pOsUserFeatureInterface=pOsUserFeatureInterface@entry=0x0, pWriteValues=
pWriteValues@entry=0x7ffff05f9d60, uiNumOfValues=uiNumOfValues@entry=1, mosCtx=<optimized out>) at [32m/home/tglu205/gfx_components/drivers.gpu.virtualization.ubuntu-manifest/media/media-driver/media_driver/agnostic/common/os/mos_utiliti
es.cpp[m:6622
#14 [34m0x00007ffff3f31a31[m in [33mvp::VpVeboxCmdPacket::RenderVeboxCmd(_MOS_COMMAND_BUFFER*, _MHW_VEBOX_DI_IECP_CMD_PARAMS&, _VPHAL_VEBOX_SURFACE_STATE_CMD_PARAMS&, _MHW_VEBOX_SURFACE_STATE_CMD_PARAMS&, _MHW_VEBOX_STATE_CMD_PARAMS&, _M
HW_MI_FLUSH_DW_PARAMS&, _RENDERHAL_GENERIC_PROLOG_PARAMS*)[m (this=0x7fffe8209808, CmdBuffer=<optimized out>, VeboxDiIecpCmdParams=..., VeboxSurfaceStateCmdParams=..., MhwVeboxSurfaceStateCmdParams=..., VeboxStateCmdParams=..., FlushDwPa
rams=..., pGenericPrologParams=0x7ffff05faab0) at [32m/home/tglu205/gfx_components/drivers.gpu.virtualization.ubuntu-manifest/media/media-driver/media_softlet/agnostic/common/vp/hal/packet/vp_vebox_cmd_packet.cpp[m:1504
#15 [34m0x00007ffff3f2c29e[m in [33mvp::VpVeboxCmdPacket::SendVeboxCmd(_MOS_COMMAND_BUFFER*)[m (this=0x7fffe8209808, commandBuffer=0x7ffff05faf90) at [32m/home/tglu205/gfx_components/drivers.gpu.virtualization.ubuntu-manifest/media/media
-driver/media_softlet/agnostic/common/vp/hal/packet/vp_vebox_cmd_packet.cpp[m:1128
#16 [34m0x00007ffff3efa2df[m in [33mCmdTask::Submit(bool, MediaScalability*, CodechalDebugInterface*)[m (this=0x7fffe8789100, immediateSubmit=<optimized out>, scalability=0x7fffe8009f40, debugInterface=<optimized out>) at [32m/home/tglu2
05/gfx_components/drivers.gpu.virtualization.ubuntu-manifest/media/media-driver/media_softlet/agnostic/common/shared/task/media_cmd_task.cpp[m:115
#17 [34m0x00007ffff3f281bc[m in [33mvp::PacketPipe::Execute(MediaStatusReport*, MediaScalability*&, MediaContext*, bool, unsigned char)[m (this=0x7fffe8795e50, statusReport=0x0, scalability=@0x7fffe8005060: 0x7fffe8009f40, mediaContext=0
x7fffe8507880, bEnableVirtualEngine=true, numVebox=1 '\001') at [32m/home/tglu205/gfx_components/drivers.gpu.virtualization.ubuntu-manifest/media/media-driver/media_softlet/agnostic/common/vp/hal/packet/vp_packet_pipe.cpp[m:281
#18 [34m0x00007ffff3f33858[m in [33mvp::VpPipeline::ExecuteVpPipeline()[m (this=0x7fffe8005010) at [32m/home/tglu205/gfx_components/drivers.gpu.virtualization.ubuntu-manifest/media/media-driver/media_softlet/agnostic/common/vp/hal/pipeli
ne/vp_pipeline.cpp[m:299
...
...

### Describe the expected behavior
Graceful exit gstreamer running application pipeline without hitting double free message.

## Debug information
- What's libva/libva-utils/gmmlib/media-driver version?
- Q3'2021 media stack release / media-driver latest from master

**Comment by SiewHoon** [comment]
This issue does not reproduce by using Q2'2021 Media stack release.

**Comment by SiewHoon** [comment]
This issue not able reproduce without this patch : https://github.com/intel/media-driver/commit/99690b6c66eccc710772a1ea82b8d626a7c7089c + Q3'2021 media driver.

Also git checkout this commit 99690b6c66eccc710772a1ea82b8d626a7c7089c  and install it in the system able to reproduce the issue.

**Comment by Sherry-Lin** [comment]
it's related to MOS change, so move to media common team debug.

**Comment by pingliwa** [comment]
Please help to try this PR https://github.com/intel/media-driver/pull/1305

**Comment by SiewHoon** [comment]
Done verified using this PR#1305. The issue no longer able to reproduce.

**Comment by Sherry-Lin** [comment]
Thanks @SiewHoon  for quick check. We will try to merge the code as quick as possible.

**Comment by hye5** [comment]
Can u update the HSD to fix implemented?

**Comment by SiewHoon** [comment]
The issue fixed in PR#1305 fixed and code already merged. Move this issue to closed.
