### ISSUE TITLE
Is it possible to make hardware acceleration effective without display attached

### ISSUE THREAD

**Issue by cloudjiang2** [intel/media-driver#1323]
There are two graphics cards in a windows 10 host, one is UHD, another is Geforce 1030, I found that MSDK hardware acceleration (HEVC decode/encode) works only when there is display attached to UHD graphics. My requirements:
1. two 4K displays attached to Geforce
2. UHD do video encode/decode acceleration without display attached

**Comment by XinfengZhang** [comment]
I suppose it is not suitable to report the issue here:
1. it is a windows issue , not open source linux media driver issue.
2. it is about MSDK, @onabiull  could you help to answer the question?

**Comment by Xiaogangli-intel** [comment]
Close this issue because it's not a media driver issue.
