### ISSUE TITLE
What's wrong with this?

### ISSUE THREAD

**Issue by kingskill** [intel/media-driver#1331]
/libva/media-driver/media_driver/agnostic/common/cm/cm_mem_sse2_impl.cpp:27:
/media/king/1000G/004_包裹/Deepin/直接运行/libva/media-driver/media_softlet/agnostic/common/os/mos_interface.h:1832:58: error: ‘ADAPTER_BDF’ has not been declared
     static MOS_STATUS GetAdapterBDF(PMOS_CONTEXT mosCtx, ADAPTER_BDF *adapterBDF);
                                                          ^~~~~~~~~~~
make[2]: *** [media_driver/CMakeFiles/iHD_drv_video_SSE4.dir/build.make:63：media_driver/CMakeFiles/iHD_drv_video_SSE4.dir/linux/common/cm/hal/cm_mem_os_sse4_impl.cpp.o] 错误 1
make[1]: *** [CMakeFiles/Makefile2:174：media_driver/CMakeFiles/iHD_drv_video_SSE4.dir/all] 错误 2
make[2]: *** [media_driver/CMakeFiles/iHD_drv_video_SSE2.dir/build.make:63：media_driver/CMakeFiles/iHD_drv_video_SSE2.dir/agnostic/common/cm/cm_mem_sse2_impl.cpp.o] 错误 1
make[1]: *** [CMakeFiles/Makefile2:211：media_driver/CMakeFiles/iHD_drv_video_SSE2.dir/all] 错误 2

**Comment by kingskill** [comment]
error: ‘ADAPTER_BDF’ has not been declared

This is the problem.

**Comment by XinfengZhang** [comment]
please update the gmmlib, the definition is defined in latest gmmlib. thanks

**Comment by kingskill** [comment]
> 

Intel Media Driver 2021Q4 Release - 22.1.1
intel-gmmlib-22.0.1
Libva 2.13.0

I installed these version. But still not work. 

error: ‘ADAPTER_BDF’ has not been declared

**Comment by kingskill** [comment]
![截图_deepin-terminal_20220122225819](https://user-images.githubusercontent.com/43365116/150643708-6043502c-d274-4f0d-963d-7ff9d2dc93cb.png)

**Comment by kingskill** [comment]
> please update the gmmlib, the definition is defined in latest gmmlib. thanks

Please help.

**Comment by kingskill** [comment]
My system:
![截图_deepin-terminal_20220122230719](https://user-images.githubusercontent.com/43365116/150644049-cf8ad6b7-ba92-42f6-a8ad-e2db4427200d.png)

**Comment by XinfengZhang** [comment]
the ADAPTER_BDF is added by https://github.com/intel/gmmlib/commit/94306f5443b97d9762dbb35ba65b341ee3e91cf0
and it is in intel-gmmlib-22.0.1
so, I guess that there are multiple gmmlib on your machine?

**Comment by Xiaogangli-intel** [comment]
Hi @kingskill, did you build successfully?
