### ISSUE TITLE
cannot build

### ISSUE THREAD

**Issue by zzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzz-z** [intel/media-driver#1345]
## System information
- CPU information(`cat /proc/cpuinfo | grep "model name" | uniq`): model name      : 12th Gen Intel(R) Core(TM) i9-12900K
- Display server if rendering to display(X or wayland): no display, have x11 wayland installed.

## Debug information
- What's libva/libva-utils/gmmlib/media-driver version? 2.13.0/?/22.0.2/22.1.1
- Could you confirm whether GPU hardware exist or not by `ls /dev/dri`? no file or dir
- Could you provide vainfo log if possible by `vainfo >vainfo.log 2>&1`? [empty output]

root@server ~/media-driver-intel-media-22.1.1/build_media # cmake ../media_driver/
CMake Warning (dev) in CMakeLists.txt:
  No project() command is present.  The top-level CMakeLists.txt file must
  contain a literal, direct call to the project() command.  Add a line of
  code such as

    project(ProjectName)

  near the top of the file, but after cmake_minimum_required().

  CMake is pretending there is a "project(Project)" command on the first
  line.
This warning is for project developers.  Use -Wno-dev to suppress it.

-- The C compiler identification is GNU 10.2.1
-- The CXX compiler identification is GNU 10.2.1
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working C compiler: /usr/bin/cc - skipped
-- Detecting C compile features
-- Detecting C compile features - done
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Check for working CXX compiler: /usr/bin/c++ - skipped
-- Detecting CXX compile features
-- Detecting CXX compile features - done
*BUILD_TYPE not defined, default to: release
CMake Error at CMakeLists.txt:86 (include):
  include could not find load file:

    /root/media-driver-intel-media-22.1.1/media_driver/media_driver/cmake/media_defs.cmake

CMake Error at CMakeLists.txt:88 (include):
  include could not find load file:

    /media_utils.cmake

-- Found PkgConfig: /usr/bin/pkg-config (found version "0.29.2") 
-- Found X11: /usr/include   
-- Looking for XOpenDisplay in /usr/lib/x86_64-linux-gnu/libX11.so;/usr/lib/x86_64-linux-gnu/libXext.so
-- Looking for XOpenDisplay in /usr/lib/x86_64-linux-gnu/libX11.so;/usr/lib/x86_64-linux-gnu/libXext.so - found
-- Looking for gethostbyname
-- Looking for gethostbyname - found
-- Looking for connect
-- Looking for connect - found
-- Looking for remove
-- Looking for remove - found
-- Looking for shmat
-- Looking for shmat - found
-- Looking for IceConnectionNumber in ICE
-- Looking for IceConnectionNumber in ICE - found
CMake Error at media_top_cmake.cmake:29 (include):
  include could not find load file:

    /media_gen_flags.cmake
Call Stack (most recent call first):
  CMakeLists.txt:95 (include)

CMake Error at media_top_cmake.cmake:30 (include):
  include could not find load file:

    /media_feature_flags.cmake
Call Stack (most recent call first):
  CMakeLists.txt:95 (include)

-- Checking for module 'igdgmm'
--   Found igdgmm, version 12.0.0
-- media -- PLATFORM = linux
-- media -- ARCH = 64
-- media -- CMAKE_CURRENT_LIST_DIR = /root/media-driver-intel-media-22.1.1/media_driver
-- media -- INCLUDED_LIBS = 
-- media -- LIB_NAME = iHD_drv_video
-- media -- OUTPUT_NAME = 
-- media -- BUILD_TYPE/UFO_BUILD_TYPE/CMAKE_BUILD_TYPE = release/release/Release
-- media -- LIBVA_INSTALL_PATH = 
-- media -- MEDIA_VERSION = 
-- media -- X11 Found
-- Checking for module 'libva-x11'
--   Found libva-x11, version 1.13.0
CMake Error at media_top_cmake.cmake:65 (media_include_subdirectory):
  Unknown CMake command "media_include_subdirectory".
Call Stack (most recent call first):
  CMakeLists.txt:95 (include)

-- Configuring incomplete, errors occurred!

**Comment by XinfengZhang** [comment]
cmake .. do not use cmake ../media_driver, the upper cmake file is in the parent folder
