### ISSUE TITLE
[ATS-M3]Gup frequency cannot be locked

### ISSUE THREAD

**Issue by xinyudox** [intel/media-driver#1363]
os: ubuntu 20.04
kernel: 5.10.54+prerelease2400
libva: dad7abcb958b97b50c318dd42a477e035a42e358
ffmpeg: 534c4db1800ebdb1e7dab031a63413d74bab4bf8
gmmlib: 29152fc6d39f87983b176664f225d42af039f716
media-driver: c8decb7f6e8bc1c77f6becdbe7bbe0e1697d62e8

eg:
echo 1200 > /sys/class/card0/gt_max_freq_mhz

In fact, GPU still uses the maximum value.

**Comment by Xiaogangli-intel** [comment]
@xinyudox, could you share which platform are you working on?

**Comment by Xiaogangli-intel** [comment]
Hi @xinyudox, did you tried to disable RC6? Any update on the environment preparation?

**Comment by xinyudox** [comment]
this issue can't be reproduced, and close it.
