### ISSUE TITLE
VPP: Should not report VAProcFilterHighDynamicRangeToneMapping ability on Gen9- platform.

### ISSUE THREAD

**Issue by HeJunyan** [intel/media-driver#1392]
## System information
- GPU information(`lspci -nn | grep -E 'VGA|isplay`): Gen9 and older platform.

### Describe the current behavior
It seems that the tone mapping feature is introduced in Gen9.5, so the old platform should not report that ability.
The driver reports this feature now. But it can not really work when we try to use them on Gen9.

### Describe the expected behavior
The driver should not report this feature on Gen9- platform.

**Comment by FurongZhang** [comment]
HDR Tone Mapping is supported from KBL.

**Comment by HeJunyan** [comment]
KBL is gen9.5 and SKL is Gen9, which should not have this feature.

**Comment by FurongZhang** [comment]
> KBL is gen9.5 and SKL is Gen9, which should not have this feature.

Got it. Understand the issue. Will change that. Thanks for the report.

**Comment by FurongZhang** [comment]
Fix PR: https://github.com/intel/media-driver/pull/1409
