### ISSUE TITLE
Encoder can not insert normal B frames in HEVC SCC related profiles in low power mode on TGL.

### ISSUE THREAD

**Issue by HeJunyan** [intel/media-driver#1401]
## System information
- GPU information(`lspci -nn | grep -E 'VGA|isplay`): TGL

### Describe the current behavior
The HEVC SCC related profiles can not encode normal B frames. But in VAConfigAttribPredictionDirection query,  it returns both VA_PREDICTION_DIRECTION_PREVIOUS and VA_PREDICTION_DIRECTION_FUTURE, which means it can support normal B frames.

### Describe the expected behavior
Add the support for normal B frames, or correct the query result.

## Debug information
gst-launch-1.0 -vf videotestsrc num-buffers=30 ! video/x-raw,format=NV12,width=800,height=600 ! vaapih265enc tune=low-power rate-control=cqp max-bframes=1 refs=2 ! video/x-h265,profile=screen-extended-main ! h265parse ! filesink location=out.h265

fails and print log:

[CODEC]:CRITICAL - ValidateRefFrameData:2129: MOS returned error, eStatus = 0x2
[CODEC]:CRITICAL - SetSliceStructs:1297: MOS returned error, eStatus = 0x2
[CODEC]:CRITICAL - InitializePicture:2294: MOS returned error, eStatus = 0x2
[CODEC]:CRITICAL - InitializePicture:3099: MOS returned error, eStatus = 0x2
[CODEC]:CRITICAL - ExecuteEnc:4869: Encoding initialization failed.
[CODEC]:CRITICAL - Execute:613: MOS returned error, eStatus = 0x2
[LIBVA]:CRITICAL - EncodeInCodecHal:406: DDI:Failed in Codechal!
[LIBVA]:CRITICAL - EndPicture:81: DDI:DdiEncode_EncodeInCodecHal return failure.

**Comment by Xiaogangli-intel** [comment]
Hi @HeJunyan, SCC only support low delay B, will correct the report.
