### ISSUE TITLE
The md5 value of the decoded yuv file does not match

### ISSUE THREAD

**Issue by wenqingx** [intel/media-driver#1403]
## System information
- CPU information:11th Gen Intel(R) Core(TM) i7-1165G7 @ 2.80GHz
- GPU information:0000:00:02.0 VGA compatible controller [0300]: Intel Corporation Device [8086:9a49] (rev 01)

- Display server if rendering to display(X or wayland):

### Describe the current behavior
The md5 value of the decoded yuv file does not match
## Debug information
- What's libva/libva-utils/gmmlib/media-driver version?
- libva:dad7abcb958b97b50c318dd42a477e035a42e358
- gmmlib:29152fc6d39f87983b176664f225d42af039f716
- intel-media-driver:cc45aa2772571605fb9523453fa983e76e42cf88
- Could you confirm whether GPU hardware exist or not by `ls /dev/dri`?yes
- Could you provide vainfo log if possible by `vainfo >vainfo.log 2>&1`?
- Could you provide libva trace log if possible? Run cmd `export LIBVA_TRACE=/tmp/libva_trace.log` first then execute the case.
- Could you attach dmesg log if it's GPU hang by `dmesg >dmesg.log 2>&1`?
- Do you want to contribute a patch to fix the issue? (yes/no):

**Comment by dvrogozh** [comment]
Which application you were using? Can you share command line and stream if that's open source sample or tool?

Which codec was used?

md5 does not match against what exactly? (sw codec - which one? or against prev. run of hw decoder?)
