### ISSUE TITLE
[gstreamer-vaapi][vpp] incorrect color transformed by any option of vaap.

### ISSUE THREAD

**Issue by feiwan1** [intel/media-driver#141]
System Environment
OS Ubuntu 17.04
Kernel 4.10
Hardware Skylake Intel(R) Core(TM) i5-6600K CPU @ 3.50GHz
libva tag 2.1.0
intel-media-driver f6283e2edf9af95db2007bb79e30fb9afcf2c839
gst-vaapi tag 1.13.90

Reproduce Steps
If set any options of vaapipostproc, the output color will become incorrect. For example:
$ gst-launch-1.0 videotestsrc ! vaapipostproc brightness=0.1 ! vaapisink
$ gst-launch-1.0 videotestsrc ! vaapipostproc denoise=1 ! vaapisink
$ gst-launch-1.0 videotestsrc ! vaapipostproc scale-method=1 ! vaapisink

Attach log file with va trace get by the cmd:
$ LIBVA_TRACE=./bright gst-launch-1.0 videotestsrc ! vaapipostproc brightness=0.1 ! vaapisink

The attach picture shows the different color with vaapi driver by using same cmdline. Left is vaapi driver. Right is media driver.

![img_20180412_145335](https://user-images.githubusercontent.com/25519094/38661885-faa1a216-3e64-11e8-8d02-a0eaed722bd4.jpg)

[bright.192946.thd-0x00007cad.log](https://github.com/intel/media-driver/files/1901709/bright.192946.thd-0x00007cad.log)
[bright.192946.thd-0x00007cab.log](https://github.com/intel/media-driver/files/1901710/bright.192946.thd-0x00007cab.log)
[bright.192946.thd-0x00007cac.log](https://github.com/intel/media-driver/files/1901711/bright.192946.thd-0x00007cac.log)

**Comment by FurongZhang** [comment]
We have already fixed a similar issue. And we are trying if this issue can be reproduced with our latest fix.

**Comment by Jister** [comment]
This issue has been fixed with the latest driver.
