### ISSUE TITLE
[Bug]: [regression][ffmpe-vaap&gst-va] decode.10bit.vp9 new fail case on CFL & ICL

### ISSUE THREAD

**Issue by wenqingx** [intel/media-driver#1434]
### Which component impacted?

Decode

### Is it regression? Good in old configuration?

Yes, it's good in old version

### What happened?

1.ffmepg-vaapi on CFL&ICL; gst-va on ICL
2.libva : 395e502d162f
gmmlib : 0f0d3bfa0c71
msdk : 34ec1df8448c
3.ffmpeg -hwaccel vaapi -init_hw_device vaapi=hw:/dev/dri/renderD128 -hwaccel_output_format p010le -hwaccel_flags allow_profile_mismatch -v verbose -i input.ivf -pix_fmt p010le -f rawvideo -vsync passthrough -autoscale 0 -vframes 6 -y output.yuv

gst-launch-1.0 -vf filesrc input.ivf ! ivfparse ! vp9parse ! vavp9dec ! videoconvert chroma-mode=none dither=0 ! video/x-raw,format=P010_10LE ! checksumsink2 qos=false file-checksum=false frame-checksum=false plane-checksum=false eos-after=6 dump-output=true  dump-location=output.yuv

4.the first bad commit : intel-medai-driver 3e13ecaf895c24a2a1775c637e2a0380be373763
last good commit: intel-medai-driver 705fe411e03e0e0ad1ff43974c1656e18e4846cb

### What's the usage scenario when you are seeing the problem?

Others

### What impacted?

More than 160 new fail cases.

### Debug Information

Hello!
These are some error messages of GST and ffmpeg commands. 
Do I need to add some other information? thanks.

ffmpeg:
[AVHWFramesContext @ 0x7fc53c000a40] Failed to sync surface 0x15: 23 (internal decoding error).
[vp9 @ 0x563c42b57ac0] Failed to transfer data to output frame: -5.
Error while processing the decoded data for stream #0:0
[AVIOContext @ 0x563c42b47640] Statistics: 700386 bytes written, 0 seeks, 3 writeouts
[AVIOContext @ 0x563c42b4edc0] Statistics: 137589 bytes read, 0 seeks
Conversion failed!

gst:
Pipeline is PREROLLED ...
Setting pipeline to PLAYING ...
Redistribute latency...
New clock: GstSystemClock
0:00:00.040084153 25487 0x55dcac4339e0 ERROR              videometa gstvideometa.c:247:default_map: cannot map memory range 0-1
0:00:00.040103988 25487 0x55dcac4339e0 ERROR                default video-frame.c:168:gst_video_frame_map_id: failed to map video frame plane 0
0:00:00.040123543 25487 0x55dcac4339e0 ERROR          checksumsink2 gstchecksumsink.c:420:gst_cksum_image_sink_render:<cksumimagesink0> failed to map frame
Got EOS from element "pipeline0".
Execution ended after 0:00:00.002966817
Setting pipeline to NULL ...
Freeing pipeline ...

**Comment by Jexu** [comment]
I suggest that:
1)	Check the output yuv to see if there is something like corruption, artifact...(better to compare the output yuv with that by reverting my commit as well)
2)	Try your case with sample_decoder to confirm if it is ffmpeg specific failure.
