### ISSUE TITLE
[Bug]:  decode/mpeg2 issue on DG2/ATSM, vaEndPicture return error

### ISSUE THREAD

**Issue by fanli-hub** [intel/media-driver#1457]
### Which component impacted?

Decode

### Is it regression? Good in old configuration?

No, this issue exist a long time

### What happened?

Ubuntu 20.04.4 LTS
The latest version components
Or
<html xmlns:o="urn:schemas-microsoft-com:office:office"
xmlns:dt="uuid:C2F41010-65B3-11d1-A29F-00AA00C14882"
xmlns="http://www.w3.org/TR/REC-html40">

<head>

<meta name=ProgId content=OneNote.File>
<meta name=Generator content="Microsoft OneNote 15">
</head>

<body lang=en-US style='font-family:Calibri;font-size:11.0pt'>

<div style='direction:ltr'>

libva | a1443632946344d68d54b09241eaf17d31dbd584
-- | --
Libva-utils | 69703e30f8c8d6f457a7805792f1b3ecc3b4e5ea
gmmlib | 102bb47557e57e7e58d74769105270345ed43c9a
Media-driver | 46888e8a435ff36f405229c6834ca71a108c8ad6
Vpl dispatcher | ed898448e82651f7d3445bad92488bc13181253e
Vpl runtime | e0d2754d0250661a63fff2ee2fa8e0e94b0fcfad
Cartwheel-ffmpeg | ac39e28bc3a96180b28f5323363ea2c6da835d4b

</div>

</body>

</html>

Reproduce cmd:
ffmpeg -hwaccel vaapi -vaapi_device /dev/dri/renderD128 -v verbose -i sony-ct1.bits.mpeg2 -vframes 1 -f null -

Error message:
[mpeg2video @ 0x55cc3987cb40] Failed to end picture decode issue: 23 (internal decoding error).
[mpeg2video @ 0x55cc3987cb40] hardware accelerator failed to decode picture

### What's the usage scenario when you are seeing the problem?

Video Analytics

### Do you want to contribute a patch to fix the issue?

No.

**Comment by Jexu** [comment]
It is normal clip or error clip of mpeg2 file? Does it happen for other mpeg2 decoding?  How about sample_decoder?

**Comment by stellawuintel** [comment]
Auto Created VSMGWL-54531 for further analysis.

**Comment by stellawuintel** [comment]
Auto Created VSMGWL-54531 for further analysis.

**Comment by fanli-hub** [comment]
> It is normal clip or error clip of mpeg2 file? Does it happen for other mpeg2 decoding? How about sample_decoder?

It is an error clip. Sample_decode works correctly. And this issue only occurred on DG2/ATSM.

**Comment by Jexu** [comment]
It is expected result since it is error clip decoding. Media driver get decode error from hw and return the value to app, sample_decode treats the error(mb error) as success, but ffmpeg doesn't. So both show different result.

**Comment by feiwan1** [comment]
ffmpeg-vaapi pass each slice data with a vaBuffer, while sample_decode pass all slice data into one vaBuffer. Does this can cause different vaEndPicture result?

Some debug log:
[MOS]:  CRITICAL - GetResourceInfo:1762: Invalid (nullptr) Pointer.
[MHW]:  CRITICAL - AddMfxPipeBufAddrCmd:984: MOS returned error, eStatus = 0x5
[MHW]:  CRITICAL - AddMfxPipeBufAddrCmd:89: MOS returned error, eStatus = 0x5
[CODEC]:CRITICAL - AddMfxPipeBufAddrCmd:92: MOS returned error, eStatus = 0x5
[CODEC]:CRITICAL - Execute:49: MOS returned error, eStatus = 0x5
[CODEC]:CRITICAL - PackPictureLevelCmds:94: MOS returned error, eStatus = 0x5
[CODEC]:CRITICAL - Submit:64: MOS returned error, eStatus = 0x5
[CODEC]:CRITICAL - Submit:127: MOS returned error, eStatus = 0x5
[CODEC]:CRITICAL - ExecuteActivePackets:297: MOS returned error, eStatus = 0x5
[CODEC]:CRITICAL - Execute:217: MOS returned error, eStatus = 0x5
[LIBVA]:CRITICAL - EndPicture:936: DDI:DdiDecode_DecodeInCodecHal return failure.

Btw, on Legacy platform like CFL/KBL, same cmd and clip doesn't have this issue.

**Comment by Jexu** [comment]
Your log shows the resource becoming nullptr before hw execution.
You can step into last two function to check if something wrong and what causes that.

**Comment by Jexu** [comment]
First carsh in https://github.com/intel/media-driver/blob/master/media_softlet/agnostic/common/codec/hal/dec/mpeg2/features/decode_mpeg2_basic_feature.cpp#L187 and look like incorrect picture_structure sent by ffmpeg causes this assert.
Suggess to compare the pic/ slice params between ffmpeg and sample decode by capturing libva trace.
