### ISSUE TITLE
[License] No explicit grant of license found

### ISSUE THREAD

**Issue by rahulmohang** [intel/media-driver#1460]
The license header in the following files do not have explicit grant of rights to use or redistribute:

https://github.com/intel/media-driver/blob/master/media_driver/agnostic/common/vp/hal/vphal_render_16alignment.h
https://github.com/intel/media-driver/blob/master/media_driver/agnostic/common/vp/hal/vphal_render_16alignment.cpp

The license text is just a disclaimer:
"
* INTEL MAKES NO WARRANTY OF ANY KIND REGARDING THE CODE.  THIS CODE IS
* LICENSED ON AN "AS IS" BASIS AND INTEL WILL NOT PROVIDE ANY SUPPORT,
* ASSISTANCE, INSTALLATION, TRAINING OR OTHER SERVICES.  INTEL DOES NOT
* PROVIDE ANY UPDATES, ENHANCEMENTS OR EXTENSIONS.  INTEL SPECIFICALLY
* DISCLAIMS ANY WARRANTY OF MERCHANTABILITY, NONINFRINGEMENT, FITNESS FOR ANY
* PARTICULAR PURPOSE, OR ANY OTHER WARRANTY.  Intel disclaims all liability,
* including liability for infringement of any proprietary rights, relating to
* use of the code. No license, express or implied, by estoppel or otherwise,
* to any intellectual property rights is granted herein.
"

It would be good to have an explicit license grant.

**Comment by FurongZhang** [comment]
Received the issues. Will handle that.

**Comment by rahulmohang** [comment]
Thank you @FurongZhang @Sherry-Lin @LhGu @intel-mediadev
