### ISSUE TITLE
conformance::libva-utils test regression with commit e1d367472b56

### ISSUE THREAD

**Issue by jayesht** [intel/media-driver#152]
In TestSuite - libva-utils.test.test_va_api . GetCreateConfig/VAAPIGetCreateConfig

test_va_api_fixture.cpp:225
      Expected: VaapiStatus(expectation)
      Which is: VA_STATUS_ERROR_UNSUPPORTED_RT_FORMAT
To be equal to: VaapiStatus(vaCreateConfig(m_vaDisplay, profile, entrypoint, (attribs.size() != 0 ? const_cast<VAConfigAttrib*>(attribs.data()) : __null), attribs.size(), &m_configID))
      Which is: VA_STATUS_SUCCESS
profile    = 12:VAProfileJPEGBaseline
entrypoint = 7:VAEntrypointEncPicture
numAttribs = 1
Google Test trace:
test_va_api_get_create_config.cpp:87: 0x0:0x3001f:0x100:0

Test Param = (12:VAProfileJPEGBaseline, 7:VAEntrypointEncPicture)

Affects both Ubuntu and Fedora

**Comment by uartie** [comment]
Exact test case is `GetCreateConfig/VAAPIGetCreateConfig.CreateConfigWithAttributes/126`
