### ISSUE TITLE
[Bug]: What's the license status of media_driver/agnostic/Xe_M/Xe_XPM/vp/kernel/cmfcpatch/igvpkrn_xe_xpm_cmfcpatch.c?

### ISSUE THREAD

**Issue by sebastinas** [intel/media-driver#1521]
### Which component impacted?

Build

### Is it regression? Good in old configuration?

Yes, it's good in old version

### What happened?

Same as #1517, but this time for `media_driver/agnostic/Xe_M/Xe_XPM/vp/kernel/cmfcpatch/igvpkrn_xe_xpm_cmfcpatch.c`.

### What's the usage scenario when you are seeing the problem?

Others

### Do you want to contribute a patch to fix the issue?

No.

**Comment by FurongZhang** [comment]
@LhGu , is it possible for you to follow up this issue?

**Comment by Xiaogangli-intel** [comment]
Hi @sebastinas, could you teach us how you found these issues? We will add to our build in the same way, so we can catch issues earlier.

**Comment by sebastinas** [comment]
The list also available from https://salsa.debian.org/multimedia-team/intel-media-driver/-/blob/master/debian/copyright

**Comment by LhGu** [comment]
I confirmed all files in the list and maked a PR to fix it.

**Comment by sebastinas** [comment]
22.6.0 together with this patch makes it work for the Debian package. Thanks @LhGu.

**Comment by LhGu** [comment]
> 22.6.0 together with this patch makes it work for the Debian package. Thanks @LhGu.

Thanks for your double confirm, and we will merge it ASAP.
