### ISSUE TITLE
[Bug]: segv when calling vaDestroyContext

### ISSUE THREAD

**Issue by richy759** [intel/media-driver#1529]
### Which component impacted?

Decode

### Is it regression? Good in old configuration?

No, this issue exist a long time

### What happened?

1. When starting and stopping decoders I sometimes get a SIGSEGV when closing a decoder. I'm using ffmpeg library and have multiple decoders starting and stopping.
2. Using version 22.5.4, this has been seen in previous versions.
3. I've compiled with debug symbols and source so can see the SIGSEGV in DdiMedia_FreeBufferHeapElements() (media_libva_decoder.cpp) in the loop where it looks for buffers which match our decoder context, line with `if (nullptr == mediaBufferHeapElmt->pBuffer)`
4. I can see that mediaCtx->uiNumBufs is 748485 but in the for loop here elementId has reached 752638.

### What's the usage scenario when you are seeing the problem?

Playback

### Debug Information

gmmlib version 22.2.1
[vainfo.log](https://github.com/intel/media-driver/files/9878531/vainfo.log)

### Do you want to contribute a patch to fix the issue?

No.

**Comment by Jexu** [comment]
Can you help try above fix and share the call stack as well if not work.

**Comment by intel-mediadev** [comment]
Auto Created VSMGWL-58430 for further analysis.

**Comment by richy759** [comment]
> Can you help try above fix and share the call stack as well if not work.

Will do

**Comment by richy759** [comment]
I've been running this for a few days and believe it has fixed the problem I was seeing. Thanks

**Comment by Jexu** [comment]
Good to know it and I will get the pr merged and close this issue.
