### ISSUE TITLE
[Bug]: vaGetImage is very slow on dGPU when decode a 4K 10bit clip

### ISSUE THREAD

**Issue by mengker33** [intel/media-driver#1537]
### Which component impacted?

Decode

### What happened?

1. On linux, using gstreamer va plugins to decode a 4K p010 format bitstream:<pre> gst-launch-1.0 -vf filesrc location=4k_p010.h265 ! h265parse ! vah265dec ! fakesink</pre>
2. The whole process for running the cmd line above is extremely slow (**~3sec for one frame**). Debugging into it, I found the slow step happened at GPU to CPU copy using vaGetImage. I don't see it slow on iGPU. Also, when I tried to use vaDeriveImage, the speed is normally quick.

### What's the usage scenario when you are seeing the problem?

Others

### What impacted?

Decoding a 4K ( with formats expect NV12) clip is a quite basic function. We expect faster decoding on dGPU instead of much slower than iGPU.

**Comment by Jexu** [comment]
Could you help check if blt copy in 'SwizzleSurface' or cpu copy in 'DdiMedia_CopyPlane' cost the time?

**Comment by mengker33** [comment]
> Could you help check if blt copy in 'SwizzleSurface' or cpu copy in 'DdiMedia_CopyPlane' cost the time?

I think yes. I have seen not-NV12 format will go into SwizzleSurface, then there is a call for **cpublt** is quite slow.

**Comment by intel-mediadev** [comment]
Auto Created VSMGWL-58535 for further analysis.

**Comment by uartie** [comment]
FFmpeg vaapi 10bit decode is very slow, too, on dGPU.

**Comment by Jexu** [comment]
@cqian2  could you help take a look this issue about blt copy.

**Comment by hye5** [comment]
What platform and is it a regression?

**Comment by XinfengZhang** [comment]
obviously, it is ACM

**Comment by MicroYY** [comment]
Hi @mengker33 Pls try https://github.com/intel/media-driver/pull/1569 to see if the issue still exists.

**Comment by mengker33** [comment]
> Hi @mengker33 Pls try #1569 to see if the issue still exists.

The issue is still there after this patch applied. Removing "image->format.fourcc != VA_FOURCC_NV12" may not help from my understanding, because p010 format always goto "if" path no matter "image->format.fourcc != VA_FOURCC_NV12" removed or not.

**Comment by MicroYY** [comment]
@mengker33 Refined the PR. Could you pls retry?

**Comment by mengker33** [comment]
> @mengker33 Refined the PR. Could you pls retry?

It is still quite slow.
