### ISSUE TITLE
[Feature]: Request for gstreamer plugin vapostproc to support BGRx color space format

### ISSUE THREAD

**Issue by bfbingfeng** [intel/media-driver#1539]
### What Feature?

In Edge system workload development, we need to use video/x-raw(memory:DMABuf), format=BGRx format in vapostproc, because in virtual machine only BGRx format is accepted. 

[va_all.zip](https://github.com/intel/media-driver/files/9930177/va_all.zip)
According to this vadumpcaps log, the iHD driver does not support BGRx for VPP.

can we add the feature of supporting BGRx format for memory:DMABuf on VPP?

### What's the usage scenario would be benifited?

Video Analytics, Video Conference

### What impacted?

Without this feature, the edge system IFPD program might not meet PTA requirement. Hence, it might affect the design win from the future customers.

**Comment by LhGu** [comment]
Hi, there are some format issues like ARGB/BGRA mismatch. I want to know what's **the hex order** of BGRx ( video/x-raw(memory:DMABuf), format=BGRx format ).  B-G-R-X or X-R-G-B of the raw image file @bfbingfeng.    In our driver we can only support B-G-R-X  hex order.

**Comment by LhGu** [comment]
Hi, @bfbingfeng  If your image **raw hex order is B-G-R-X**, I will add some codes in vpp caps to support VA_FOURCC_XRGB. Its ouput image raw hex order is also B-G-R-X.

**Comment by LhGu** [comment]
Need info. Close it now, and please feel free to re-open this issue if you want to discuss more.
