### ISSUE TITLE
Failed to do trancode of h265 main10 profile with FFmpeg on CFL

### ISSUE THREAD

**Issue by xhaihao** [intel/media-driver#159]
CFL is supported since commit 9b0caac9692f7e47e2cac01853390f147f9ebfa1, however I failed to do transcode for H265 10bits on CFL:

software stacks:
libva: d6fd111e2062bb4732db8a05ed55fc01771087b4
media_driver: 5c334b3e1fb7f5c0a7c2218fa912278c081f65e5
gmmlib: a5015343bc932e39747c57ea5dec0cbf28685465
ffmpeg: 0736f32a4facddbd953977ca614a3ee6d8a6e1d7

command line: ffmpeg -hwaccel vaapi -hwaccel_device /dev/dri/renderD128 -hwaccel_output_format vaapi -i h265-main10.h265 -c:v hevc_vaapi -profile:v main10 output.h265

Error message:
[hevc_vaapi @ 0x55cf5c430e50] Surface RT format 0x100 is not supported (mask 0x1).
Error initializing output stream 0:0 -- Error while opening encoder for output stream #0:0 - maybe incorrect parameters such as bit_rate, rate, width or height
Conversion failed!

Note: the message above is different from the error message in https://github.com/intel/media-driver/issues/158,

**Comment by XinfengZhang** [comment]
thanks for the issue reporting , will fix ASAP
