### ISSUE TITLE
Performance regression related to vaGetImage()

### ISSUE THREAD

**Issue by spiderkeys** [intel/media-driver#1590]
Previous discussion can be found starting here in another issue:
https://github.com/intel/media-driver/issues/925#issuecomment-1367669402

Summary:
On multiple different processor generations, including 7th, 9th, and 10th gen Intel processors, a large increase in CPU was observed when decoding H264 video using FFmpeg's VAAPI hardware decoding functionality via the FFmpeg library API (libavcodec/format/util).

The regression appears to have been introduced in commit: https://github.com/intel/media-driver/commit/497d9864aaba83214cbc2e6ae8cee4151934fe43

Before this commit, decoding via VAAPI on a few of my test platforms uses 10-20% CPU. After that commit, it takes 55-80% CPU (with no changes to the binary application that does the decoding, only swapping out the shared libraries for gmmlib and  the iHD video driver.

**Comment by intel-mediadev** [comment]
Auto Created VSMGWL-60539 for further analysis.
