### ISSUE TITLE
[Bug]: Debian 11 x86 HD600 - vaapih264enc unsupported VBR rate control

### ISSUE THREAD

**Issue by mseidler1** [intel/media-driver#1596]
### Which component impacted?

Encode

### Is it regression? Good in old configuration?

None

### What happened?

When running in Debian 11 with iHD driver (x86 with HD600 graphics):
gst-launch-1.0 --gst-debug-level=2 videotestsrc ! videoconvert ! vaapih264enc rate-control=vbr ! video/x-h264,profile=main ! h264parse ! rtph264pay config-interval=1 ! udpsink host=127.0.0.1 port=5555 sync=false async=false

Result:
0:00:00.052209243  4417 0x55d637942d80 ERROR           vaapicontext gstvaapicontext.c:355:config_create: unsupported VBR rate control
...

The same happens for other rate-control settings despite cqp.

This is working but missing the rate-
[vaapi rate-control.txt](https://github.com/intel/media-driver/files/10412006/vaapi.rate-control.txt)
control:
gst-launch-1.0 --gst-debug-level=2 videotestsrc ! videoconvert ! vaapih264enc ! video/x-h264,profile=main ! h264parse ! rtph264pay config-interval=1 ! udpsink host=127.0.0.1 port=5555 sync=false async=false

### What's the usage scenario when you are seeing the problem?

Transcode for media delivery, Content Creation

### What impacted?

VBR and CBR not working with vaapih264enc.

### Debug Information

libva2: 2.10.0-1
libva-dev: 2.10.0-1
intel-media-va-driver: 21.1.1+dfsg1-1

ls/dev/dri: card0 renderD128

vainfo
libva info: VA-API version 1.10.0
libva info: User environment variable requested driver 'iHD'
libva info: Trying to open /usr/lib/x86_64-linux-gnu/dri/iHD_drv_video.so
libva info: Found init function __vaDriverInit_1_10
libva info: va_openDriver() returns 0
vainfo: VA-API version: 1.10 (libva 2.10.0)
vainfo: Driver version: Intel iHD driver for Intel(R) Gen Graphics - 21.1.1 ()
vainfo: Supported profile and entrypoints
      VAProfileMPEG2Simple            : VAEntrypointVLD
      VAProfileMPEG2Main              : VAEntrypointVLD
      VAProfileH264Main               : VAEntrypointVLD
      VAProfileH264Main               : VAEntrypointEncSliceLP
      VAProfileH264High               : VAEntrypointVLD
      VAProfileH264High               : VAEntrypointEncSliceLP
      VAProfileJPEGBaseline           : VAEntrypointVLD
      VAProfileJPEGBaseline           : VAEntrypointEncPicture
      VAProfileH264ConstrainedBaseline: VAEntrypointVLD
      VAProfileH264ConstrainedBaseline: VAEntrypointEncSliceLP
      VAProfileVP8Version0_3          : VAEntrypointVLD
      VAProfileHEVCMain               : VAEntrypointVLD
      VAProfileHEVCMain10             : VAEntrypointVLD
      VAProfileVP9Profile0            : VAEntrypointVLD
      VAProfileVP9Profile2            : VAEntrypointVLD

### Do you want to contribute a patch to fix the issue?

No.

**Comment by nyanmisaka** [comment]
[intel-media-va-driver-non-free](https://packages.debian.org/bullseye/intel-media-va-driver-non-free) package is required for using VBR rate control without enabling [HuC firmware](https://github.com/intel/media-driver/tree/intel-media-22.6#known-issues-and-limitations).

**Comment by mseidler1** [comment]
Thank you!
