### ISSUE TITLE
[RFC] Is it have a plan to support QVBR mode in Linux

### ISSUE THREAD

**Issue by mypopydev** [intel/media-driver#161]
From https://software.intel.com/en-us/articles/common-bitrate-control-methods-in-intel-media-sdk, now 
windows driver has support QVBR mode, is it have a plan to support QVBR mode in Linux?

**Comment by XinfengZhang** [comment]
will add support

**Comment by XinfengZhang** [comment]
#168 and https://github.com/intel/libva/pull/212
currently , it's only support AVC
