### ISSUE TITLE
[Bug]: MADI/MCDI is still broken, proposed fix is ignored

### ISSUE THREAD

**Issue by smp79** [intel/media-driver#1618]
### Which component impacted?

Video Processing

### Is it regression? Good in old configuration?

No, this issue exist a long time

### What happened?

ADI is non-functional, newer platforms (TGL+) that are not supported by intel-vaapi-driver can not use high quality advanced deinterlacing. 
#1162 fixes the issue but that PR seem to be forgotten/ignored for almost 2 years. Please do something about this issue.

### What's the usage scenario when you are seeing the problem?

Playback

### Do you want to contribute a patch to fix the issue?

None

**Comment by LhGu** [comment]
Fix in this PR: https://github.com/intel/media-driver/pull/1162.

**Comment by intel-mediadev** [comment]
Auto Created VSMGWL-62032 for further analysis.

**Comment by LhGu** [comment]
Close this issue, pls chat in this PR: https://github.com/intel/media-driver/pull/1162
