### ISSUE TITLE
[Bug]: Video Composition performace drop

### ISSUE THREAD

**Issue by Lu-Anxiao** [intel/media-driver#1627]
### Which component impacted?

Video Processing

### Is it regression? Good in old configuration?

No, this issue exist a long time

### What happened?

HEVC 4K 16 channels video wall composition FPS drops to 15 while it could achieve 40 FPS for 15 channels.

### What's the usage scenario when you are seeing the problem?

Others

### What impacted?

Video composition

### Debug Information

sample_multi_transcode -par 16.par

-i::h265 Ghost_Towns_4K_8bit_420_30fps.h265 -join -hw -o::sink -vpp_comp_dst_x 0    -vpp_comp_dst_y 0    -vpp_comp_dst_w 960 -vpp_comp_dst_h 540 -n 900 -u 7
-i::h265 Ghost_Towns_4K_8bit_420_30fps.h265 -join -hw -o::sink -vpp_comp_dst_x 0    -vpp_comp_dst_y 540  -vpp_comp_dst_w 960 -vpp_comp_dst_h 540 -n 900 -u 7
-i::h265 Ghost_Towns_4K_8bit_420_30fps.h265 -join -hw -o::sink -vpp_comp_dst_x 0    -vpp_comp_dst_y 1080 -vpp_comp_dst_w 960 -vpp_comp_dst_h 540 -n 900 -u 7
-i::h265 Ghost_Towns_4K_8bit_420_30fps.h265 -join -hw -o::sink -vpp_comp_dst_x 0    -vpp_comp_dst_y 1620 -vpp_comp_dst_w 960 -vpp_comp_dst_h 540 -n 900 -u 7

-i::h265 Ghost_Towns_4K_8bit_420_30fps.h265 -join -hw -o::sink -vpp_comp_dst_x 960  -vpp_comp_dst_y 0    -vpp_comp_dst_w 960 -vpp_comp_dst_h 540 -n 900 -u 7
-i::h265 Ghost_Towns_4K_8bit_420_30fps.h265 -join -hw -o::sink -vpp_comp_dst_x 960  -vpp_comp_dst_y 540  -vpp_comp_dst_w 960 -vpp_comp_dst_h 540 -n 900 -u 7
-i::h265 Ghost_Towns_4K_8bit_420_30fps.h265 -join -hw -o::sink -vpp_comp_dst_x 960  -vpp_comp_dst_y 1080 -vpp_comp_dst_w 960 -vpp_comp_dst_h 540 -n 900 -u 7
-i::h265 Ghost_Towns_4K_8bit_420_30fps.h265 -join -hw -o::sink -vpp_comp_dst_x 960  -vpp_comp_dst_y 1620 -vpp_comp_dst_w 960 -vpp_comp_dst_h 540 -n 900 -u 7

-i::h265 Ghost_Towns_4K_8bit_420_30fps.h265 -join -hw -o::sink -vpp_comp_dst_x 1920 -vpp_comp_dst_y 0    -vpp_comp_dst_w 960 -vpp_comp_dst_h 540 -n 900 -u 7
-i::h265 Ghost_Towns_4K_8bit_420_30fps.h265 -join -hw -o::sink -vpp_comp_dst_x 1920 -vpp_comp_dst_y 540  -vpp_comp_dst_w 960 -vpp_comp_dst_h 540 -n 900 -u 7
-i::h265 Ghost_Towns_4K_8bit_420_30fps.h265 -join -hw -o::sink -vpp_comp_dst_x 1920 -vpp_comp_dst_y 1080 -vpp_comp_dst_w 960 -vpp_comp_dst_h 540 -n 900 -u 7
-i::h265 Ghost_Towns_4K_8bit_420_30fps.h265 -join -hw -o::sink -vpp_comp_dst_x 1920 -vpp_comp_dst_y 1620 -vpp_comp_dst_w 960 -vpp_comp_dst_h 540 -n 900 -u 7

-i::h265 Ghost_Towns_4K_8bit_420_30fps.h265 -join -hw -o::sink -vpp_comp_dst_x 2880 -vpp_comp_dst_y 0    -vpp_comp_dst_w 960 -vpp_comp_dst_h 540 -n 900 -u 7
-i::h265 Ghost_Towns_4K_8bit_420_30fps.h265 -join -hw -o::sink -vpp_comp_dst_x 2880 -vpp_comp_dst_y 540  -vpp_comp_dst_w 960 -vpp_comp_dst_h 540 -n 900 -u 7
-i::h265 Ghost_Towns_4K_8bit_420_30fps.h265 -join -hw -o::sink -vpp_comp_dst_x 2880 -vpp_comp_dst_y 1080 -vpp_comp_dst_w 960 -vpp_comp_dst_h 540 -n 900 -u 7
-i::h265 Ghost_Towns_4K_8bit_420_30fps.h265 -join -hw -o::sink -vpp_comp_dst_x 2880 -vpp_comp_dst_y 1620 -vpp_comp_dst_w 960 -vpp_comp_dst_h 540 -n 900 -u 7

-i::source -b 8000 -w 3840 -h 2160 -join -hw -n 900 -vpp_comp 16 -u 7 -o::h265 output.h265

### Do you want to contribute a patch to fix the issue?

Yes, I'm glad to submit a patch to fix it

**Comment by FurongZhang** [comment]
Thanks @Lu-Anxiao . I saw you filed some patch for this issue. Will review your patch and merge that once it is ready.

**Comment by FurongZhang** [comment]
https://github.com/intel-innersource/drivers.gpu.unified/pull/111159

**Comment by intel-mediadev** [comment]
Auto Created VSMGWL-63676 for further analysis.

**Comment by xiaoton1** [comment]
duplicated to https://jira.devtools.intel.com/browse/VSMGWL-62274
