### ISSUE TITLE
[Bug]:  output bitrate of sample_encode with extbrc:on  is not stable in vbr method.

### ISSUE THREAD

**Issue by HeXianrui** [intel/media-driver#1669]
### Is it regression? Good in old configuration?

No, this issue exist a long time

### What happened?

1:linux platform.
2:Output bitrate is not stable as the case with extbrc:off(native vbr)
3:The fluctuation range of the output bitrate is up or down 40% to the target bitrate.
4:Please help check this issue. 

5:Could you point me how to get frame complexity when encoding  with extbrc:off ?
 And Where can I find the source  code for how native brc works?

### What's the usage scenario when you are seeing the problem?

Others

### What impacted?

Bit rate control not stable.

### Debug Information

libva info: VA-API version 1.12.0
libva info: User environment variable requested driver 'iHD'
libva info: Trying to open /opt/intel/mediasdk/lib64/iHD_drv_video.so
libva info: Found init function __vaDriverInit_1_12
libva info: va_openDriver() returns 0

 intel media sdk version 1.35.

### Do you want to contribute a patch to fix the issue?

No.

**Comment by Sherry-Lin** [comment]
Could you share which platform you found this issue? Any tool to reproduce it? Which codec you are looking for, AVC/HEVC/VP9/AV1?

**Comment by bai-isaac** [comment]
Hi @HeXianrui ,
Since there has been no response for a long time, I will close this issue.
If you encounter any problems on the encoding, please feel free to report new issues. Thanks.
