### ISSUE TITLE
Very low frame rate due to extremely long execution time of vaMapBuffer in libva trace log file

### ISSUE THREAD

**Issue by BenFossil** [intel/media-driver#1697]
Hi all,

I use Yocto project to build libva (https://github.com/intel/libva repo, v2.18-branch branch) and intel-media-driver (https://github.com/intel/media-driver repo, intel-media-23.1 branch) for my core-image-weston image. When I play video via HTML5 player on chromium, there are some screen hangs while playing. I checked libva log file and see that  sometimes vaMapBuffer call takes up to several seconds to complete which is the reason for my screen hang issue.
Here is an example in libva trace log file:

......
[23429.118482][ctx       none]=========vaEndPicture ret = VA_STATUS_SUCCESS, success (no error) 
[**23434.222300**][ctx       none]=========vaMapBuffer ret = VA_STATUS_SUCCESS, success (no error) 
[23434.222318][ctx       none]=========vaUnmapBuffer ret = VA_STATUS_SUCCESS, success (no error) 
.......

That vaMapBuffer call takes about 5s to complete!!!
There are other vaMapBuffer calls that take. such very long time as in the attached file.
My hardware system is Intel J4215 with UHD Graphic 600 GPU

Please help how to troubleshoot why some vaMapBuffer calls take such extremely long time and causes very low frame rate

Thank you,
Ben

[libva.trace.log](https://github.com/intel/libva/files/11771712/libva.trace.log)

**Comment by Jexu** [comment]
What is you the codec and frame resolution of your content? Do you see any hang happen in dmesg log?

**Comment by Jexu** [comment]
Prefix log [2794.478772] indicates to the timestamp that current function is called instead of time cost.
Your log shows a big sw latency in chromium between vaEndPic and vaMapBuf, please report to chromium.
I will close this issue since there is no response for long time, and help re-open it again if having any other problem.
