### ISSUE TITLE
[Bug]: vaGetConfigAttributes returns wrong value of cu_qp_delta in VaConfigAttribValEncHevcFeatures with low-power mode

### ISSUE THREAD

**Issue by mengker33** [intel/media-driver#1698]
### Which component impacted?

Encode

### Is it regression? Good in old configuration?

None

### What happened?

In hevc encoding with low-power mode, vaGetConfigAtttibutes return an incorrect value (i.e. 2)of cu_qp_delta in VaConfigAttribValEncHevcFeatures, which causes artifacts in the encoded clip.
See the wrong one:
<img width="299" alt="image" src="https://github.com/intel/media-driver/assets/51201865/ae39d686-0f39-461b-a337-7417e8839585">

If returned value is 3 in low-power, the result is correct:
See the correct one:
<img width="299" alt="image" src="https://github.com/intel/media-driver/assets/51201865/1c69d7e9-88a8-48c0-83ad-1f868652a002">

### What's the usage scenario when you are seeing the problem?

Others

### What impacted?

It impacts the whole hevc encoding in low-power mode, simply means it can possibly impact every listed selection above.

### Do you want to contribute a patch to fix the issue?

None

**Comment by Sherry-Lin** [comment]
Is it common issue or specific to which platform?

**Comment by mengker33** [comment]
> Is it common issue or specific to which platform?

I think it is a common one as I can reproduce on tgl as well as on mtl.

**Comment by intel-mediadev** [comment]
Auto Created VSMGWL-66648 for further analysis.

**Comment by mengker33** [comment]
Hey, any updates?

**Comment by bai-isaac** [comment]
hi mengker33, which va version do you use? and could you please share how to reproduce this issue? Thanks!

**Comment by mengker33** [comment]
> hi mengker33, which va version do you use? and could you please share how to reproduce this issue? Thanks!

I use libva 2.19.0. 
The issue can be reproduced using gstreamer-va low-power hevc encoder, i.e. vah265lpenc
<pre>gst-launch-1.0 -vf videotestsrc num-buffers=30 ! video/x-raw,format=NV12 ! vah265lpenc ! h265parse ! filesink location=output.h265 </pre>
You can see the output.h265 has the artifacts as above one.

**Comment by OttoYang** [comment]
Hi @mengker33 
We return this param `cu_qp_delta` as an enable flag not as depth.  
The depth only supports 0 or 3 due to HW limitation.
So you may need to change the code in gstreamer as shown below:  
```c
pps->cu_qp_delta_enabled_flag = !!features.bits.cu_qp_delta;
pps->diff_cu_qp_delta_depth = sps->log2_diff_max_min_luma_coding_block_size == 3 ？sps->log2_diff_max_min_luma_coding_block_size: 0;
```

**Comment by mengker33** [comment]
Understood！ Appreciate your quick response :)

**Comment by OttoYang** [comment]
Hi @mengker33
May I know if the fix works for you?

**Comment by mengker33** [comment]
Yes, I will modify codes on GStreamer side
BTW, one more question, why need to set depth to maximum when this flag is enabled?

**Comment by OttoYang** [comment]
> Yes, I will modify codes on GStreamer side BTW, one more question, why need to set depth to maximum when this flag is enabled?

Hardware only supports 0 or 3(LCU-64) in low-power mode now. So other depths may lead unexpected behavior.

**Comment by mengker33** [comment]
Got it. Thank you, let me close the ticket.
