### ISSUE TITLE
[Bug]: 

### ISSUE THREAD

**Issue by chukfinley** [intel/media-driver#1707]
### Is it regression? Good in old configuration?

None

### What happened?

Hi,
OS Debian 12
i followed this guid https://superuser.com/questions/1428442/using-ffmpeg-to-encode-a-video-to-h264-using-intel-quicksync
at the media driver i get an python error when running

cmake ../media-driver

CMake Error at /usr/share/cmake-3.25/Modules/FindPkgConfig.cmake:73 (execute_process):
  execute_process attempted to output into a file: into a source directory.
Call Stack (most recent call first):
  media_driver/media_top_cmake.cmake:23 (find_package)
  media_driver/CMakeLists.txt:95 (include)

-- Configuring incomplete, errors occurred!
See also "/home/gpu/vaapi/media-driver/CMakeFiles/CMakeOutput.log".
gpu@debian-gpu:~/vaapi/media-driver$ cmake -v
CMake Error: Unknown argument -v
CMake Error: Run 'cmake --help' for all supported options.
gpu@debian-gpu:~/vaapi/media-driver$ cmake -V
CMake Error: Unknown argument -V
CMake Error: Run 'cmake --help' for all supported options.
gpu@debian-gpu:~/vaapi/media-driver$ cmake --version
cmake version 3.26.4

CMake suite maintained and supported by Kitware (kitware.com/cmake).

Python Verison 3.11.2
cmake version 3.26.4

### What's the usage scenario when you are seeing the problem?

Others

### Do you want to contribute a patch to fix the issue?

None

**Comment by Sherry-Lin** [comment]
Does this issue still exist? There is a suggested solution in https://superuser.com/questions/1428442/using-ffmpeg-to-encode-a-video-to-h264-using-intel-quicksync. I'm going to close this issue. Please feel free to re-open it if any concerns.
