### ISSUE TITLE
Errors when building media-driver on 32-bit Ubuntu 16.04LTS

### ISSUE THREAD

**Issue by Srivat97** [intel/media-driver#174]
I am currently trying to build the media-driver on a 32-bit Ubuntu machine. While building I changed the architecture type to 32 and i started getting build errors within the source code. They are listed below:

In file included from /home/user/media-driver/media_driver/linux/common/os/libdrm/include/xf86drm.h:41:0,
                 from /home/user/media-driver/media_driver/linux/common/ddi/media_libva_common.h:33,
                 from /home/user/media-driver/media_driver/linux/common/cm/media_libva_cm.h:30,
                 from /home/user/media-driver/media_driver/linux/common/cm/cm_def_os.h:41,
                 from /home/user/media-driver/media_driver/agnostic/common/cm/cm_def.h:30,
                 from /home/user/media-driver/media_driver/agnostic/common/cm/cm_array.h:30,
                 from /home/user/media-driver/media_driver/agnostic/common/cm/cm_array.cpp:27:
/home/user/media-driver/media_driver/linux/common/os/libdrm/include/libdrm_macros.h: In function ‘int drm_munmap(void*, size_t)’:
/home/user/media-driver/media_driver/linux/common/os/libdrm/include/libdrm_macros.h:40:40: error: size of array is negative
       (void) sizeof(char [1 - 2*!(COND)]); \
                                        ^
/home/user/media-driver/media_driver/linux/common/os/libdrm/include/libdrm_macros.h:76:4: note: in expansion of macro ‘STATIC_ASSERT’
    STATIC_ASSERT(LARGE_OFF_T % 2147483629 == 721 &&
    ^
media_driver/CMakeFiles/iHD_drv_video.dir/build.make:62: recipe for target 'media_driver/CMakeFiles/iHD_drv_video.dir/agnostic/common/cm/cm_array.cpp.o' failed
make[2]: *** [media_driver/CMakeFiles/iHD_drv_video.dir/agnostic/common/cm/cm_array.cpp.o] Error 1
CMakeFiles/Makefile2:163: recipe for target 'media_driver/CMakeFiles/iHD_drv_video.dir/all' failed
make[1]: *** [media_driver/CMakeFiles/iHD_drv_video.dir/all] Error 2
Makefile:149: recipe for target 'all' failed
make: *** [all] Error 2

If I try to build it with the default parameters, I receive incompatible errors when iHD_drv_video tries linking.

**Comment by Srivat97** [comment]
Additionally, the following command was used to configure the media-driver before running the make command:
`$ cmake ../media-driver \
-DCMAKE_INSTALL_PREFIX=/usr \
-DMEDIA_VERSION="2.0.0" \
-DBUILD_ALONG_WITH_CMRTLIB=1 \
-DBS_DIR_GMMLIB=`pwd`/../gmmlib/Source/GmmLib/ \
-DBS_DIR_COMMON=`pwd`/../gmmlib/Source/Common/ \
-DBS_DIR_INC=`pwd`/../gmmlib/Source/inc/ \
-DBS_DIR_MEDIA=`pwd`/../media-driver
-DARCH=32`

**Comment by oliver-sang** [comment]
@Srivat97 
Hello, basically our driver is targeting 64-bit system, such like where you saw the build error.
We encourage you to supply patch to support 32-bit. What's your idea? Thanks

**Comment by oliver-sang** [comment]
@Srivat97 since we won't address this 32-bit problem, instead, we welcome you to file PR :), I will close this issue. Thanks
