### ISSUE TITLE
Can we use the media-driver to decode hevc video up to 8192x8192 ?

### ISSUE THREAD

**Issue by jinlongzhou** [intel/media-driver#176]
I used to  take vaapi-intel-driver[https://github.com/intel/intel-vaapi-driver](url) as the backend of the libva , but i found that it can not decode hevc videos whoes size over 4k.  i dont think this is the problem of the libva, but it is the problem of vaapi-intel-driver.  So here is the question, if i replace the "vaapi-intel-driver" with "media-driver" as the backend of libva, can we decode hevc video up to 8k?

**Comment by XinfengZhang** [comment]
which platform? HW support 8K decode from BDW+, but we just export 4K resolution caps.

**Comment by XinfengZhang** [comment]
it's a small change, you can ignore the resolution report from vaQueryConfigAttributes and vaQuerySurfaceAttributes , call decode directly. if you need it, I can file a PR for you to export 8K capabilities.

**Comment by jinlongzhou** [comment]
thank you , i really need it

**Comment by XinfengZhang** [comment]
https://github.com/XinfengZhang/media-driver/tree/hevc_8k
you can refer the head  commit of this branch.  thanks

**Comment by XinfengZhang** [comment]
@jinlongzhou  could you close this issue?
