### ISSUE TITLE
[Bug]: build error in Ubuntu 24.04

### ISSUE THREAD

**Issue by xhaihao** [intel/media-driver#1791]
### Which component impacted?

Build

### Is it regression? Good in old configuration?

None

### What happened?

Follow https://github.com/intel/media-driver?tab=readme-ov-file#building to build media driver in  Ubuntu 24.04 and I got the error below:

> /home/aaa/media-driver/media_driver/media_softlet/agnostic/Xe_M/Xe_M_base/codec/hal/dec/avc/packet/decode_avc_picture_xe_m_base_packet.cpp: In member function ‘MOS_STATUS decode::AvcDecodePicPktXe_M_Base::DumpResources(MHW_VDBOX_AVC_DIRECTMODE_PARAMS&, uint32_t)’:
>
> /home/aaa/media-driver/media_driver/media_softlet/agnostic/Xe_M/Xe_M_base/codec/hal/dec/avc/packet/decode_avc_picture_xe_m_base_packet.cpp:592:65: error: comparing the result of pointer addition ‘(avcDirectmodeParams._MHW_VDBOX_AVC_DIRECTMODE_PARAMS::presAvcDmvBuffers + ((((sizetype)n) + 1) * 328))’ and NULL [-Werror=address]
> 592 |                 if (&avcDirectmodeParams.presAvcDmvBuffers[n+1] != nullptr)
>      |                     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^~~~~~~~~~

### What's the usage scenario when you are seeing the problem?

Others

### Do you want to contribute a patch to fix the issue?

None

**Comment by Jexu** [comment]
@xhaihao Could you help verify the fix

**Comment by intel-mediadev** [comment]
Auto Created VSMGWL-73053 for further analysis.
