### ISSUE TITLE
[Bug]: media-driver 24.2.2 fails to compile with gcc-14.1

### ISSUE THREAD

**Issue by heitbaum** [intel/media-driver#1797]
### Which component impacted?

Build

### Is it regression? Good in old configuration?

No, this issue exist a long time

### What happened?

When compiling with gcc-14.1 (rc) media-driver 24.2.2 fails to compile with the following errors.

`error: template-id not allowed for constructor in C++20 [-Werror=template-id-cdtor] `

### What's the usage scenario when you are seeing the problem?

Others

### What impacted?

Unable to compile with gcc-14.1

### Debug Information

Na

### Do you want to contribute a patch to fix the issue?

No.

**Comment by rubin55** [comment]
FWIW, I just tried to compile 24.2.4 using `gcc` 14.1.1, this fails with a lot of errors, here's the output log for those interested: 
[output.log](https://github.com/user-attachments/files/15510335/output.log)

**Comment by MicroYY** [comment]
Fix by: https://github.com/intel/media-driver/pull/1808

**Comment by intel-mediadev** [comment]
Auto Created VSMGWL-73974 for further analysis.
