### ISSUE TITLE
what is the usage of the two files "/data/igfx_user_feature.txt" and "/etc/igfx_user_feature.txt"?

### ISSUE THREAD

**Issue by jinlongzhou** [intel/media-driver#185]
the program aborts at _UserFeature_DumpFile interface when it try to open "/etc/igfx_user_feature.txt". does this file need to be created and edited manually before the program execute?  if so, what is format in the  file?  is there a manual for the usage?

**Comment by XinfengZhang** [comment]
actually, there should only have /etc/igfx_user_feature.txt, it is a registry file, now. feature switch is from VAAPI.  so no need to use the file, if you want, you can follow this format
[KEY]
    0x00000001
    UFKEY_INTERNAL\LibVa
        [VALUE]

**Comment by XinfengZhang** [comment]
@jinlongzhou could we close it?
