### ISSUE TITLE
[Bug]: ffmpeg-vaapi decode 10bit vp9 have lots case fail on LNL by md5 mismatch

### ISSUE THREAD

**Issue by Hangjie22Coder** [intel/media-driver#1857]
### Which component impacted?

Decode

### Is it regression? Good in old configuration?

None

### What happened?

VERSION=Ubuntu 22.04.3 LTS
kernel:6.10.0-rc3+

        ["libva"]="01153523f25ac703e7ce2afc0023788a90f6c1bb (2024-07-17 13:51:11 -0400)"
        ["gmmlib"]="567dc09fd3859de3d9c09456ee7b366c0d327eb6 (2024-09-06 15:21:19 +0530)"
        ["libva-utils"]="908e2014546bf133cdc8a72cc0d3f2518d04cffc (2024-07-16 13:30:52 +0800)"
        ["media-driver"]="a584e987e16cf624b664155685412a9d6937e26f (2024-09-27 16:44:37 +0800)"
        ["vpl_runtime"]="fbd9d4e471d7d8d21b7f4a5d5fc5789c93160ddb (2024-09-25 16:47:22 +0800)"
        ["vpl_dispatcher"]="5f6bd8a1e753c8f63a3fd8b36894d6968b808a6d (2024-08-22 15:59:59 +0800)"
        ["cartwheel-ffmpeg"]="aa4c028ebeee5923d352040c07c28f6695a3f44c (2024-09-28 10:01:01 +0000)"

### What's the usage scenario when you are seeing the problem?

Others

### Debug Information

cmd line:
ffmpeg -v verbose  -hwaccel vaapi -init_hw_device vaapi=hw:/dev/dri/renderD128 -hwaccel_output_format p010le -hwaccel_flags allow_profile_mismatch  -i input.ivf -lavfi 'null' -c:v rawvideo -pix_fmt p010le -fps_mode passthrough -noautoscale -vframes 332 -y -f tee '[f=md5]pipe:1' 

result:
md5:expect = 2119eee12b1fe12ec5520742bdfaa3ca
md5:actual = f59fba6fd0cfa3a133f1a9714e28a357

This bug also exists in MTL/ADL/TGL/ICL/CFL/DG2. 
This should be a huge bug, which affects many cases in daily full test.

### Do you want to contribute a patch to fix the issue?

None

**Comment by Jexu** [comment]
It is regression or not? Could you help get the first bad commit id?

**Comment by Hangjie22Coder** [comment]
Thank you for your comment. This bug has been resolved internally on our side, so there is no need to investigate further. We won't be pursuing the first bad commit as the issue no longer persists.
