### ISSUE TITLE
Driver installation should use libva.pc driverdir variable

### ISSUE THREAD

**Issue by uartie** [intel/media-driver#2]
LibVA provides a pkgconfig (libva.pc) file that defines a `driverdir` variable.  This variable specifies the default path that libva will search for drivers.   This variable can be obtained with `pkg-config libva --variable driverdir`.  The cmake configuration should use this `driverdir` as the default installation location for the driver (but still allow it to be overridden by developer... e.g. -DLIBVA_DRIVERS_PATH=<path>).  Obviously, users can still override libva driver search path with environment var at runtime.

**Comment by oliver-sang** [comment]
thanks for reporting this issue and thanks for the PR. I ran into some problem while trying your PR which I added comments in PR. Could you help? Thanks
