### ISSUE TITLE
Driver doesn't report VPP maxWidth/maxHeight via vaQueryVideoProcPipelineCaps

### ISSUE THREAD

**Issue by dmitryermilov** [intel/media-driver#201]
Driver doesn't report VPP maxWidth/maxHeight via vaQueryVideoProcPipelineCaps for EUs (e.g. scaling) and VEBOX usage cases. See code below:
https://github.com/intel/media-driver/blob/master/media_driver/linux/common/ddi/media_libva.cpp#L5343-L5363

The driver fills width/height/pixel_format caps **only** for SFC cases.

**Comment by XinfengZhang** [comment]
thanks for reporting, we will add the missing part

**Comment by dmitryermilov** [comment]
Hi @XinfengZhang . Is there any progress ?

**Comment by FurongZhang** [comment]
@dmitryermilov We have discussed this issue. And it should be in open source very soon. I will check the code if it is there now. Thanks for your feedback.

**Comment by dvrogozh** [comment]
Folks, please, stop pushing changes to repository without review! This should be a PR first, which we need to take a look, try and comment. For example, in the above commit I left 2 comments:
1. Shouldn't that be a per-platform specific?
2. Shouldn't that be a SFC/AVS specific?
