### ISSUE TITLE
[ffmpeg-vaapi][vp9 encode] vp9 encode failed when using ffmpeg-vaapi

### ISSUE THREAD

**Issue by FocusLuo** [intel/media-driver#205]
the cmd line can work on i965 driver, but failed on iHD driver on (CFL/KBL/GLK/)
ffmpeg -hwaccel vaapi -vaapi_device /dev/dri/renderD128 -y -s:v 1920x1080 -i ./1080p_blue_sky.yuv -vf format=nv12,hwupload -c:v vp9_vaapi -loop_filter_level 16 -loop_filter_sharpness 15 -g 30 -global_quality 20 1080p_1920x1080_i420_looplevel16_loopsharpness15_bf1_gop30_gquality20_fps30.ivf
[rawvideo @ 0x55c5160de800] Estimating duration from bitrate, this may be inaccurate
Input #0, rawvideo, from '/root/media_streams//encoderbitstreams//1080p_blue_sky.yuv':
  Duration: 00:00:08.68, start: 0.000000, bitrate: 622080 kb/s
    Stream #0:0: Video: rawvideo (I420 / 0x30323449), yuv420p, 1920x1080, 622080 kb/s, 25 tbr, 25 tbn, 25 tbc
Stream mapping:
  Stream #0:0 -> #0:0 (rawvideo (native) -> vp9 (vp9_vaapi))
Press [q] to stop, [?] for help
[vp9_vaapi @ 0x55c5160e3440] Encoding entrypoint not found (19 / 6).
Error initializing output stream 0:0 -- Error while opening encoder for output stream #0:0 - maybe incorrect parameters such as bit_rate, rate, width or height
Conversion failed!

**Comment by XinfengZhang** [comment]
please also attach the platform information
