### ISSUE TITLE
[ffmpeg-vaapi][HEVC encode] 1:N encode failed by using ffmpeg-vaapi

### ISSUE THREAD

**Issue by FocusLuo** [intel/media-driver#206]
The HEVC 1:N encode can work well on i965, but failed on iHD
platforms: CFL, GLK and KBL
ffmpeg -hwaccel vaapi -vaapi_device /dev/dri/renderD128 -v verbose -f rawvideo -s:v 720x480 -i ./Test_720x480p.yuv -an -vf format=nv12,hwupload -c:v hevc_vaapi -vframes 200 -y ./H265e_1N_720x480_session8_1.h265 -vf format=nv12,hwupload -c:v hevc_vaapi -vframes 200 -y ./H265e_1N_720x480_session8_2.h265 -vf format=nv12,hwupload -c:v hevc_vaapi -vframes 200 -y ./H265e_1N_720x480_session8_3.h265 -vf format=nv12,hwupload -c:v hevc_vaapi -vframes 200 -y ./H265e_1N_720x480_session8_4.h265 -vf format=nv12,hwupload -c:v hevc_vaapi -vframes 200 -y ./H265e_1N_720x480_session8_5.h265 -vf format=nv12,hwupload -c:v hevc_vaapi -vframes 200 -y ./H265e_1N_720x480_session8_6.h265 -vf format=nv12,hwupload -c:v hevc_vaapi -vframes 200 -y ./H265e_1N_720x480_session8_7.h265 -vf format=nv12,hwupload -c:v hevc_vaapi -vframes 200 -y ./H265e_1N_720x480_session8_8.h265

part of log as below:
[graph 7 input from stream 0:0 @ 0x5614f625ccc0] w:720 h:480 pixfmt:yuv420p tb:1/25 fr:25/1 sar:0/1 sws_param:flags=2
[auto_scaler_0 @ 0x5614f625e780] w:iw h:ih flags:'bicubic' interl:0
[Parsed_format_0 @ 0x5614f625bb40] auto-inserting filter 'auto_scaler_0' between the filter 'graph 7 input from stream 0:0' and the filter 'Parsed_format_0'
[auto_scaler_0 @ 0x5614f625e780] w:720 h:480 fmt:yuv420p sar:0/1 -> w:720 h:480 fmt:nv12 sar:0/1 flags:0x4
[hevc_vaapi @ 0x5614ef936840] Input 720x480 -> Surface 720x480 -> CTU 23x15.
Output #7, hevc, to './H265e_1N_720x480_session8_8.h265':
  Metadata:
    encoder         : Lavf58.17.100
    Stream #7:0: Video: hevc (hevc_vaapi) (Main), 1 reference frame, vaapi_vld, 720x480, q=2-31, 25 fps, 25 tbn, 25 tbc
    Metadata:
      encoder         : Lavc58.20.101 hevc_vaapi
[hevc_vaapi @ 0x5614ef921200] Failed to end picture encode issue: 24 (internal encoding error).
[hevc_vaapi @ 0x5614ef921200] Encode failed: -5.
Video encoding failed

**Comment by XinfengZhang** [comment]
seems ffmpeg call vaDestroyContext before vaDestroyBuffer (VAEncCodedBufferType)

**Comment by XinfengZhang** [comment]
cant reproduce with latest ffmpeg (4ac88ba5487e026bf81da565f97cfcf8f920657d)

**Comment by mypopydev** [comment]
I can't reproduce with FFmpeg master/media-driver master/libva master in SKL.

**Comment by wangzj0601** [comment]
this issue can be duplicated on CFL/KBL/GLK, while can not be duplicated on SKL with below env.
media-driver: b06a5736095c2b9c735ea42a64de9c7f3a9191bb
ffmpeg: 27662ed681cbc74e9492cecf86ead8946679fd23 repo:https://git.ffmpeg.org/ffmpeg.git

**Comment by XinfengZhang** [comment]
@wangzj0601 suppose , it is because lack of P frame support on CFL/KBL/GLK

**Comment by zhuqingliang** [comment]
passed at latest codebase ffmpeg(n4.1)
