### ISSUE TITLE
VC1DEC:  b_picture_fraction not follow VA-API 2.0 define

### ISSUE THREAD

**Issue by mypopydev** [intel/media-driver#21]
The field b_picture_fraction in va.h means index for PICTURE_LAYER::BFRACTION value in Table 40 (7.1.1.14), but media-driver not follow the define

**Comment by thomasli21801** [comment]
The parse function is following VC1 bspec. In order to follow definition in va.h, app must make sure the calculation to map code word to index of FractionToScaleFactor table. Could you please help to double check with app behavior?

**Comment by mypopydev** [comment]
@thomasli21801 in va.h, b_picture_fraction means index for PICTURE_LAYER::BFRACTION value in Table 40 (7.1.1.14), please double check the define. Tks

**Comment by thomasli21801** [comment]
We may need to modify internal test app for VC1 decode to change from code word to index.
