### ISSUE TITLE
[ffmpeg-vaapi][h264 encode] avc cbr encode output bitrate out of control on GLK platform 

### ISSUE THREAD

**Issue by FocusLuo** [intel/media-driver#210]
avc cbr encode output bitrate out of control on GLK platform, but it can work on CFL/KBL/SKL/APL paltform
ffmpeg -hwaccel vaapi -vaapi_device /dev/dri/renderD128 -v verbose -f rawvideo -s:v 720x480 -i ./720x480p.yuv -vf format=nv12,hwupload -c:v h264_vaapi -g 12 -bf 0 -b:v 1M -maxrate:v 1M -quality 4 -vframes 200 -y ./h264e_cbr_720x480_gop12_refdist0_bitrate1M.h264
bitrate_real=77.39
bitrate_input=1024
bitrate_gap = 92.00

**Comment by XinfengZhang** [comment]
GLK issue, low priority.

**Comment by XinfengZhang** [comment]
it should already been fixed by latest driver. latest driver add the support of GLK
