### ISSUE TITLE
[ffmpeg-vaapi][h264 encode] avc vbr encode output bitrate out of control on GLK platform

### ISSUE THREAD

**Issue by FocusLuo** [intel/media-driver#211]
the cmd line can work well on CFL/KBL/SKL, but failed on GLK for bitrate out of control:
ffmpeg -hwaccel vaapi -vaapi_device /dev/dri/renderD128 -v verbose -f rawvideo -s:v 1920x1080 -i ./1080p_blue_sky.yuv -vf format=nv12,hwupload -c:v h264_vaapi -g 30 -bf 3 -b:v 2M -quality 4 -vframes 100 -y ./h264e_vbr_1920x1080_gop30_refdist3_bitrate2M.h264

log info:
No more output streams to write to, finishing.e=00:00:03.56 bitrate= 589.1kbits/s speed=3.55x
frame=  100 fps= 90 q=-0.0 Lsize=     601kB time=00:00:03.96 bitrate=1243.1kbits/s speed=3.55x
video:601kB audio:0kB subtitle:0kB other streams:0kB global headers:0kB muxing overhead: 0.000000%

**Comment by XinfengZhang** [comment]
it should already been fixed by latest driver. latest driver add the support of GLK
