### ISSUE TITLE
[ffmpeg-vaapi][avc encode] multi-process encode failed on GLK platform by using ffmpeg-vaapi

### ISSUE THREAD

**Issue by FocusLuo** [intel/media-driver#212]
To start 8 process for a same avc encode comline, and then to check the md5 for each output file, the iHD driver have different md5 on GLK, but it can work well on CFL/KBL/SKL/APL
for ((i=0;i<8;i++));do
{
ffmpeg -hwaccel vaapi -vaapi_device /dev/dri/renderD128 -v verbose -f rawvideo -s:v 720x480 -i ./Test_720x480p.yuv -vf format=nv12,hwupload -c:v h264_vaapi -g 10 -bf 1 -refs 2 -vframes 100 -y ./H264e_multi_process_720x480P_"$i".h264
} &
done
wait $!

**Comment by XinfengZhang** [comment]
it should already been fixed by latest driver. latest driver add the support of GLK
