### ISSUE TITLE
Fix installing permissions for iHD_drv_video.so

### ISSUE THREAD

**Issue by chivakker** [intel/media-driver#215]
With the current build system iHD_drv_video.so is installed with permissions 644, it should be at least 754. Please fix.

**Comment by oliver-sang** [comment]
what's the real intention to request this?
If check /usr/lib/x86_64-linux-gnu in ubuntu, most real lib has the mode 644.
If check /usr/lib64 in fedora, yes, most of them has the mode 755.
But what's the difference? Any impact to any user case?
iHD is loaded by libva by designated path/name, I think the read access is enough. Any reason you request to have execute access to it?

**Comment by chivakker** [comment]
I don't know what distributions do in terms of modifying permissions, but this is a driver that should have execute permission upon installing.  I don't think distributions are packaging it yet but I'd assume they don't mess up with that.  Other driver install with the right permissions.

**Comment by chivakker** [comment]
@XinfengZhang please fix this,  a recent update in gmmlib ABI wasn't caught because this wasn't fixed.
