### ISSUE TITLE
[SKL][JPECENC]jpec encoder failure on 640 480 nv12.yuv 

### ISSUE THREAD

**Issue by ycui6** [intel/media-driver#220]
The JPEGENC issue has been reproduced on location with command below:
msdk@ico-pae-msdk:~/VPG_HikV/work/libva-utils/encode$ ./jpegenc 640 480 Jpeg-Enc/nv12.yuv output0.jpg 0 50

P.S failure when “VAEncPackedHeaderParameterBufferType”
Please help check, thanks

**Comment by XinfengZhang** [comment]
jpeg encode does not support packed header, application just send parameter is enough, driver will pack the headers

**Comment by mypopydev** [comment]
@ycui6 can you try the patch https://github.com/intel/media-driver/pull/192 for this issue

**Comment by XinfengZhang** [comment]
sync with @ycui6 , he changed the jpegenc to handle the packed header. close the issue
