### ISSUE TITLE
[BDW/SKL] No VP8 ENC support in the media-driver.

### ISSUE THREAD

**Issue by mypopydev** [intel/media-driver#24]
In BDW/SKL HW Spec, it's can support VP8 ENC, but media-driver doesn't support it.

BTW: I think i965 (https://github.com/01org/intel-vaapi-driver) can support VP8 ENC in BDW/SKL.

**Comment by liangali** [comment]
The engineering focus for media-driver is on CNL and beyond. We did not want to duplicate the effort and capabilities provided by intel-vaapi-driver for products prior to CNL (BDW/SKL).

**Comment by mypopydev** [comment]
So CNL will support VP8/VP9 DEC/ENC ? @liangali

**Comment by liangali** [comment]
Yes, VP8/VP9 DEC had been enabled, the ENC will be added in future.
