### ISSUE TITLE
Remove implicit macros for gmmlib includes

### ISSUE THREAD

**Issue by chivakker** [intel/media-driver#246]
Per Readme file, these are to be defined:

-DBS_DIR_GMMLIB=`pwd`/../gmmlib/Source/GmmLib/ \
-DBS_DIR_COMMON=`pwd`/../gmmlib/Source/Common/ \
-DBS_DIR_INC=`pwd`/../gmmlib/Source/inc/ \

can these be removed in favor of a shared object approach where pc file is consulted to do the appropriate definitions?

Assuming, gmmlib is already compiled as a .so file with its pc file.  media-driver should just unse pkg-config to link against it, use pc file information and avoid recompiling gmmlib.  

This should fix also the problem stated on #35 without the submodule

**Comment by oliver-sang** [comment]
thanks for your suggestion. team is working for this.
