### ISSUE TITLE
pkgconfig for igdgmm is lacking Libs options

### ISSUE THREAD

**Issue by chivakker** [intel/media-driver#248]
Please include Libs information for proper linking from outside this library.

**Comment by oliver-sang** [comment]
we will change to use dynamic gmmlib and regard gmmlib as an external dep. So we won't pursue to supply igdgmm pkgconfig information from media side.
Will close this issue when we finish the transition. Thanks

**Comment by dvrogozh** [comment]
This is not media-driver issue! This is gmmlib issue and should be filed appropriately!

See: intel/gmmlib#26 (igdgmm.pc file should be corrected)

**Comment by drprajap** [comment]
This issue has been addressed by gmmlib commit - [d3e1b05](https://github.com/intel/gmmlib/commit/d3e1b053f6639efc25959b0485a0f3def2833354).

Thanks.

**Comment by yangnin** [comment]
This issue has been addressed by gmmlib commit - d3e1b05.
