### ISSUE TITLE
libva-utils ENC test samples avcenc can't work.

### ISSUE THREAD

**Issue by mypopydev** [intel/media-driver#25]
https://github.com/01org/libva-utils/blob/master/encode/avcenc.c can't work in media-driver, the root case is setting 0/0 in    /* Create a context for this decode pipe */
    va_status = vaCreateContext(va_dpy, avcenc_context.config_id,
                                picture_width, picture_height,
                                VA_PROGRESSIVE, 
                                0, 0,
                                &avcenc_context.context_id);

**Comment by XinfengZhang** [comment]
driver store the surfaceID array to be reference or reconstruct. all recon/reference should be in the stored surfaceID array. can change it to dynamic register the surface, but is it very important?  I can evaluate the priority

**Comment by mypopydev** [comment]
@XinfengZhang I observe FEI didn't follow this restrict, any  specialized reason?

**Comment by XinfengZhang** [comment]
I implemented it by requirement from real usagecases,only decode and FEI.  we will add the support for legacy encode.

**Comment by XinfengZhang** [comment]
fixed by  the commit 039e892
