### ISSUE TITLE
Incorrect EU count is used on some SKU with one EU disabled.

### ISSUE THREAD

**Issue by yakuizhao** [intel/media-driver#26]
The driver will try to query the EU_count/sub_slicecount by using drm_ioctl. But as no slice_count is queried, it uses the below code to update the eu_count/sub_slicecount based on device_id.
    >sysInfo->SliceCount    = devInfo->SliceCount;
        sysInfo->SubSliceCount = devInfo->SubSliceCount;
        sysInfo->EUCount       = devInfo->EUCount;

See table and notes in https://01.org/sites/default/files/documentation/intel-gfx-prm-osrc-skl-vol04-configurations.pdf - "[a] Particular SKUs produced by Intel may have one EU disabled."
So the EUCount in driver is incorrect on the particular SKU.

**Comment by dahuaxie** [comment]
Yes the logic seems correct to me. With the patch EU/Slice/SubSlice is individually initialized and not affect each other
