### ISSUE TITLE
usage/video_analytics_Intel_GPU submodule src is missing after 2e521ee

### ISSUE THREAD

**Issue by asavah** [intel/media-driver#269]
I thought intel people should at least know how to handle git.
```
~/media-driver# git submodule status
fatal: no submodule mapping found in .gitmodules for path 'usage/video_analytics_Intel_GPU'
```

**Comment by Sherry-Lin** [comment]
usage/video_analytics_Intel_GPU folder was created for reference code. We are syncing up with legal team for the process. 
There is an reference design in https://github.com/yunbiaolin/video_analytics_Intel_GPU.
Sorry for misleading title.
