### ISSUE TITLE
The vpp will ignore alpha value in output_background_color and always clear background to black.

### ISSUE THREAD

**Issue by xuguangxin** [intel/media-driver#272]
According to libva definition, the output_background_color  is an ARGB value. If we set alpha to 0.  It will use the original background value. This feature is very useful if we want to draw mutli video on different areas. But the current driver will ignore the alpha and always clear the background to black. 

How to reproduce:
1. follow https://github.com/intel/libyami/wiki/Build to build libyami and the media-driver
2. configure libyami-utils using --enable-dmabuf
3. kill x server
4. run libyami-utils/exmpale/grid xxx.264 -r 4 -c 5

You will see only right conner has a video playback. other areas are black

Expected behaviors:
We can see 4x5(20) videos playback on screen

**Comment by FurongZhang** [comment]
Thanks for the details of issue. Will try to reproduce the issue first.

**Comment by xuguangxin** [comment]
hi @FurongZhang , any update on this? thanks

**Comment by Jister** [comment]
Hi, Guangxin, I have create a pull request to fix the issue, please refer to #296
