### ISSUE TITLE
Additional Image formats

### ISSUE THREAD

**Issue by krogueintel** [intel/media-driver#287]
The older intel-vaapi-driver supported the the following formats for creating a VAImage : IA44, AI44, IA88, AI88, ARGB, ABGR,, 422H, and UYVY which the intel media-driver does not. For better transitioning, would it be possible to support these formats as well?

**Comment by XinfengZhang** [comment]
yes,we add more Image support , base on the format driver support (VPP&CODEC)

**Comment by FurongZhang** [comment]
@Jister , Have we merged the fix? Is it possible for you to update the status? If merged, how about closing this issue? Thanks a lot!

**Comment by Jister** [comment]
IA44, AI44, IA88 will not be supported, unless there is specific/strong requirement. Other formats have be added.

**Comment by FurongZhang** [comment]
@krogueintel  Have you had a chance to check if this issue is fixed or not? Thanks a lot in advance! Currently, we don't have a plan to support IA44, AI44, IA88 until there is a strong request since they are legacy formats. 
BTW, do you know if there is some main usage for IA44, AI44, IA88 formats?

**Comment by krogueintel** [comment]
I changed groups; any work on the media driver is completely out of scope (and indeed almost unrelated) for my group's responsibilities.

**Comment by FurongZhang** [comment]
Thanks @krogueintel for the information.
