### ISSUE TITLE
[FFmpeg-Vaapi][HEVC_ffmpeg_decode]the dumped file has garbage on CFL on iHD driver

### ISSUE THREAD

**Issue by zhuqingliang** [intel/media-driver#295]
The test case passed on i965 driver, but failed on iHD driver , and the dumped file has garbage

1.ffmpeg -hwaccel vaapi -hwaccel_device /dev/dri/renderD128 -v verbose -y -i /media//ffmpeg_hevc/AMP_A_Samsung_6.bit -pix_fmt yuv420p -y ./AMP_A_Samsung_6.bit.yuv
2. real_md5=a24c19048a55394de8c1b454f450888d ref_md5=86afaedd98cbc5f11da775121bf12dd5
3. use tool 7yuv to observe the dumped file

**Comment by XinfengZhang** [comment]
@zhuqingliang where can get the stream? is it a public stream?

**Comment by XinfengZhang** [comment]
cant reproduce this issue with latest media driver. commit 60b1e83aef1b751fb2b455b67766dc579cd73c80
