### ISSUE TITLE
[SKL]FFmpe VA-API dump YUV fail.

### ISSUE THREAD

**Issue by mypopydev** [intel/media-driver#302]
use the cmd:

./ffmpeg -hwaccel vaapi -vaapi_device /dev/dri/render128 -i xxx.mp4 -f null /dev/null

to dump YUV to CPU, get some fail infos.

**Comment by mypopydev** [comment]
After debug the code, I think https://github.com/intel/media-driver/commit/a9a07fc919388a2be91f73fa19482be0159ab621 lead to this issue.

**Comment by XinfengZhang** [comment]
backout it, 4683ab40fcaf9a98d28b06b310a37035b0b0ebd3 should work
