### ISSUE TITLE
Сontinuous VmRSS growth when recreate VPP context

### ISSUE THREAD

**Issue by dmitryermilov** [intel/media-driver#309]
Frequent VPP vaCreateContext/vaDestroyContext calls cause VmRSS memory growth. Please use the reproducer in attachment.
Please note that the issue is seen only when app has a static decoder context. The issue is not reproducible without decoder.
[memory_growth_reproducer.tar.gz](https://github.com/intel/media-driver/files/2361182/memory_growth_reproducer.tar.gz)

1) Extract the archive 
2) make
3) ./memleak_reproducer &
4) ./leak_finder.sh

check VmRSS from leak_finder.sh, e.g.:
`less vm_log.txt  | grep VmRSS | grep -o -E '[0-9]+' > vmrss.log`

The values always show a vivid growing pattern.

**Comment by Stephanie-Qi** [comment]
[https://github.com/intel/media-driver/pull/311](url) is the fix for this issue.
