### ISSUE TITLE
[HEVC FEI] MVPs are not working

### ISSUE THREAD

**Issue by vshampor** [intel/media-driver#312]
asg-hevc-based tests show that the motion vector predictors supplied to the driver are not actually used in a meaningful way.

To reproduce, build the [opensource Intel MediaSDK](https://github.com/Intel-Media-SDK/MediaSDK with BUILD_TOOLS cmake option enabled, then execute the following:

`./asg-hevc -generate -gen_inter -gen_mv -gen_pred -gen_split -i foreman_352x288_300.yuv -o 0001.prmvmvp -w 352 -h 288 -n 300 -g 2 -x 1 -num_active_P 1 -r 1 -log2_ctu_size 5 -no_cu_to_pu_split -max_log2_cu_size 5 -min_log2_cu_size 5 -gpb_off -sub_pel_mode 0 -pred_file 0001_mvmvp.mvin -InitialQP 2`

`./sample_hevc_fei -i 0001.prmvmvp -o 0001.prmvmvp.mvmvp.hevc -w 352 -h 288 -n 300 -f 25 -qp 2 -g 2 -GopRefDist 1 -gpb:off -NumRefFrame 1 -NumRefActiveP 1 -NumPredictorsL0 4 -NumPredictorsL1 4 -encode -EncodedOrder -mvpin 0001_mvmvp.mvin`

`./hevc_fei_extractor 0001.prmvmvp.mvmvp.hevc 0001_mvmvp.ctustat 0001_mvmvp.custat`

`./asg-hevc -verify -gen_inter -gen_mv -gen_pred -gen_split -w 352 -h 288 -n 300 -g 2 -x 1 -num_active_P 1 -r 1 -log2_ctu_size 5 -no_cu_to_pu_split -max_log2_cu_size 5 -min_log2_cu_size 5 -gpb_off -sub_pel_mode 0 -pak_ctu_file 0001_mvmvp.ctustat -pak_cu_file 0001_mvmvp.custat -mv_thres 70 -split_thres 70 -numpredictors 4 -InitialQP 2`

then observe the ~0% passrate and a message "ERROR: Low pass-rate for MVs" in asg-hevc standard output and examine the noise blocks in B frames of the fresh foreman_test.hevc - these will be mostly intra coded, while they should have been inter-coded based off the same noise blocks on the previous frames with a large MV, which had been supplied to the encoder as an MVP during the sample_hevc_fei operation.

**Comment by wangyan-intel** [comment]
Keep a week. If no more response, I will close it.
