### ISSUE TITLE
[gst-vaapi][ICL] vaGetConfigAttributes returns a wrong chroma format.

### ISSUE THREAD

**Issue by feiwan1** [intel/media-driver#318]
When using vaGetConfigAttributes with the parameters:
profile=VAProfileHEVCMain422_10
entrypoint=VAEntrypointVLD
attrib_list.type=VAConfigAttribRTFormat
num_attribs=1
Then the return value of attrib_list.value is VA_RT_FORMAT_YUV420. But the right return value should be VA_RT_FORMAT_YUV422.

**Comment by wangyan42164** [comment]
I will check it.

**Comment by wangyan42164** [comment]
MediaLibvaCaps::CreateDecAttributes() seems to need support VAProfileHEVCMain422_10. I will prepare a patch/PR for this.

**Comment by wangyan42164** [comment]
It can be refined for the other formats like VAProfileHEVCMain444_10

**Comment by feiwan1** [comment]
By using master code, the issue is gone. Thanks for fixing it.
