### ISSUE TITLE
cmake not honoring user settings

### ISSUE THREAD

**Issue by chivakker** [intel/media-driver#331]
Please see description in https://github.com/Intel-Media-SDK/MediaSDK/issues/678

Do not force GNUInstallDirs if user is requesting something else

Example of another program that fixed this
https://github.com/Intel-Media-SDK/MediaSDK/issues/678

**Comment by uartie** [comment]
GNUInstallDirs should already take user settings into account... I suspect the issue might be something else.

**Comment by chivakker** [comment]
After some investigation on this, there's indeed not specific rule for defining those variables.  As mentioned by @uartie this shouldn't be expected to be honored by this package.  Closing this issue; I hope this doesn't cause further confusion
