### ISSUE TITLE
[regression] ffmpeg-vaapi wrong chroma output in jpeg decode 444P image

### ISSUE THREAD

**Issue by uartie** [intel/media-driver#334]
First bad commit:

```
commit 53d304115c3faaa3a2c91c16af079214ebc7d9e1 (HEAD -> master)
Author: xinfeng_(carl)__zhang <carl.zhang@intel.com>
Date:   Sat Sep 29 11:54:52 2018 +0800

    [Decode] call vp in the vaPutImage(CL#803612)
    
    1. set image to be a linear surface
    2. use VP to copy the surface into image
    3. avoid read slowly of tile surface(map_gtt)
    
    Change-Id: I9badccb436d3c6dc17ac90bb89a3936f39a017d4
```

LIBVA_DRIVER_NAME=iHD ffmpeg -hwaccel vaapi -hwaccel_device /dev/dri/renderD128 -v verbose -i smpte_444P.jpeg -pix_fmt yuv444p -f rawvideo -vsync passthrough -vframes 1 -y smpte_444P_720x480.yuv

**Comment by uartie** [comment]
**Expected Result:**
![expected](https://user-images.githubusercontent.com/677859/46308901-b7c54280-c56f-11e8-8142-fe03ac551699.jpg)

**Actual Result:**
_Y'CbCr_
![actual](https://user-images.githubusercontent.com/677859/46308896-b72cac00-c56f-11e8-95c5-eb41ec862a2b.jpeg)
_Cb Only_
![actual-cb](https://user-images.githubusercontent.com/677859/46308898-b72cac00-c56f-11e8-8f7d-cd6722f64c6d.jpeg)
_Cr Only_
![actual-cr](https://user-images.githubusercontent.com/677859/46308899-b72cac00-c56f-11e8-89a1-48f0919168c5.jpeg)

**Comment by uartie** [comment]
JPEG 4:4:4 Input File:
![smpte_444p](https://user-images.githubusercontent.com/677859/46309031-0e328100-c570-11e8-9f92-fc361db363f9.jpeg)

**Comment by XinfengZhang** [comment]
yes, we know the root cause, will revert the change firstly, then check in again after fix these issues

**Comment by XinfengZhang** [comment]
root cause is, get image will call VP to copy data from tile surface to linear surface, but it call some other function to scale the output surfaces
