### ISSUE TITLE
[regression] ffmpeg-vaapi VP9 decode 10bit does not generate bit-matched output

### ISSUE THREAD

**Issue by uartie** [intel/media-driver#335]
First bad commit (FBC):

```
commit 53d304115c3faaa3a2c91c16af079214ebc7d9e1 (HEAD -> master)
Author: xinfeng_(carl)__zhang <carl.zhang@intel.com>
Date:   Sat Sep 29 11:54:52 2018 +0800

    [Decode] call vp in the vaPutImage(CL#803612)
    
    1. set image to be a linear surface
    2. use VP to copy the surface into image
    3. avoid read slowly of tile surface(map_gtt)
    
    Change-Id: I9badccb436d3c6dc17ac90bb89a3936f39a017d4
```

1. Generate reference P010 YUV file with i965 driver and ffmpeg-vaapi
```
LIBVA_DRIVER_NAME=i965 ffmpeg -hwaccel vaapi -hwaccel_device /dev/dri/renderD128 -v verbose -i smpte-p010-640x480.webm -pix_fmt p010le -f rawvideo -vsync passthrough -vframes 10 -y ffmpeg-vaapi-i965-result.yuv
```

2. Generate reference P010 YUV file with i965 driver and gstreamer-vaapi
```
LIBVA_DRIVER_NAME=i965 gst-launch-1.0 -vf filesrc location=/home/uaeoff/Work/workspace/media/src/otc-media/assets/vp9/10bit/smpte-p010-640x480.webm ! matroskademux ! vaapivp9dec ! videoconvert ! video/x-raw,format=P010_10LE ! filesink location=gst-vaapi-i965-result.yuv
```

3. Generate reference P010 YUV file with iHD and ffmpeg-vaapi
```
LIBVA_DRIVER_NAME=iHD ffmpeg -hwaccel vaapi -hwaccel_device /dev/dri/renderD128 -v verbose -i smpte-p010-640x480.webm -pix_fmt p010le -f rawvideo -vsync passthrough -vframes 10 -y ffmpeg-vaapi-iHD-result.yuv
```

4. Compare SSIM between ```fmpeg-vaapi-i965-result.yuv``` and ```gst-vaapi-i965-result.yuv``` results in 1.0 exact match for all YUV channels.

5. Compare SSIM between ```ffmpeg-vaapi-iHD-result.yuv``` and ```fmpeg-vaapi-i965-result.yuv``` or ```gst-vaapi-i965-result.yuv``` results in:
    SSIM_Y MIN: 0.99999707499618751
    SSIM_U MIN: 0.99999956314091665
    SSIM_V MIN: 0.99999958094135644
    SSIM_Y_AVG: 0.99999865890981177
    SSIM_U_AVG: 0.99999956314091665
    SSIM_V_AVG: 0.99999958094135644

Prior to the FBC above, step 5 would produce 1.0 SSIM.

[smpte-p010-640x480.webm.tar.gz](https://github.com/intel/media-driver/files/2435529/smpte-p010-640x480.webm.tar.gz)

**Comment by XinfengZhang** [comment]
thanks @uartie , it should be a regression , will revert it , thanks
