### ISSUE TITLE
[regression] gst-vaapi AVC/HEVC 4CIF (704x576) encode garbage

### ISSUE THREAD

**Issue by uartie** [intel/media-driver#337]
First bad commit:

```
commit 53d304115c3faaa3a2c91c16af079214ebc7d9e1 (HEAD -> master)
Author: xinfeng_(carl)__zhang <carl.zhang@intel.com>
Date:   Sat Sep 29 11:54:52 2018 +0800

    [Decode] call vp in the vaPutImage(CL#803612)
    
    1. set image to be a linear surface
    2. use VP to copy the surface into image
    3. avoid read slowly of tile surface(map_gtt)
    
    Change-Id: I9badccb436d3c6dc17ac90bb89a3936f39a017d4
```

Since this commit, gstreamer-vaapi produces garbage when encoding AVC/HEVC in 4CIF resolution (704x576).

GST_VAAPI_ALL_DRIVERS=1 LIBVA_DRIVER_NAME=iHD gst-launch-1.0 -vf videotestsrc num-buffers=150 ! video/x-raw,format=NV12,width=704,height=576 ! vaapih264enc ! h264parse ! filesink location=test.h264

**Comment by XinfengZhang** [comment]
will revert it

**Comment by DjibrilMAHOUACHE** [comment]
Uh... if imagine if you code phones' camera in video (like frame rate (PAL/SECAM: 25 fps), resolution (PAL/SECAM: 702x576, 704x576 or 720x576), etc...)
