### ISSUE TITLE
gcc compilation with AddressSanitizer fails due to uninitialized variable

### ISSUE THREAD

**Issue by dmitryermilov** [intel/media-driver#339]
gcc ASAN build complains that the following variable isnot initialized:
https://github.com/intel/media-driver/blob/9a64b5e4422e562b73d3eeffffb010873e17f124/media_driver/agnostic/gen8/hw/mhw_vebox_g8_X.cpp#L293 
```

 error: ‘uiInstanceBaseAddr’ may be used uninitialized in this function [-Werror=maybe-uninitialized]
         ResourceParams.dwOffset     = pVeboxHeap->uiIecpStateOffset + uiInstanceBaseAddr;
```

**Comment by XinfengZhang** [comment]
thanks for reporting, will fix it after national holiday. thanks
