### ISSUE TITLE
[VP9][Decode] Invalid max frame width/height attribute reporting

### ISSUE THREAD

**Issue by vshampor** [intel/media-driver#340]
Driver reports max supported frame width/height as 1920x1920 whereas it should actually support resolutions of up to 4K at least.

**Comment by dvrogozh** [comment]
This is reported as https://github.com/Intel-Media-SDK/MediaSDK/issues/639 on mediasdk side.

**Comment by vshampor** [comment]
The fix:
https://github.com/intel/media-driver/pull/341
