### ISSUE TITLE
Remove including local folders that don't exist during compilation

### ISSUE THREAD

**Issue by chivakker** [intel/media-driver#347]
media-driver compiles with the following includes which refer to local folders that don't exist.  gmmlib is found with pkg-config and the others do not exist

cmake ../media-driver && make

 -I<sources>/media-driver/../gmmlib/Source/inc 
-I<sources>/media-driver/../gmmlib/Source/inc/common 
-I<sources>/media-driver/../gmmlib/Source/inc/platform/iAlm 
-I<sources>/media-driver/../gmmlib/Source/inc/umKmInc 
-I<sources>/media-driver/../gmmlib/Source/GmmLib/inc 
-I<sources>/media-driver/../huc/inc

**Comment by yangnin** [comment]
Could u help to review PR#316? it will be helpful for this issue.
