### ISSUE TITLE
Include a readme file on os/libdrm headers

### ISSUE THREAD

**Issue by chivakker** [intel/media-driver#350]
To know where these headers are coming from and how they should be updated please include a README with instructions in

media_driver/linux/common/os/libdrm/

**Comment by chivakker** [comment]
For example, mesa does it here

https://gitlab.freedesktop.org/mesa/mesa/tree/master/include/drm-uapi

**Comment by Sherry-Lin** [comment]
it's diff story with Mesa. Media driver libdrm is for driver internal usage. The interaction between driver and kmd is based on driver request so no need to add it. Please let me know if any questions.
