### ISSUE TITLE
CMRT building as a plug-in, should it have a API/ABI?

### ISSUE THREAD

**Issue by chivakker** [intel/media-driver#358]
CMRT is still a building dependency for this driver.  Can it be isolated at compile time?  If it is installing as part of the features provided by this, could it  define an API/ABI as well?

**Comment by HeFan2017** [comment]
Hi @chivakker , we already have an API definition in media/cmrtlib/agnostic/share/cm_rt.h. Do we need to copy it to somewhere else?

**Comment by dvrogozh** [comment]
To use this library the one needs its headers. So, yes, you need to provide full development and runtime installation for it. Also, please, clarify the usage model: should application link against the library or load it. I.e. please, provide documentation. Finally, do you have stable backward compatible uAPI and uABI for the library?

I suggest you to provide the above information for review before really making changes.

**Comment by HeFan2017** [comment]
hi @dvrogozh , Thanks for the info.

Here are the information needed and it would be nice if you can help review it:

cmrtlib is a runtime library needed when user wants to execute their own GPU kernels on render engine. It calls iHD media driver to load the kernels and allocate the resources. It provides a set of backward compatible APIs defined in media/cmrtlib/agnostic/share/cm_rt.h for user to call directly from application. 

cmrtlib is built and installed together with iHD media driver, on Ubuntu it is /usr/lib/x86_64-gnu/igfxcmrt64.so by default. You need to include the media/cmrtlib/agnostic/share/cm_rt.h and link against igfxcmrt64.so in your application. 

Or, you can build your application with the SDK package we maintained in https://01.org/c-for-media-development-package/. In the SDK, we provided the CMake files to build your own application and kernels. You can also find the spec of APIs in the documents of the SDK package.

**Comment by dvrogozh** [comment]
If user is supposed to link against cmrt library, then it is named incorrectly. You use Windows style name which on Linux is reserved for plugins which are loaded via dlopen. So, if library can be linked against, then it should be named lib<name>.so.<major_version>.<minor_version><micro_version>. Where major.micro.minor is usually just an API version. For cmrt you need to chose a name, it will be libigfxcmrt.so.x.y.z or just libcmrt.so.x.y.z if you want to shorten it.

You can refer to https://github.com/intel/gmmlib/commit/e52096b67adeba76c76007a00924b76152a3f5d6 to see how to setup all that in cmake. Though you will need to additionally adjust a place where you forced the name to omit 'lib' prefix.

Besides *.h files and *.so* files you must provide .pc file, for example igfxcmrt.pc which will contain configuration instructions to build against your library.

The big question which I think will can be a big concern is why cmrt shares repository with the driver. I am not sure that this would be considered acceptable. Still, I believe you need to proceed with the changes I mentioned above while we clarify repository question.

@chivakker : what's your opinion?

**Comment by HeFan2017** [comment]
Just list the tasks we need to follow up:
1. provide readme in cmrtlib folder to state the backward compatibility of API/ABI , and clarify the relationship with the old cmrt
2. Add a flag in cmake files to exclude cmrtllib in build
3. change the lib name to libxxx.so.xxx.xx.xx 
4. provide installation mechanism to install cmrt header files for external users (to /usr/include/cmrt or something similar) 
5. provide installation mechanism to install cmrt.pc file (to usr/lib64/pkgconfig or whatever is system default)

It will be ready in our Q4 release

**Comment by HeFan2017** [comment]
https://github.com/intel/media-driver/pull/394 is created for this:
2. Add a flag in cmake files to exclude cmrtllib in build

**Comment by HeFan2017** [comment]
https://github.com/intel/media-driver/pull/413 is created for this:
3. change the lib name to libxxx.so.xxx.xx.xx

**Comment by HeFan2017** [comment]
https://github.com/intel/media-driver/pull/421 is created for this:
1. provide readme in cmrtlib folder to state the backward compatibility of API/ABI , and clarify the relationship with the old cmrt

**Comment by jbeich** [comment]
Is API compatible with [standalone](https://github.com/intel/cmrt) variant ([packaged](https://repology.org/metapackage/cmrt/versions))?

**Comment by HeFan2017** [comment]
hi @jbeich , the answer is no.
This cmrtlib library is a separate effort from a similar library (https://github.com/intel/cmrt). They may provide the same functionalities but this is not intended to replace the other.

**Comment by HeFan2017** [comment]
hi @dvrogozh @chivakker , https://github.com/intel/media-driver/pull/445 is created for these:
4. provide installation mechanism to install cmrt header files for external users (to /usr/include/cmrt or something similar)
5. provide installation mechanism to install cmrt.pc file (to usr/lib64/pkgconfig or whatever is system default)

**Comment by dvrogozh** [comment]
@HeFan2017 : thank you, we will take a look.
