### ISSUE TITLE
AVC enc doesn't initialize the framerate for BRC when VAEncMiscParameterFrameRate uses zero denominator

### ISSUE THREAD

**Issue by yakuizhao** [intel/media-driver#36]
Currently the framerate in  VAEncMiscParameterFrameRate can be intercept as the below:
>     * denominator = framerate >> 16 & 0xffff;
>    * numerator   = framerate & 0xffff;
>    frame_rate = numerator / denomintor

Of course it still allows that the dominator is zero.  In such case AVC enc deesn't initialize the correct framerate for BRC.

**Comment by XinfengZhang** [comment]
fix by commit 50ec6254
