### ISSUE TITLE
[gst-vaapi][ICL][Decode] vaGetConfigAttributes return wrong RT when the profile set as V1AProfileHEVCMain444 or VAProfileHEVCMain444_10.

### ISSUE THREAD

**Issue by feiwan1** [intel/media-driver#417]
Another patch similar to  PR323 needed to support HEVC profile V1AProfileHEVCMain444/VAProfileHEVCMain444_10.

**Comment by XinfengZhang** [comment]
need to add correct RT format for the range extension.  @wangyan42164 please help on it.
