### ISSUE TITLE
RFC: make gmmlib use optional at compile time

### ISSUE THREAD

**Issue by chivakker** [intel/media-driver#419]
I would like to have gmmlib as an optional allocator that can be decided at compile time.  This is strictly for the driver and not for cmrt.  If possible have the driver using a local allocator that doesn't require an external dependency to be able to compile.  This should simplify the usage and be at par with what i965 driver provides. 

Please comment on this topic.

**Comment by XinfengZhang** [comment]
just allocation part, right? surface & buffer & image is enough?

**Comment by XinfengZhang** [comment]
will close it, because no plan to separate gmmlib and make it as an option
