### ISSUE TITLE
MCTF performance regression on BDW up to 38%

### ISSUE THREAD

**Issue by andreyor** [intel/media-driver#468]
Mediasdk performance validation has shown regression on MCTF workloads beetween Q2 and Q3 releases.

Regression commit was found: https://github.com/intel/media-driver/commit/e80bd63e25504cdc9c1a4ad47713d00cd84a6764

To reproduce, run sample_multi_transcode with par-file:
`-o::h264 <out.h264> -mctf 2:0:10 -b 6000 -i::h264 <1920x1080p_29.97_10mb.264> -u 4 -async 1 -hw`

**Comment by eero-t** [comment]
Does this happen also on something else than BDW?

**Comment by andreyor** [comment]
No, only on BDW.

**Comment by XinfengZhang** [comment]
already been fixed by 6c99fc02c0fd6adaf7f00b1cf571769ebf62e5a5
