### ISSUE TITLE
shaders: warning during VP shaders generation

### ISSUE THREAD

**Issue by dvrogozh** [intel/media-driver#471]
Apply #453, you will see the following warning during shaders generation:
```
[ 63%] Generating return.hex
line 24.10: warning: destination register ARF access requires {Switch} ThreadCtrl
         mov    (1|M0)    ip.0<1>:ud    r8.7<0;1,0>:d
         ^
```

It is coming from here:
https://github.com/intel/media-driver/blob/273ef13413a1c1f3527831df9f2ad962361dd97c/media_driver/agnostic/gen11_icllp/vp/kernel/Source/return.asm#L24

I've been on this commit in IGC (https://github.com/intel/intel-graphics-compiler):
```
commit 4128b9e13ed44ebce29a8df7fbeea4b7a5486afd
Author: Wei Pan <wei.pan@intel.com>
Date:   Thu Nov 8 18:25:27 2018 +0100

    Limit clustering width

    Change-Id: I9ee7beed0689553d7ffe0826a68950d6462f6417

```

**Comment by FurongZhang** [comment]
Will check that.

**Comment by FurongZhang** [comment]
Kernel has a fix.  Requesting to have a try.

**Comment by FurongZhang** [comment]
@XinfengZhang , We sent the binary to bug submitter via Email, not get any response. Need you to check with the bug submitter.

**Comment by XinfengZhang** [comment]
I believe there should be a PR to fix it. @FurongZhang

**Comment by FurongZhang** [comment]
I have requested shader folks to submit a PR to fix this warning.
