### ISSUE TITLE
[SKL][VP8DEC] Vp8 DEC always check last/gold/alt reference in key frame

### ISSUE THREAD

**Issue by mypopydev** [intel/media-driver#48]
Vp8 DEC always check last/gold/alt reference in key frame/ no-key frame case, and give a wrong assert message in key frame case.

**Comment by thomasli21801** [comment]
I would suggest to set L/G/A reference for key frame as itself for error concealment to enhance driver robustness.

**Comment by mypopydev** [comment]
@thomasli21801 I don't think keyframe need to set any L/G/A reference frame in VP8 ENC, and I think driver need to handle this normal case.

**Comment by thomasli21801** [comment]
Why for VP8 ENC? (typo?) I just learnt that self-reference feature for I frame or key frame is removed recently. So it's OK to set L/G/A to nullptr for VP8 key-frame.
