### ISSUE TITLE
[MPEG2][Decode] Invalid max frame width/height attribute reporting

### ISSUE THREAD

**Issue by dmitryermilov** [intel/media-driver#483]
Driver reports max supported frame width/height as 1920x1920 while it should actually support 2K resolution according to https://github.com/intel/media-driver/blob/master/docs/media_features.md

The bug comes from https://github.com/intel/media-driver/blob/f9b1c19c36ead3cca95295581f0fee8b8b99a137/media_driver/agnostic/common/codec/shared/codec_def_common_encode.h#L53, https://github.com/intel/media-driver/blob/e63034d3b6ab5e44f9f434432fc64990466393d3/media_driver/linux/common/ddi/media_libva_caps.cpp#L475

**Comment by XinfengZhang** [comment]
hi @dmitryermilov  could you tell us the codec?

**Comment by XinfengZhang** [comment]
1920---> 2048?

**Comment by dmitryermilov** [comment]
Hi @XinfengZhang ,

It's MPEG2. 
>1920---> 2048?

Yes.

**Comment by dmitryermilov** [comment]
@XinfengZhang , did you have a chance to take a look?

**Comment by XinfengZhang** [comment]
@dmitryermilov , sorry , missed it, will file a PR soon

**Comment by dmitryermilov** [comment]
Thank you!
