### ISSUE TITLE
[gstreamer-vaapi][Denoise][YV12] denoise doesn't work with YV12 input.

### ISSUE THREAD

**Issue by feiwan1** [intel/media-driver#484]
By using gst-vaapi cmdline with YV12 as input, and YV12 output, and enable denoise. But the dumped output YV12 file is bit match with input. 
If using I420 as input or using YV12 + HSBC/sharp, the output is different with input.

Cmdline:
gst-launch-1.0 filesrc location=test.1920x1080.yv12 num-buffers=1 ! rawvideoparse format=yv12 width=1920 height=1080 ! vaapipostproc format=yv12 width=1920 height=1080 denoise=1 ! checksumsink2 file-checksum=false frame-checksum=false plane-checksum=false dump-output=true dump-location=dn_yv12.yuv

Also I checked with libyami and MSDK, all looks have this issue.
libyami:
yamivpp --dn 100 1920x1080.yv12 1920x1080.yami.yv12
MSDK:
sample_vpp -sw 1920 -sh 1080 -scc yv12 -dw 1920 -dh 1080 -dcc yv12 -denoise 100 -i 1920x1080.yv12 -o out.msdk.yv12

**Comment by FurongZhang** [comment]
Start to debug this issue.

**Comment by uartie** [comment]
Easier way to reproduce:
```
gst-launch-1.0 -vf videotestsrc num-buffers=10 \
  ! video/x-raw,format=YV12 \
  ! msdkvpp hardware=true denoise=59 \
  ! video/x-raw,format=NV12 \
  ! videoconvert ! video/x-raw,format=YV12 \
  ! filesink location=denoise.yuv

gst-launch-1.0 -vf videotestsrc num-buffers=10 \
  ! video/x-raw,format=YV12 \
  ! filesink location=nodenoise.yuv

md5sum *denoise.yuv
3d311c36606c55b32bfddb1c08f6efc8  denoise.yuv
3d311c36606c55b32bfddb1c08f6efc8  nodenoise.yuv

```

**Comment by Jister** [comment]
Driver just cannot support YV12/I410 for denoise.

**Comment by feiwan1** [comment]
Close this issue since media-driver will not support this format. And we will remove YV12 denoise test denoise test case.
