### ISSUE TITLE
[SKL][HEVC ENC] HEVC ENC setting the max_transform_hierarchy_depth_inter/max_transform_hierarchy_depth_intra with 3 lead to HEVC ENC output is wrong

### ISSUE THREAD

**Issue by mypopydev** [intel/media-driver#50]
HECV ENC setting the max_transform_hierarchy_depth_inter/max_transform_hierarchy_depth_intra with 3 lead to HEVC ENC output is wrong, and I think driver need to double-check this part.

And when change from 3 to 2, the HEVC ENC output is right.

More information, you can find in link: [https://patchwork.libav.org/patch/64113/](https://patchwork.libav.org/patch/64113/)

**Comment by yakuizhao** [comment]
Thanks for the reporting the issue.
I will take a look at it and provide one fix in time.
