### ISSUE TITLE
[gstreamer-msdk][hevc 8bit encode]the bitrate of hevc cbr encoded file is out of range target 10%

### ISSUE THREAD

**Issue by wangzj0601** [intel/media-driver#512]
System Environment
Platform: KBL/APL/SKL
Arch: x86_64
Kernel: 4.18.0+
libva commit 382acf177ce18c069e0293408afa34c5875296ff
gmmlib commit 001d32de2153e3d37f21d6dfa0a771cd3c34c9d7
msdk: commit 91eded1ef35020b85977c8fcf5d5c14645c89a37
media_driver commit d31ce0b
gstreamer master branch 5688773b91c3ea1094996a573f119230727a0978
repo: https://gitlab.freedesktop.org/gstreamer/gstreamer.git
gst-plugin-bad master branch e5278757c335f45930e1683d7068dadd49b40017
repo: https://gitlab.freedesktop.org/gstreamer/gstreamer-vaapi.git

Bug detailed description
the bitrate of some hevc 8bit cases can not be controlled in target 10%.

failed cases
test_8bit_cbr(bframes=0,bitrate=1000,case=bluesky,fps=30,gop=100,profile=main,slices=1)  13.79 CBR_BITRATE_GAP FAIL
test_8bit_cbr(bframes=0,bitrate=1000,case=bluesky,fps=30,gop=100,profile=main,slices=3)  13.85 CBR_BITRATE_GAP FAIL
test_8bit_cbr(bframes=0,bitrate=1000,case=bluesky,fps=30,gop=30,profile=main,slices=1)  10.98 CBR_BITRATE_GAP FAIL
test_8bit_cbr(bframes=0,bitrate=1000,case=bluesky,fps=30,gop=30,profile=main,slices=3)  11.20 CBR_BITRATE_GAP FAIL
test_8bit_cbr(bframes=0,bitrate=100,case=480p,fps=25,gop=30,profile=main,slices=1)  10.51 CBR_BITRATE_GAP FAIL
test_8bit_cbr(bframes=0,bitrate=200,case=stockholm,fps=25,gop=30,profile=main,slices=1)  15.44 CBR_BITRATE_GAP FAIL
test_8bit_cbr(bframes=0,bitrate=400,case=stockholm,fps=25,gop=30,profile=main,slices=1)  14.94 CBR_BITRATE_GAP FAIL
test_8bit_cbr(bframes=0,bitrate=600,case=stockholm,fps=25,gop=30,profile=main,slices=1)  12.28 CBR_BITRATE_GAP FAIL
test_8bit_cbr(bframes=2,bitrate=1000,case=bluesky,fps=25,gop=100,profile=main,slices=1)  10.07 CBR_BITRATE_GAP FAIL
test_8bit_cbr(bframes=2,bitrate=1000,case=bluesky,fps=30,gop=100,profile=main,slices=1)  16.43 CBR_BITRATE_GAP FAIL
test_8bit_cbr(bframes=2,bitrate=1000,case=bluesky,fps=30,gop=100,profile=main,slices=3)  10.28 CBR_BITRATE_GAP FAIL
test_8bit_cbr(bframes=2,bitrate=100,case=480p,fps=25,gop=30,profile=main,slices=1)  18.55 CBR_BITRATE_GAP FAIL
test_8bit_cbr(bframes=2,bitrate=200,case=stockholm,fps=25,gop=30,profile=main,slices=1)  16.80 CBR_BITRATE_GAP FAIL
test_8bit_cbr(bframes=2,bitrate=3000,case=4k2013,fps=30,gop=30,profile=main,slices=1)  17.57 CBR_BITRATE_GAP FAIL
test_8bit_cbr(bframes=2,bitrate=3000,case=4k2013,fps=30,gop=30,profile=main,slices=3)  17.18 CBR_BITRATE_GAP FAIL
test_8bit_cbr(bframes=2,bitrate=400,case=stockholm,fps=25,gop=30,profile=main,slices=1)  20.37 CBR_BITRATE_GAP FAIL
test_8bit_cbr(bframes=2,bitrate=5000,case=4k2013,fps=30,gop=30,profile=main,slices=1)  15.57 CBR_BITRATE_GAP FAIL
test_8bit_cbr(bframes=2,bitrate=5000,case=4k2013,fps=30,gop=30,profile=main,slices=3)  15.97 CBR_BITRATE_GAP FAIL
test_8bit_cbr(bframes=2,bitrate=600,case=stockholm,fps=25,gop=30,profile=main,slices=1)  11.91 CBR_BITRATE_GAP FAIL

Reproduce Steps
1. build enc as above lists
2. gst-launch-1.0 -vf filesrc location=/media_stream/yuv/4k_2013_3840x2160_I420.yuv num-buffers=75 ! rawvideoparse format=i420 width=3840 height=2160 framerate=30 ! msdkh265enc rate-control=cbr bitrate=5000 gop-size=30 num-slices=3 b-frames=2 hardware=true ! video/x-h265,profile=main ! h265parse ! filesink location=./4k2013-30-3-2-5000-main-30.h265
3. size_encoded = 1344529
    bitrate_actual = 1344529 * 8 * 30 /1024 / 75 = 4201.65
    bitrate_gap = 15.97%

**Comment by XinfengZhang** [comment]
@wangzj0601 is the issue still there? we have multiple fixes merged

**Comment by wangzj0601** [comment]
@feiwan1 Please help take a look at the all issues under my name, thanks.

**Comment by feiwan1** [comment]
thanks @wangzj0601 for caring the issues :), @FocusLuo Could you help to confirm this issue ?

**Comment by xinyudox** [comment]
I tried a few cases with last media driver on APL, and here's the result.
bframes=0,bitrate=1000,case=bluesky,fps=30,gop=100,profile=main,slices=1    bitrate_gap = 13.78%
bframes=0,bitrate=1000,case=bluesky,fps=30,gop=100,profile=main,slices=3    bitrate_gap = 12.55%
bframes=0,bitrate=1000,case=bluesky,fps=30,gop=30,profile=main,slices=1      bitrate_gap = 11.33%

**Comment by Xiaogangli-intel** [comment]
@xinyudox how many frames in your tests? It should be bigger than 200 frames, otherwise, it's not accurate.

**Comment by xinyudox** [comment]
I tried a few cases with last media driver on APL, and here's the result.   
num-buffers=300
bframes=0,bitrate=1000,case=bluesky,fps=30,gop=100,profile=main,slices=3       bitrate_gap = 31.51%
bframes=0,bitrate=1000,case=bluesky,fps=30,gop=100,profile=main,slices=1       bitrate_gap = 32.52%

APL | OS: ubuntu 18.04 | kernel 5.7.0-rc5-daily-nocodec-20200519
libva | afca400d5629409ae7d51c4b1109a1b73ab2844a
Mediasdk | 04626ad4ca5d720957cbe59fd7b468d978e36150
gmmlib | 40c7d14fd16a4282410a2f6b0cd59251c8e41d5c
iHD Driver | 388ea75
libva-utils | 287f3a581f46f2e38aa7dc8b371033e91110da6a
gst-plugins-bad | 495ed45d056cc4ae88c95b5587732d87382e93a1
gst-plugins-base | 93cb325fa133d494369761b029b0583a2ff66605
gstreamer-vaapi | b1832223ffb72360e01fe30cdf0b88423b0455b2
gst-plugins-good | 5a7275220bd18cb60b8f91ccadf919554de68383
gstreamer | cecb2912633164a66a942d5413404812ad8fc0a0
gst-checksumsink | 766a46d628a78345de6ac6fe932dd2c3a80d59b4
vaapi-fits-full | 14fdb2a083fbc1e45ff2fc6a428d494110ee3277
vaapi-fits | 950b99722a387cba1ce30c72f7c514d146ff0083

**Comment by Xiaogangli-intel** [comment]
Synced with @FocusLuo, as this issue cannot be reproduced on my side based on the latest tool list, I will close this now. If it still exist on your side, please issue a new one.
