### ISSUE TITLE
[DDI] m_encMax4KWidth naming

### ISSUE THREAD

**Issue by shural** [intel/media-driver#53]
m_encMax4KWidth is set as ENCODE_4K_MAX_PIC_WIDTH, but what if we check 8K in the future, in that sense the naming is not good. This applies to Height check as well.

**Comment by XinfengZhang** [comment]
change to m_encMaxWidth and m_encMaxHeight?

**Comment by XinfengZhang** [comment]
@shural  we have to keep it , or rename it to m_enc4KWidth, m_enc4KHeight, 
in the future, we can add m_enc8KWidth and m_enc8KHeight to report the capabilities. 
is it ok?

**Comment by XinfengZhang** [comment]
it's static variable for max resolution check, should add new variable and macro for 8K. so close it.
