### ISSUE TITLE
No packed 24 RGB  image format support

### ISSUE THREAD

**Issue by HeJunyan** [intel/media-driver#532]
Need to support packed 24 RGB image format as input.

**Comment by FurongZhang** [comment]
May I know the reason why packed 24 RGB image format is needed? For what kind of usage? Thanks a lot in advance!

**Comment by HeJunyan** [comment]
I know this is a rarely used format but the request is we need to support:
gst-launch-1.0 videotestsrc ! video/x-raw, format=RGB, framerate=30/1, width=640, height=360 ! vaapipostproc ! glimagesink

here format=RGB is packed 24 bits RGB

**Comment by dnagasun** [comment]
> May I know the reason why packed 24 RGB image format is needed? For what kind of usage? Thanks a lot in advance!

TSD's customer are using this format for camera support. So there is need to enable this for IOTG product.

**Comment by FurongZhang** [comment]
https://github.com/intel/media-driver/pull/594

**Comment by FurongZhang** [comment]
PR has been merged.

**Comment by FurongZhang** [comment]
@HeJunyan  This fix has been merged into master branch. Is it possible for you to close this issue? Thanks a lot in advance!

**Comment by HeJunyan** [comment]
Verified and OK
