### ISSUE TITLE
Need to add RGB16(RGB565) image format support

### ISSUE THREAD

**Issue by HeJunyan** [intel/media-driver#533]
No RGB16(RGB565) image format support now. The RGB565 or BGR565 image format should be added.

**Comment by FurongZhang** [comment]
Will check it and get back.

**Comment by FurongZhang** [comment]
May I know what the usage is for RGB16(565)? Now, the trending is 8bit, 10bit. May I know if there is someone who is using RGB565? Thanks a lot in advance!

**Comment by HeJunyan** [comment]
Some requirement says:

 gst-launch-1.0 filesrc location= /media/Raw_Videos/Prog_Planar_RGB16_320x240_5frames.yuv ! videoparse width=320 height=240 format=rgb16 ! vaapipostproc format=nv12 ! glimagesink

Here, rgb16 is the RGB565 format.

**Comment by eero-t** [comment]
> May I know what the usage is for RGB16(565)? Now, the trending is 8bit, 10bit.

Trend for 8 & 10-bit data is mainly for human eyes.  Neural networks related software typically requires RGB input,  YUV is rarely used there.  They process data with low number of bits, both for training the network (with huge amount of input video) and when the trained network processes data.  Don't know whether anything specifically uses 565 though.

**Comment by dnagasun** [comment]
TSD's customer are using this format for camera support. So there is need to enable this for IOTG product.

**Comment by dnagasun** [comment]
> May I know what the usage is for RGB16(565)? Now, the trending is 8bit, 10bit. May I know if there is someone who is using RGB565? Thanks a lot in advance!

TSD's customer are using this format for camera support. Specifically for Mondelo. So there is need to enable this for IOTG product. Thanks in advance for your support.

**Comment by FurongZhang** [comment]
Sure. Then, we will support that. Thanks a lot for the information.
