### ISSUE TITLE
Failed to create XRGB format image.

### ISSUE THREAD

**Issue by HeJunyan** [intel/media-driver#534]
vaQueryImageFormats return XRGB format but we failed to create a XRGB image using vaCreateImage,
return VA_STATUS_ERROR_UNIMPLEMENTED error.

**Comment by FurongZhang** [comment]
@Jister  Is it possible for you to check that? Thanks a lot in advance!

**Comment by FurongZhang** [comment]
https://github.com/intel/media-driver/pull/572  fix is filed. @HeJunyan, Could you please let me know how to verify it? Thanks a lot in advance!

**Comment by HeJunyan** [comment]
Verified, OK

**Comment by FurongZhang** [comment]
Thanks a lot.

**Comment by FurongZhang** [comment]
@HeJunyan Since verified, how about to close it? Thanks a lot in advance!
