### ISSUE TITLE
Need to add ARGB-10LE image format support 

### ISSUE THREAD

**Issue by HeJunyan** [intel/media-driver#538]
Need to support 10bits ARGB format.  The display may support 10bits ARGB input.
E.G.
gst-launch-1.0 videotestsrc ! capsfilter caps=video/x-raw,format=P010_10LE ! vaapipostproc format=argb-10le ! glimagesink

need 10bits ARGB image as input to display.

**Comment by FurongZhang** [comment]
I have added 10bit RGB in Libva. Currently, the pull request is being reviewing. Driver side, will also submit a patch.

**Comment by xhaihao** [comment]
@FurongZhang @XinfengZhang what is the fourcc code for 10bit RGB?

**Comment by FurongZhang** [comment]
@xhaihao  I added a PR in Libva. And I am fixing the RGB10 format issues, will merge into master after I finish the fixes.

**Comment by FurongZhang** [comment]
@xhaihao  I have already added you into the link. Is it possible for you to help to review that? Thanks a lot in advance!

**Comment by FurongZhang** [comment]
@xhaihao Your merge about ARGB10 fixed your issue?

**Comment by xhaihao** [comment]
@FurongZhang I need your driver fix, I only merged the fourcc code  in libva.

**Comment by HeJunyan** [comment]
Still need to add ARGB10 to surface and image query, and then, application can know such kind of format exists.

**Comment by dnagasun** [comment]
hi @FurongZhang, appreciate if you could provide the status of this fix? Need media driver fix to close this issue.

**Comment by FurongZhang** [comment]
I am working on that now.

**Comment by FurongZhang** [comment]
https://github.com/intel/media-driver/pull/651
https://github.com/intel/media-driver/pull/652
https://github.com/intel/media-driver/pull/653

**Comment by FurongZhang** [comment]
I have already submitted these 3 PRs, please help to verify if RGB10 support is ready or not in driver. If not, please let me know. If yes, please close this issue.

**Comment by FurongZhang** [comment]
And glimagesink will not support 10bit in the near future in GStreamer.

**Comment by xhaihao** [comment]
The latest glimagesink may accept P010_10LE/BGR10A2_LE/RGB10A2_LE on little endian and do down-sampling internally if the framebuffer is 8bit.

**Comment by HeJunyan** [comment]
the #651 really fix query problem.
I am sorry I made a mistake.
After check, I find the Media_Format_R10G10B10A2 is only supported in DdiMedia_DeriveImage.
But for DdiMedia_CreateImage and GET/PUT functions, we just get VA_STATUS_ERROR_UNIMPLEMENTED.
All the images related functions need to add Media_Format_R10G10B10A2 support.
The logic in  gst-vaapi will create the image first and upload/download the images to surface.
while the logic in msdk seems directly derive the image from surface and use it.
That's the difference make the msdk can work while gstreamer-vaapi can not.

**Comment by FurongZhang** [comment]
We have already added 10bit RGB support in DdiMedia_CreateImage and GET/PUT functions. The code fixes have been merged. Please check and let us know if any issues, thanks a lot in advance!

**Comment by HeJunyan** [comment]
Thanks, and verified.
