### ISSUE TITLE
[DDI] VAEntrypointStats should not be bounded to AVC FEI

### ISSUE THREAD

**Issue by shural** [intel/media-driver#54]
VAEntrypointStats is generic, and can be used for both AVC and HEVC FEI, and may later for other encoders. It's not good coding behavior to bound VAEntrypointStats to AVC FEI in MediaLibvaCaps::GetEncodeCodecMode.

Also, if in regular calling sequence that DDI decode or encode key is already parsed from input parameters such as profile and vaentrypoint, suggest use the key to map to CODECHAL keys defined in lower layer (i.e., CODECHAL) instead of parsing the same profile and vaentrypoint again.

**Comment by XinfengZhang** [comment]
changing it to be bounded with AVC will also impact other api. such as VAStatus vaQueryConfigEntrypoints, for the given profile such as VAProfileH264Main, it should report VAEntrypointStats .

**Comment by kelvinhu325** [comment]
Yes, VAEntrypointStats is generic, but driver implements VAEntrypointStats with the same path as AVC currently

**Comment by XinfengZhang** [comment]
close the issue, it will be changed after HEVC preEnc is enable. the Entrypoint could be combined for different codec
