### ISSUE TITLE
[H264][DEC] Incorrected resolutions return

### ISSUE THREAD

**Issue by aulitin** [intel/media-driver#540]
Found problem with h264 decode on BDW Ubuntu 18.04.. Function vaQueryConfigEntrypoints don't work correctly. This function returns 8192x8192 resolution for VAProfileH264High profile and VAEntrypointVLD entrypoint. But [it](https://github.com/intel/media-driver/blob/master/docs/media_features.md) says they the output resolution is 4K.
Commit 0e46d8574ca07d4580c20dadefd57a005213855a introduced regression. 
Based on the code this incorrect output may be found on other platforms.

**Comment by XinfengZhang** [comment]
thanks report, yes, BDW AVC does not support level 6.x, @wangyan42164 , please help to check it

**Comment by wangyan42164** [comment]
I will check it.

**Comment by aulitin** [comment]
@wangyan42164, Can your pull request fix [this problem](https://github.com/intel/media-driver/issues/550)?
I am waiting for fix. When are you going to merge pull request?
