### ISSUE TITLE
[HEVC][ENC] Incorrected resolutions return

### ISSUE THREAD

**Issue by aulitin** [intel/media-driver#550]
Found problem with hevc encode on SKL and BXT Ubuntu 18.04.. Function vaQueryConfigEntrypoints doesn't work correctly. This function returns 8192x8192 resolution for VAProfileHEVCMain profile and VAEntrypointEncSlice entrypoint. But [this table](https://github.com/intel/media-driver/blob/master/docs/media_features.md) says that the output resolution is 4K.
Version Media-drver: 224141564fe20c19e279ec004f89fa92534f90a0

**Comment by semelianova** [comment]
The same problem appears on CFL and KBL. 8k is not supported on platform less ICL.

**Comment by dmitryermilov** [comment]
@aulitin , @semelianova , would you like to prepare a pool request with a fix to the driver repo?

**Comment by aulitin** [comment]
@dmitryermilov, I am unable to do it soon.

**Comment by Xiaogangli-intel** [comment]
@aulitin [the table](https://github.com/intel/media-driver/blob/master/docs/media_features.md) was updated, the output resolution should be 8K, could you confirm it?

**Comment by semelianova** [comment]
@Xiaogangli-intel Is the table correct? When try to encode or decode 8K resolution stream I get VA_STATUS_ERROR_RESOLUTION_NOT_SUPPORTED from driver caps

**Comment by semelianova** [comment]
I think need to add HEVC profile with 8k resolution in  [CheckEncodeResolution ](https://github.com/intel/media-driver/blob/b6e7cc5cdd5e1a306c47e1bf48952e381712b414/media_driver/linux/common/ddi/media_libva_caps.cpp#L1944) function. Now we fall in default case and compare with 4K max.

**Comment by semelianova** [comment]
Hi @Xiaogangli-intel, Are there any updates? Now HEVCe doesn't work with 8k. Should HEVCe support 8k resolution on gen9 platforms? Does driver really support it?
