### ISSUE TITLE
BGRA and ARGB are taken as the same format in the driver.

### ISSUE THREAD

**Issue by xhaihao** [intel/media-driver#554]
in DdiMedia_OsFormatToMediaFormat() in media_libva.cpp:

>        case VA_FOURCC_BGRA:
>        case VA_FOURCC_ARGB:
> #ifdef VA_RT_FORMAT_RGB32_10BPP
>             if(VA_RT_FORMAT_RGB32_10BPP == rtformatType)
>             {
>                 return Media_Format_B10G10R10A2;                                                                                                                                               
>             }
> #endif
>             return Media_Format_A8R8G8B8;

But according to the comment in va.h, VA_FOURCC_BGRA and VA_FOURCC_ARGB should be different.

**Comment by feiwan1** [comment]
By using gst-vaapi to convert NV12 to ARGB, but the dumped output format is BGRA. Same issue by using yamivpp.

gst-vaapi:
gst-launch-1.0 videotestsrc num-buffers=10 pattern=4 ! video/x-raw,format=NV12,width=720,height=480 ! vaapipostproc format=bgra ! filesink location=red.bgra

libyami:
yamivpp 720x480.nv12 720x480.argb
