### ISSUE TITLE
README file wrong or not updated correctly?

### ISSUE THREAD

**Issue by makedir** [intel/media-driver#561]
https://github.com/intel/media-driver/blob/master/README.md#hw-media-features

Why does it claim, Coffee Lake doesnt support HEVC 8 and 10bit hw encode?

![image](https://user-images.githubusercontent.com/6721083/54403201-749afe00-46cf-11e9-82bc-e7d0eb0ad5ef.png)

The part about CNL cant do AVC HW encode also doesnt make sense. Kaby Lake should also do all these, and should do VP9 encode too, no?

This is from ffmpeg:

![image](https://user-images.githubusercontent.com/6721083/54403430-4b2ea200-46d0-11e9-9959-4ee99db408ba.png)

**Comment by Entropy512** [comment]
If I'm reading the documentation correctly, those platforms require nonfree shaders in order to encode those particular codecs.  You've linked the table for the fully opensource version of the driver.  Scroll up for the table of codecs supported with nonfree shaders.

**Comment by Sherry-Lin** [comment]
Yes, we have two build options. Non-free kernel is default option which could support full features(https://github.com/intel/media-driver#features-in-default-driver-build), and free kernel is mapping to full open source build(https://github.com/intel/media-driver#features-in-open-source-build).

**Comment by XinfengZhang** [comment]
already updated it https://github.com/intel/media-driver#components-and-features
