### ISSUE TITLE
[Enhancement][FFmpeg vaapi] support for HEVC Encode Trellis

### ISSUE THREAD

**Issue by fulinjie** [intel/media-driver#574]
Do we have this feature or have the plan to enable Trellis for HEVC encode?

**Comment by Xiaogangli-intel** [comment]
Do you mean Trellis-QP?

**Comment by fulinjie** [comment]
Yes, for quantization

**Comment by Xiaogangli-intel** [comment]
Currently it's not supported, I didn't see any plan until now.

**Comment by fulinjie** [comment]
@Xiaogangli-intel thanks, will leave this feature open in FFmpeg.
Closed.
