### ISSUE TITLE
[SKL][VC1 DEC] Need to skip emulation prevention byte to calc macroblock offset in VC1 DEC

### ISSUE THREAD

**Issue by mypopydev** [intel/media-driver#58]
Need to skip emulation prevention byte to calc macroblock offset in VC1 DEC, but as VA-API, emulation prevention byte will be handle in driver, now iHD handle emulation prevention byte in H.264/H.265 DEC, but didn't handle in VC1 DEC.

And we have a workround (https://github.com/mypopydev/FFmpeg/commit/80b86dabaf0352eafa6503fd04d4e72626cc6e3c) for this, but I think need to fix in iHD driver.

**Comment by yakuizhao** [comment]
Thanks for reporting the issue.
Yes.  This can be handled in driver like H264/H265.

But as one middleware tries to adjust the macroblock for VC1,  we need to let them know the update. Otherwise it will be broken after it is added into the driver.

**Comment by XinfengZhang** [comment]
@mypopydev seems your WA is for VP8. it is not related with the description.
