### ISSUE TITLE
Log the version information of media kernels

### ISSUE THREAD

**Issue by ss22ongithub** [intel/media-driver#596]
This media_driver/agnostic/gen9/vp/kernel/igvpkrn_g9.c (and other similar files ) has the binary content of the 'kernels' used in the driver. 

For the purpose of clarity and debugging it  would help to know version information of the 'kernels' used in the media driver . As  this   file is auto generated KernelBinToSource.exe tool  it should be possible to include a const. string which can hold the version information . The same can be logged in the debug logs .

Could you please check the feasibility of doing including this change ?

**Comment by XinfengZhang** [comment]
it is hard to implement it, because there are several kernel combined in igvpkrn_g9.c  change the tools and check the fill a version list of each kernel?
