### ISSUE TITLE
[avc vdenc] multislice encode file have garbage and decode error

### ISSUE THREAD

**Issue by zhuqingliang** [intel/media-driver#612]
bug describe
NOT  lowpower mode , multislice encode  is good 
enable lowpower mode , the h264 file have garbage ,  both in ffmpeg and gstreamer.

1. environment
Platform: KBL
Platform: ICL
Arch: x86_64
Kernel: 5.0.0
Libva: c98b06d2b8c00dc4df628488b672711b3f0eb118
iHD_driver: 5366de39a3f3b7f256b540bfa0ba088133315610
libva-utils: 375e4eaae3377c1806e83874f9fa9b79b1f225b1
ffmpeg-vaapi: 9dece050ef01c70df1ac74a04da3548b3c0d79a9

2 ffmpeg 
-----step 1 : 
ffmpeg -hwaccel vaapi -vaapi_device /dev/dri/renderD128 -v verbose -f rawvideo -pix_fmt yuv420p -s:v 720x480 -i  720x480p.yuv -vf 'format=nv12,hwupload' -c:v h264_vaapi -profile:v high -rc_mode CQP -g 30 -qp 10 -quality 4 -slices 3 -low_power 1 -vframes 150 -y 720x480p.264

-----step 2:  
ffmpeg -i  720x480p.264 -pix_fmt yuv420p -f rawvideo  -vframes 1 -vsync passthrough  -y dump.yuv 
dump.yuv have garbage :
error message:
[h264 @ 0x1e63080] decode_slice_header error
[h264 @ 0x1e63080] slice type 32 too large at 1215
[h264 @ 0x1e63080] decode_slice_header error
[h264 @ 0x1e63080] slice type 32 too large at 1260
[h264 @ 0x1e63080] decode_slice_header error
[h264 @ 0x1e63080] slice type 32 too large at 1305
 
3   gsteamer
-------step1 
gst-launch-1.0 -vf filesrc location=720x480p.yuv num-buffers=150 ! rawvideoparse format=i420 width=720 height=480 ! videoconvert ! video/x-raw,format=NV12 ! vaapih264enc rate-control=cqp keyframe-period=30 init-qp=28 quality-level=4 num-slices=3 tune=low-power ! video/x-h264,profile=high ! h264parse ! filesink location=aa.264
-------step2
 gst-launch-1.0 -vf filesrc location=480p-cqp-high-30-28-3-4-low-power.h264 ! h264parse ! vaapih264dec ! videoconvert ! video/x-raw,format=I420 ! checksumsink2 file-checksum=false frame-checksum=false plane-checksum=false dump-output=true qos=false dump-location=aa.yuv
--------step 3 
observe aa.yuv
![image](https://user-images.githubusercontent.com/29194447/56642417-f48e8d80-66a9-11e9-80b6-ef5aab328add.png)

**Comment by uartie** [comment]
This is a duplicate of #389

**Comment by zhuqingliang** [comment]
reduplicate , close .
