### ISSUE TITLE
[gstreamer-vaapi][encode][Jpeg] jpeg file show noise by using UYVY input format.

### ISSUE THREAD

**Issue by feiwan1** [intel/media-driver#616]
When using UYVY format as the input for jpeg encode, the output file show noise.
(This need the patch #615 )

cmdline:
$ gst-launch-1.0 videotestsrc num-buffers=1 ! video/x-raw,format=UYVY ! vaapijpegenc ! jpegparse ! filesink location=out.uyvy.jpeg

And I used jpegenc from libva-utils got the same result:
$ jpegenc 320 240 in.uyvy out.jpeg 2 50

Ps, when using YUY2, the output looks good.

Noise picture:
![out](https://user-images.githubusercontent.com/25519094/56948620-4c723c00-6b63-11e9-95b0-4bc1ca579442.jpeg)

Expected picture:
![gst yuy2](https://user-images.githubusercontent.com/25519094/56948649-5dbb4880-6b63-11e9-8279-68b68a1789f5.jpeg)

**Comment by wangyan-intel** [comment]
@feiwan1 I tried your command with #615 but no this issue on KBL. What platform do you run it on? My tried commit is 54a198. Thanks.

**Comment by feiwan1** [comment]
I am using SKL. @wangyan-intel

**Comment by dnagasun** [comment]
I tried the command with #615 in EHL Simics, can see this issue. 
it fails with UYVY, but looks good when tried with YUY2.

**Comment by wangyan-intel** [comment]
@feiwan1 Could you please try #648 ? Thanks.

**Comment by feiwan1** [comment]
@wangyan-intel , with #615 and this patch, the issue is gone on SKL. Thanks.

**Comment by wangyan42164** [comment]
For ICL platform, also need #658.
