### ISSUE TITLE
[ffmpeg-vaapi][max_frame_size][vaGetConfigAttributes][Enhancement]

### ISSUE THREAD

**Issue by fulinjie** [intel/media-driver#643]
Since VAConfigAttribMaxFrameSize has been added in libva,https://github.com/intel/libva/commit/dcbd65bf03d0755bbdaa1e69b81480e8de1fb8e2
IMHO, m_attributes for m_profileEntryTbl need to be added too to make the query for max_frame_size valid.

Message:
[h264_vaapi @ 0x5594b51cbec0] Max frame size attribute is not supported.

p (*m_profileEntryTbl[1].m_attributes)
$21 = std::map with 8 elements = {[VAConfigAttribRTFormat] = 131075, [VAConfigAttribEncryption] = 2147483648, [VAConfigAttribDecSliceMode] = 3, [VAConfigAttribDecProcessing] = 1, 
[VAConfigAttribMaxPictureWidth] = 8192, [VAConfigAttribMaxPictureHeight] = 8192, [VAConfigAttribProcessingRate] = 2, [VAConfigAttribCustomRoundingControl] = 1}

**Comment by wangyan42164** [comment]
@fulinjie I submitted #656 to fix it. It works fine on my side. Could you please try it? Thanks.

**Comment by fulinjie** [comment]
@wangyan42164 thanks Yan, it works in avc encoder and returns expected attrib.value for VAEncMiscParameterTypeMultiPassFrameSize.

A remained concern:
Is there any plan to support VAEncMiscParameterTypeMaxFrameSize which is also defined in libva?

If no, i would like to consider the multi path solution only.

**Comment by wangyan42164** [comment]
@fulinjie VAEncMiscParameterTypeMaxFrameSize has been supported in current media driver.

**Comment by wangyan-intel** [comment]
@fulinjie I checked the code of media driver. VAEncMiscParameterTypeMaxFrameSize should be for VP8/9 only.  VAEncMiscParameterTypeMultiPassFrameSize is for AVC only. Thanks.

**Comment by fulinjie** [comment]
Thanks a lot.
