### ISSUE TITLE
Video Playback in the browser fails on ChromeOS after the changes:  [Decode] Enable HEVC decode frame split for ICL Linux

### ISSUE THREAD

**Issue by ss22ongithub** [intel/media-driver#655]
Video playback VP8 /VP9 and H264 in chrome browser on the chromium OS,  hangs as soon as the the video starts playing ex. youtube.com

Board used : ICL RVP
CHROMEOS_RELEASE_CHROME_MILESTONE=77
CHROMEOS_RELEASE_NAME=Chromium OS
CHROMEOS_RELEASE_VERSION=12278.0.2019_06_17_0146
Linux kernel version: Linux  5.2.0-rc5-intel-next-04694-g77e0c844b276

The changes were backtracked and found the issue always occurs after the below commit ID :
commit a466be0b1a79f47bf09d2f5134591fe17e92170c
Author: TonyYe <tony.ye@intel.com>
Date:   Thu Jun 13 15:24:38 2019 +0800
[Decode] Enable HEVC decode frame split for ICL Linux
Enable HEVC decode frame split for ICL Linux.
Change-Id: I63a4e2b8e23850689aa84a92ca9d91cf1181af90

**Comment by XinfengZhang** [comment]
@ss22ongithub  , as I know, you work on it and triage the issue, could you update current status?
