### ISSUE TITLE
Is look_ahead support planned?

### ISSUE THREAD

**Issue by OpenSourceAnarchist** [intel/media-driver#657]
MediaSDK supports LA_ICQ and LA (VBR) encoding. I just wanted to know if this is a planned feature of media-driver as well?

Is there a _noticeable_ benefit to LA_ICQ compared to standard ICQ? According to [this MediaSDK page](https://software.intel.com/en-us/articles/advanced-bitrate-control-methods-in-intel-media-sdk), there is a comparison between VBR and ICQ, and VBR and LA_ICQ, but not ICQ and LA_ICQ. If there is a significant quality/encoding speed difference, what is it?

I only ask because FFmpeg developers recommend media-driver rather than MediaSDK/libmfx.

**Comment by XinfengZhang** [comment]
LA will keep a lot of frames, it is not suitable to implement it inside driver
