### ISSUE TITLE
[RFC] is it  support  KBL/GLK/CFL in media-driver now?

### ISSUE THREAD

**Issue by mypopydev** [intel/media-driver#67]
Now the media-driver support BDW (Broadwell)/SKL (Skylake)/BXT (Broxton) / APL (Apollolake)/CNL (Cannonlake), is it will support KBL/GLK/CFL? Tks,

After grep the code with cmd as follow:

barry@barry-HP-ENVY-Notebook:~/Sources/umd_dev/media-driver$ **grep "DeviceInfoFactory<GfxDeviceInfo>" * -rn**

get the out put as follow: 
media_driver/linux/gen10/ddi/media_sysinfo_g10.cpp:33://extern template class DeviceInfoFactory<GfxDeviceInfo>;
media_driver/linux/gen10/ddi/media_sysinfo_g10.cpp:34:typedef DeviceInfoFactory<GfxDeviceInfo> base_fact;
media_driver/linux/gen10/ddi/media_sysinfo_g10.cpp:261:static bool cnlDevice5a4a = DeviceInfoFactory<GfxDeviceInfo>::
media_driver/linux/gen10/ddi/media_sysinfo_g10.cpp:264:static bool cnlDevice5a42 = DeviceInfoFactory<GfxDeviceInfo>::
media_driver/linux/gen10/ddi/media_sysinfo_g10.cpp:267:static bool cnlDevice5a41 = DeviceInfoFactory<GfxDeviceInfo>::
media_driver/linux/gen10/ddi/media_sysinfo_g10.cpp:270:static bool cnlDevice5a49 = DeviceInfoFactory<GfxDeviceInfo>::
media_driver/linux/gen10/ddi/media_sysinfo_g10.cpp:273:static bool cnlDevice5a44 = DeviceInfoFactory<GfxDeviceInfo>::
media_driver/linux/gen10/ddi/media_sysinfo_g10.cpp:276:static bool cnlDevice5a59 = DeviceInfoFactory<GfxDeviceInfo>::
media_driver/linux/gen10/ddi/media_sysinfo_g10.cpp:279:static bool cnlDevice5a5a = DeviceInfoFactory<GfxDeviceInfo>::
media_driver/linux/gen10/ddi/media_sysinfo_g10.cpp:282:static bool cnlDevice5a5c = DeviceInfoFactory<GfxDeviceInfo>::
media_driver/linux/gen10/ddi/media_sysinfo_g10.cpp:285:static bool cnlDevice5a50 = DeviceInfoFactory<GfxDeviceInfo>::
media_driver/linux/gen10/ddi/media_sysinfo_g10.cpp:288:static bool cnlDevice5a51 = DeviceInfoFactory<GfxDeviceInfo>::
media_driver/linux/gen10/ddi/media_sysinfo_g10.cpp:291:static bool cnlDevice5a52 = DeviceInfoFactory<GfxDeviceInfo>::
media_driver/linux/gen10/ddi/media_sysinfo_g10.cpp:294:static bool cnlDevice5a54 = DeviceInfoFactory<GfxDeviceInfo>::
media_driver/linux/gen10/ddi/media_sku_wa_g10.cpp:34://extern template class DeviceInfoFactory<GfxDeviceInfo>;
media_driver/linux/gen8/ddi/media_sysinfo_g8.cpp:229://extern template class DeviceInfoFactory<GfxDeviceInfo>;
media_driver/linux/gen8/ddi/media_sysinfo_g8.cpp:230:typedef DeviceInfoFactory<GfxDeviceInfo> base_fact;
media_driver/linux/gen8/ddi/media_sysinfo_g8.cpp:232:static bool bdwDevice1602 = DeviceInfoFactory<GfxDeviceInfo>::
media_driver/linux/gen8/ddi/media_sysinfo_g8.cpp:235:static bool bdwDevice1606 = DeviceInfoFactory<GfxDeviceInfo>::
media_driver/linux/gen8/ddi/media_sysinfo_g8.cpp:238:static bool bdwDevice160a = DeviceInfoFactory<GfxDeviceInfo>::
media_driver/linux/gen8/ddi/media_sysinfo_g8.cpp:241:static bool bdwDevice160d = DeviceInfoFactory<GfxDeviceInfo>::
media_driver/linux/gen8/ddi/media_sysinfo_g8.cpp:244:static bool bdwDevice160e = DeviceInfoFactory<GfxDeviceInfo>::
media_driver/linux/gen8/ddi/media_sysinfo_g8.cpp:247:static bool bdwDevice160b = DeviceInfoFactory<GfxDeviceInfo>::
media_driver/linux/gen8/ddi/media_sysinfo_g8.cpp:250:static bool bdwDevice1612 = DeviceInfoFactory<GfxDeviceInfo>::
media_driver/linux/gen8/ddi/media_sysinfo_g8.cpp:253:static bool bdwDevice1616 = DeviceInfoFactory<GfxDeviceInfo>::
media_driver/linux/gen8/ddi/media_sysinfo_g8.cpp:256:static bool bdwDevice161a = DeviceInfoFactory<GfxDeviceInfo>::
media_driver/linux/gen8/ddi/media_sysinfo_g8.cpp:259:static bool bdwDevice161d = DeviceInfoFactory<GfxDeviceInfo>::
media_driver/linux/gen8/ddi/media_sysinfo_g8.cpp:262:static bool bdwDevice161e = DeviceInfoFactory<GfxDeviceInfo>::
media_driver/linux/gen8/ddi/media_sysinfo_g8.cpp:265:static bool bdwDevice161b = DeviceInfoFactory<GfxDeviceInfo>::
media_driver/linux/gen8/ddi/media_sysinfo_g8.cpp:269:static bool bdwDevice1622 = DeviceInfoFactory<GfxDeviceInfo>::
media_driver/linux/gen8/ddi/media_sysinfo_g8.cpp:272:static bool bdwDevice1626 = DeviceInfoFactory<GfxDeviceInfo>::
media_driver/linux/gen8/ddi/media_sysinfo_g8.cpp:275:static bool bdwDevice162b = DeviceInfoFactory<GfxDeviceInfo>::
media_driver/linux/gen8/ddi/media_sysinfo_g8.cpp:278:static bool bdwDevice162a = DeviceInfoFactory<GfxDeviceInfo>::
media_driver/linux/gen8/ddi/media_sysinfo_g8.cpp:281:static bool bdwDevice162d = DeviceInfoFactory<GfxDeviceInfo>::
media_driver/linux/gen8/ddi/media_sysinfo_g8.cpp:284:static bool bdwDevice162e = DeviceInfoFactory<GfxDeviceInfo>::
media_driver/linux/gen8/ddi/media_sysinfo_g8.cpp:288:static bool bdwDevice163b = DeviceInfoFactory<GfxDeviceInfo>::
media_driver/linux/gen8/ddi/media_sku_wa_g8.cpp:32://extern template class DeviceInfoFactory<GfxDeviceInfo>;
media_driver/linux/gen9/ddi/media_sysinfo_g9.cpp:33://extern template class DeviceInfoFactory<GfxDeviceInfo>;
media_driver/linux/gen9/ddi/media_sysinfo_g9.cpp:34:typedef DeviceInfoFactory<GfxDeviceInfo> base_fact;
media_driver/linux/gen9/ddi/media_sysinfo_g9.cpp:626:static bool sklDevice1902 = DeviceInfoFactory<GfxDeviceInfo>::
media_driver/linux/gen9/ddi/media_sysinfo_g9.cpp:629:static bool sklDevice1906 = DeviceInfoFactory<GfxDeviceInfo>::
media_driver/linux/gen9/ddi/media_sysinfo_g9.cpp:632:static bool sklDevice190a = DeviceInfoFactory<GfxDeviceInfo>::
media_driver/linux/gen9/ddi/media_sysinfo_g9.cpp:635:static bool sklDevice190b = DeviceInfoFactory<GfxDeviceInfo>::
media_driver/linux/gen9/ddi/media_sysinfo_g9.cpp:638:static bool sklDevice190e = DeviceInfoFactory<GfxDeviceInfo>::
media_driver/linux/gen9/ddi/media_sysinfo_g9.cpp:641:static bool sklDevice1913 = DeviceInfoFactory<GfxDeviceInfo>::
media_driver/linux/gen9/ddi/media_sysinfo_g9.cpp:644:static bool sklDevice1915 = DeviceInfoFactory<GfxDeviceInfo>::
media_driver/linux/gen9/ddi/media_sysinfo_g9.cpp:647:static bool sklDevice1917 = DeviceInfoFactory<GfxDeviceInfo>::
media_driver/linux/gen9/ddi/media_sysinfo_g9.cpp:650:static bool sklDevice1912 = DeviceInfoFactory<GfxDeviceInfo>::
media_driver/linux/gen9/ddi/media_sysinfo_g9.cpp:653:static bool sklDevice1916 = DeviceInfoFactory<GfxDeviceInfo>::
media_driver/linux/gen9/ddi/media_sysinfo_g9.cpp:656:static bool sklDevice191a = DeviceInfoFactory<GfxDeviceInfo>::
media_driver/linux/gen9/ddi/media_sysinfo_g9.cpp:659:static bool sklDevice191b = DeviceInfoFactory<GfxDeviceInfo>::
media_driver/linux/gen9/ddi/media_sysinfo_g9.cpp:662:static bool sklDevice191d = DeviceInfoFactory<GfxDeviceInfo>::
media_driver/linux/gen9/ddi/media_sysinfo_g9.cpp:665:static bool sklDevice191e = DeviceInfoFactory<GfxDeviceInfo>::
media_driver/linux/gen9/ddi/media_sysinfo_g9.cpp:668:static bool sklDevice1921 = DeviceInfoFactory<GfxDeviceInfo>::
media_driver/linux/gen9/ddi/media_sysinfo_g9.cpp:672:static bool sklDevice1923 = DeviceInfoFactory<GfxDeviceInfo>::
media_driver/linux/gen9/ddi/media_sysinfo_g9.cpp:675:static bool sklDevice192b = DeviceInfoFactory<GfxDeviceInfo>::
media_driver/linux/gen9/ddi/media_sysinfo_g9.cpp:678:static bool sklDevice1926 = DeviceInfoFactory<GfxDeviceInfo>::
media_driver/linux/gen9/ddi/media_sysinfo_g9.cpp:681:static bool sklDevice1927 = DeviceInfoFactory<GfxDeviceInfo>::
media_driver/linux/gen9/ddi/media_sysinfo_g9.cpp:684:static bool sklDevice192d = DeviceInfoFactory<GfxDeviceInfo>::
media_driver/linux/gen9/ddi/media_sysinfo_g9.cpp:688:static bool sklDevice192a = DeviceInfoFactory<GfxDeviceInfo>::
media_driver/linux/gen9/ddi/media_sysinfo_g9.cpp:691:static bool sklDevice1932 = DeviceInfoFactory<GfxDeviceInfo>::
media_driver/linux/gen9/ddi/media_sysinfo_g9.cpp:694:static bool sklDevice193a = DeviceInfoFactory<GfxDeviceInfo>::
media_driver/linux/gen9/ddi/media_sysinfo_g9.cpp:697:static bool sklDevice193b = DeviceInfoFactory<GfxDeviceInfo>::
media_driver/linux/gen9/ddi/media_sysinfo_g9.cpp:700:static bool sklDevice193d = DeviceInfoFactory<GfxDeviceInfo>::
media_driver/linux/gen9/ddi/media_sysinfo_g9.cpp:704:static bool bxtDevice1a84 = DeviceInfoFactory<GfxDeviceInfo>::
media_driver/linux/gen9/ddi/media_sysinfo_g9.cpp:707:static bool bxtDevice1a85 = DeviceInfoFactory<GfxDeviceInfo>::
media_driver/linux/gen9/ddi/media_sysinfo_g9.cpp:710:static bool bxtDevice5a84 = DeviceInfoFactory<GfxDeviceInfo>::
media_driver/linux/gen9/ddi/media_sysinfo_g9.cpp:713:static bool bxtDevice5a85 = DeviceInfoFactory<GfxDeviceInfo>::
media_driver/linux/gen9/ddi/media_sysinfo_g9.cpp:716:static bool glkDevice3a84 = DeviceInfoFactory<GfxDeviceInfo>::
media_driver/linux/gen9/ddi/media_sysinfo_g9.cpp:719:static bool glkDevice3a85 = DeviceInfoFactory<GfxDeviceInfo>::
media_driver/linux/gen9/ddi/media_sysinfo_g9.cpp:722:static bool kblDevice5906 = DeviceInfoFactory<GfxDeviceInfo>::
media_driver/linux/gen9/ddi/media_sysinfo_g9.cpp:725:static bool kblDevice5902 = DeviceInfoFactory<GfxDeviceInfo>::
media_driver/linux/gen9/ddi/media_sysinfo_g9.cpp:728:static bool kblDevice5908 = DeviceInfoFactory<GfxDeviceInfo>::
media_driver/linux/gen9/ddi/media_sysinfo_g9.cpp:731:static bool kblDevice590a = DeviceInfoFactory<GfxDeviceInfo>::
media_driver/linux/gen9/ddi/media_sysinfo_g9.cpp:734:static bool kblDevice590b = DeviceInfoFactory<GfxDeviceInfo>::
media_driver/linux/gen9/ddi/media_sysinfo_g9.cpp:737:static bool kblDevice590e = DeviceInfoFactory<GfxDeviceInfo>::
media_driver/linux/gen9/ddi/media_sysinfo_g9.cpp:740:static bool kblDevice5913 = DeviceInfoFactory<GfxDeviceInfo>::
media_driver/linux/gen9/ddi/media_sysinfo_g9.cpp:743:static bool kblDevice5915 = DeviceInfoFactory<GfxDeviceInfo>::
media_driver/linux/gen9/ddi/media_sysinfo_g9.cpp:746:static bool kblDevice5916 = DeviceInfoFactory<GfxDeviceInfo>::
media_driver/linux/gen9/ddi/media_sysinfo_g9.cpp:749:static bool kblDevice5917 = DeviceInfoFactory<GfxDeviceInfo>::
media_driver/linux/gen9/ddi/media_sysinfo_g9.cpp:752:static bool kblDevice5912 = DeviceInfoFactory<GfxDeviceInfo>::
media_driver/linux/gen9/ddi/media_sysinfo_g9.cpp:755:static bool kblDevice591e = DeviceInfoFactory<GfxDeviceInfo>::
media_driver/linux/gen9/ddi/media_sysinfo_g9.cpp:758:static bool kblDevice591a = DeviceInfoFactory<GfxDeviceInfo>::
media_driver/linux/gen9/ddi/media_sysinfo_g9.cpp:761:static bool kblDevice591b = DeviceInfoFactory<GfxDeviceInfo>::
media_driver/linux/gen9/ddi/media_sysinfo_g9.cpp:764:static bool kblDevice591d = DeviceInfoFactory<GfxDeviceInfo>::
media_driver/linux/gen9/ddi/media_sysinfo_g9.cpp:767:static bool kblDevice5921 = DeviceInfoFactory<GfxDeviceInfo>::
media_driver/linux/gen9/ddi/media_sysinfo_g9.cpp:770:static bool kblDevice5923 = DeviceInfoFactory<GfxDeviceInfo>::
media_driver/linux/gen9/ddi/media_sysinfo_g9.cpp:773:static bool kblDevice5926 = DeviceInfoFactory<GfxDeviceInfo>::
media_driver/linux/gen9/ddi/media_sysinfo_g9.cpp:776:static bool kblDevice5927 = DeviceInfoFactory<GfxDeviceInfo>::
media_driver/linux/gen9/ddi/media_sysinfo_g9.cpp:779:static bool kblDevice593b = DeviceInfoFactory<GfxDeviceInfo>::
media_driver/linux/gen9/ddi/media_sysinfo_g9.cpp:782:static bool kblDevice5932 = DeviceInfoFactory<GfxDeviceInfo>::
media_driver/linux/gen9/ddi/media_sysinfo_g9.cpp:785:static bool kblDevice592b = DeviceInfoFactory<GfxDeviceInfo>::
media_driver/linux/gen9/ddi/media_sysinfo_g9.cpp:788:static bool kblDevice592a = DeviceInfoFactory<GfxDeviceInfo>::
media_driver/linux/gen9/ddi/media_sysinfo_g9.cpp:791:static bool cflDevice3e93 = DeviceInfoFactory<GfxDeviceInfo>::
media_driver/linux/gen9/ddi/media_sysinfo_g9.cpp:794:static bool cflDevice3e90 = DeviceInfoFactory<GfxDeviceInfo>::
media_driver/linux/gen9/ddi/media_sysinfo_g9.cpp:797:static bool cflDevice3e92 = DeviceInfoFactory<GfxDeviceInfo>::
media_driver/linux/gen9/ddi/media_sysinfo_g9.cpp:800:static bool cflDevice3e94 = DeviceInfoFactory<GfxDeviceInfo>::
media_driver/linux/gen9/ddi/media_sysinfo_g9.cpp:803:static bool cflDevice3e91 = DeviceInfoFactory<GfxDeviceInfo>::
media_driver/linux/gen9/ddi/media_sysinfo_g9.cpp:806:static bool cflDevice3e96 = DeviceInfoFactory<GfxDeviceInfo>::
media_driver/linux/gen9/ddi/media_sysinfo_g9.cpp:809:static bool cflDevice3e9b = DeviceInfoFactory<GfxDeviceInfo>::
media_driver/linux/gen9/ddi/media_sysinfo_g9.cpp:813:static bool cflDevice3ea5 = DeviceInfoFactory<GfxDeviceInfo>::
media_driver/linux/gen9/ddi/media_sysinfo_g9.cpp:816:static bool cflDevice3ea6 = DeviceInfoFactory<GfxDeviceInfo>::
media_driver/linux/gen9/ddi/media_sysinfo_g9.cpp:819:static bool cflDevice3ea7 = DeviceInfoFactory<GfxDeviceInfo>::
media_driver/linux/gen9/ddi/media_sysinfo_g9.cpp:822:static bool cflDevice3ea8 = DeviceInfoFactory<GfxDeviceInfo>::
media_driver/linux/gen9/ddi/media_sku_wa_g9.cpp:32://extern template class DeviceInfoFactory<GfxDeviceInfo>;

Now can find **CNL (GEN10), BDW(GEN8), SKL(GEN9), GLK(GEN9), KBL(GEN9), CFL(GEN9), BXT (GEN9)**, is it media-driver support CFL/GLK/KBL now?

**Comment by XinfengZhang** [comment]
@mypopydev  no plan to support KBL as of now.

**Comment by oliver-sang** [comment]
@mypopydev can we close this?

**Comment by mypopydev** [comment]
@oliver-sang you can close this RFC
