### ISSUE TITLE
Add support for vulkan on older cpus intel

### ISSUE THREAD

**Issue by mathpfvr** [intel/media-driver#682]
I have Intel Celeron 3205U 1.5ghx on my notebook of Samsung and I used Linux Zorin OS 15, please add support for vulkan on older cpus Intel

**Comment by XinfengZhang** [comment]
linux media driver is pure UMD encode/decode/vpp driver,  suppose you want [libva ](https://github.com/intel/libva) support vulkan , right?

**Comment by eero-t** [comment]
Mathpfvr added ticket to libva, so I suppose this can be closed: https://github.com/intel/libva/issues/321

**Comment by XinfengZhang** [comment]
@mathpfvr are you expecting driver to implement some vulkan video api ?
