### ISSUE TITLE
[vp8 encode] maximum support 4k failed

### ISSUE THREAD

**Issue by zhuqingliang** [intel/media-driver#687]
description : 
  ffmpeg vp8 4k  encode failed ,shows hardware only support  32-1920 

reproduce step:
1.ffmpeg -hwaccel vaapi -vaapi_device /dev/dri/renderD128 -v verbose -f rawvideo -pix_fmt yuv420p -s:v 3840x2160 -i 4k_2013_3840x2160_I420.yuv -vf 'format=nv12,hwupload' -c:v vp8_vaapi -rc_mode CQP -g 30 -global_quality 28 -loop_filter_sharpness 0 -loop_filter_level 0 -vframes 10 -y test.ivf
2. error log:
Hardware does not support encoding at size 3840x2160 (constraints: width 32-1920 height 32-1920).

**Comment by wangyan-intel** [comment]
@zhuqingliang It should be duplicated with #565.
