### ISSUE TITLE
Noise reduction not working

### ISSUE THREAD

**Issue by shakeeb80** [intel/media-driver#689]
I want to use noise reduction filter (VAProcFilterNoiseReduction) using va api but it does not seems to be doing anything. Can anyone guide me what may be wrong ? Also what algoirthm does the noise reduction filter use ? Is it using spatial or temporal or both ? 

I am following the instructions mentioned in https://people.freedesktop.org/~gb/vaapi/vpp/group__api__vpp.html

Thanks

**Comment by FurongZhang** [comment]
May I know how you are using the noise filter? Can you try our sample code first? Thanks a lot in advance! 
Libva-Utils: https://github.com/intel/libva-utils
https://github.com/intel/libva-utils/blob/master/videoprocess/vppdenoise.cpp
