### ISSUE TITLE
reply VASurfaceAttribMemoryType to vaQuerySurfaceAttributes()

### ISSUE THREAD

**Issue by ceyusa** [intel/media-driver#698]
Other drivers, such as intel-vaapi-driver and amdgpu gallium, according to [vadumpcaps](https://github.com/fhvwy/vadumpcaps), reply when calling `vaQuerySurfaceAttributes()` the available `VASurfaceAttribMemoryType` to all the profile/entrypoints, but media-driver only replies it to the postprocessor profile,  not to the rest of the encoders and decoders.

**Comment by wangyan-intel** [comment]
@ceyusa I will check it. Thanks.

**Comment by wangyan-intel** [comment]
@ceyusa I have submitted #699 for fixing this issue. Thanks.
