### ISSUE TITLE
 VAEncMiscParameterBufferQualityLevel need to reset for AVC/HEVC when sequence parameters reset.

### ISSUE THREAD

**Issue by mypopydev** [intel/media-driver#7]
User need to reset  VAEncMiscParameterBufferQualityLevel after reset sequence parameters , otherwise iHD driver won't use the expected quality level for encoding.

BTW:  iHD driver uses a different quality level for AVC/HEVC when reset, AVC use 1, HEVC use 4. 

I don't think this action follow the VA-API Spec, and iHD follow a  counterintuitive way for Quality Level setting.

**Comment by xinfengz** [comment]
you mean, even there are a new sequence parameters, driver should always keep previous quality level setting until next quality level setting, right?   so , we should not set the default quality level in parsing sequence parameter function?

**Comment by mypopydev** [comment]
Yes, I think quality level will keep  unless user explicit change it, if user does not debug the driver, do you think any user know need to re-setting quality level when re-set sequence parameter? 

BTW: AVC/HEVC use a different default quality level value (1 for AVC, 4 for HEVC), I don't think this is a good idea from API view.

**Comment by xinfengz** [comment]
sure , will submit a PR to fix it . thanks
