### ISSUE TITLE
[ffmpeg_vaapi][hevc_lp_encode] encode file has garbage on ICL

### ISSUE THREAD

**Issue by zhuqingliang** [intel/media-driver#700]
description:
  the color have some error on hevc lowpower encode cbr/vbr mode

reproduce step:
1.ffmpeg -hwaccel vaapi -vaapi_device /dev/dri/renderD128 -v verbose -f rawvideo -pix_fmt yuv420p -s:v 352x288 -r:v 30 -i yuv/MOBILE_352x288_30_orig_01_352x288_I420.yuv -vf 'format=nv12,hwupload' -c:v hevc_vaapi -profile:v main -rc_mode CBR -g 30 -slices 1 -b:v 100k -maxrate 100k -low_power 1 -vframes 300 -y test.h265

2. observe
the color have some garbage, screen shot below 
![Capture](https://user-images.githubusercontent.com/29194447/62451186-56c65680-b7a0-11e9-9adb-8b572b469ec6.PNG)
![Capture2](https://user-images.githubusercontent.com/29194447/62451207-604fbe80-b7a0-11e9-9ffd-228857a3594e.PNG)

**Comment by wangyan-intel** [comment]
@zhuqingliang Could you share your video clip for debugging? Thanks.

**Comment by zhuqingliang** [comment]
@wangyan-intel  https://drive.google.com/file/d/1mnTYUS_0MMGT0az4MbihvIL_BmyGas-T/view?usp=sharing

**Comment by wangyan-intel** [comment]
This is encoding issue.

**Comment by Xiaogangli-intel** [comment]
@zhuqingliang This issue should be fixed in the latest driver? Could you have a try?
And please use this FFmpeg which has some fixes for VAAPI.
PS: Please run _git am patchset/*.patch_ before build.

**Comment by Xiaogangli-intel** [comment]
This issue has been fixed in the latest driver, so close it.
