### ISSUE TITLE
Build as static library

### ISSUE THREAD

**Issue by tmm1** [intel/media-driver#702]
I am working on some patches to enable building the driver as a static archive. Is there any interest in making this an officially supported build mode?

**Comment by XinfengZhang** [comment]
@tmm1 , what is the usage cases? why you need it as a static library, is it will be combined with libva?

**Comment by tmm1** [comment]
Yes to build with libva and ffmpeg as single binary deployment

**Comment by XinfengZhang** [comment]
We will not implement it.
