### ISSUE TITLE
xf86_drm_mock.c give a lot insignificance log message when build the driver.

### ISSUE THREAD

**Issue by mypopydev** [intel/media-driver#71]
xf86_drm_mock.c give a lot insignificance log message like "!!!This is libdrm mock drmIoctl, fd=xxx".

**Comment by oliver-sang** [comment]
this is fixed by https://github.com/intel/media-driver/commit/7c7eb2aaccdca81209db60ab0394f6c7a7ba4d3d

Thanks for reporting this!

**Comment by oliver-sang** [comment]
@mypopydev could we close this?

**Comment by mypopydev** [comment]
LGTM, you can close this issue, thanks the quick response.
