### ISSUE TITLE
cc1plus: warning: ‘-Werror=’ argument ‘-Werror=implicit-function-declaration’ is not valid for C++

### ISSUE THREAD

**Issue by sebastinas** [intel/media-driver#712]
Since GCC 9, the compiler emits the following warning:

```
cc1plus: warning: ‘-Werror=’ argument ‘-Werror=implicit-function-declaration’ is not valid for C++
```

The flags only makes sense for C code. Please remove it for the C++ bits and pieces.

**Comment by XinfengZhang** [comment]
@yanqings  @hanlong1 , could you help on it?

**Comment by rossburton** [comment]
Specifically, GCC 9.2 changed behaviour here.

**Comment by LocutusOfBorg** [comment]
patch here:
http://launchpadlibrarian.net/437767084/intel-media-driver-non-free_19.2.1+ds1-1ubuntu1_19.2.1+ds1-1ubuntu2.diff.gz

**Comment by XinfengZhang** [comment]
thanks @LocutusOfBorg , will refer the patch
