### ISSUE TITLE
build issue

### ISSUE THREAD

**Issue by waiter89** [intel/media-driver#713]
/home/surveil/intel-media/media-driver/media_driver/linux/common/ddi/media_libva.cpp: In function ‘int32_t DdiMedia_MediaFormatToOsFormat(DDI_MEDIA_FORMAT)’:
/home/surveil/intel-media/media-driver/media_driver/linux/common/ddi/media_libva.cpp:461:20: error: ‘VA_FOURCC_Y8’ was not declared in this scope
             return VA_FOURCC_Y8;
                    ^~~~~~~~~~~~
/home/surveil/intel-media/media-driver/media_driver/linux/common/ddi/media_libva.cpp:461:20: note: suggested alternative: ‘VA_FOURCC_Y800’
             return VA_FOURCC_Y8;
                    ^~~~~~~~~~~~

**Comment by XinfengZhang** [comment]
just file a but on libva https://github.com/intel/libva/issues/330
for this issue only---- you can update libva
