### ISSUE TITLE
[ffmpeg][low delay B][query][enhancement] add query support for prediction direction caps

### ISSUE THREAD

**Issue by fulinjie** [intel/media-driver#721]
Thanks to the help in libva and since PR for prediction direction caps report is merged:
https://github.com/intel/libva/commit/f094de317b4f498b57d47d8b0823a2a24cb125e1

we could now step further and seek for query support in media-driver.

**Comment by fulinjie** [comment]
Hi @XinfengZhang , is there any update for this?

**Comment by fulinjie** [comment]
link the pr:
https://github.com/intel/media-driver/pull/783

**Comment by XinfengZhang** [comment]
reopen it, because also need to change for HEVC
