### ISSUE TITLE
[Discussion] what should be added into next release

### ISSUE THREAD

**Issue by XinfengZhang** [intel/media-driver#735]
I open this issue to discuss next release --- Q4 release
which issue should be fixed in the Q4
which feature should be ready ??? ...
please help to add your comments and requirements. thanks

**Comment by chivakker** [comment]
As I am reading the pre-release notes, I'm seeing they are validated against non-released or pre-released tags for gmmlib and libva.  To try to keep consistency is it possible that pre-releases can be validated against actual tags instead of random sha's?

**Comment by XinfengZhang** [comment]
@Sherry-Lin

**Comment by XinfengZhang** [comment]
@chivakker  it should be a requirement to gmmlib and libva,  release process and tag cadence is not similar
