### ISSUE TITLE
conflict between different DOCs. 

### ISSUE THREAD

**Issue by xhaihao** [intel/media-driver#737]
According to https://github.com/intel/media-driver/blob/master/docs/media_features.md#hardwarepak--shadermedia-kernelvme-encoding  HEVC 8bit AYUV is supported by Hardware(PAK) + Shader(media kernel+VME) Encoding on ICL, however according to https://github.com/intel/media-driver/blob/master/README.md#decodingencoding-features, HEVC 8bit AYUV is only supported by Hardware Encoding, Low Power Encoding(VDEnc/Huc) on ICL, which one is right?

**Comment by Sherry-Lin** [comment]
Sorry for misleading. HEVC 8bit AYUV should be only supported in Low Power Encoding. We will correct the information. Thanks for your reminder.
