### ISSUE TITLE
JPEG encoder doesn't support AYUV input

### ISSUE THREAD

**Issue by xhaihao** [intel/media-driver#742]
According to https://github.com/intel/media-driver/blob/master/docs/media_features.md#supported-encoding-input-format-and-max-resolution, JPEG encoder supports AYUV input, however `DdiEncodeJpeg::ConvertMediaFormatToInputSurfaceFormat` doesn't convert AYUV to a valid internal format.

https://github.com/intel/media-driver/blob/cf6e2ca57cbd7b5c1aa743807d3a5cac8202cacb/media_driver/linux/common/codec/ddi/media_ddi_encode_jpeg.cpp#L582-L606

**Comment by XinfengZhang** [comment]
AYUV should be similar with RGB and 444P

**Comment by feiwan1** [comment]
> AYUV should be similar with RGB and 444P

Hi @XinfengZhang , so you will plan to add AYUV format in jpeg encode in media-driver?

**Comment by Xiaogangli-intel** [comment]
JPEG encoder doesn't support AYUV format. Feature table is updated in #1388.
