### ISSUE TITLE
DdiMediaBase::GetRenderTargetID cost 2% cpu time when we do single process multiple channel decoder

### ISSUE THREAD

**Issue by xuguangxin** [intel/media-driver#744]
If you use vtune to profile following command
`gst-launch-1.0 tee name = t filesrc location=1920x1080_2700frames.264 ! t. t. ! h264parse ! queue ! vaapih264dec ! "video/x-raw(memory:VASurface)" ! fpsdisplaysink video-sink=fakesink sync=false t. ! h264parse ! queue ! vaapih264dec ! "video/x-raw(memory:VASurface)" ! fpsdisplaysink video-sink=fakesink sync=false t. ! h264parse ! queue ! vaapih264dec ! "video/x-raw(memory:VASurface)" ! fpsdisplaysink video-sink=fakesink sync=false t. ! h264parse ! queue ! vaapih264dec ! "video/x-raw(memory:VASurface)" ! fpsdisplaysink video-sink=fakesink sync=false t. ! h264parse ! queue ! vaapih264dec ! "video/x-raw(memory:VASurface)" ! fpsdisplaysink video-sink=fakesink sync=false t. ! h264parse ! queue ! vaapih264dec ! "video/x-raw(memory:VASurface)" ! fpsdisplaysink video-sink=fakesink sync=false t. ! h264parse ! queue ! vaapih264dec ! "video/x-raw(memory:VASurface)" ! fpsdisplaysink video-sink=fakesink sync=false t. ! h264parse ! queue ! vaapih264dec ! "video/x-raw(memory:VASurface)" ! fpsdisplaysink video-sink=fakesink sync=false t. ! h264parse ! queue ! vaapih264dec ! "video/x-raw(memory:VASurface)" ! fpsdisplaysink video-sink=fakesink sync=false t. ! h264parse ! queue ! vaapih264dec ! "video/x-raw(memory:VASurface)" ! fpsdisplaysink video-sink=fakesink sync=false t. ! h264parse ! queue ! vaapih264dec ! "video/x-raw(memory:VASurface)" ! fpsdisplaysink video-sink=fakesink sync=false t. ! h264parse ! queue ! vaapih264dec ! "video/x-raw(memory:VASurface)" ! fpsdisplaysink video-sink=fakesink sync=false t. ! h264parse ! queue ! vaapih264dec ! "video/x-raw(memory:VASurface)" ! fpsdisplaysink video-sink=fakesink sync=false t. ! h264parse ! queue ! vaapih264dec ! "video/x-raw(memory:VASurface)" ! fpsdisplaysink video-sink=fakesink sync=false t. ! h264parse ! queue ! vaapih264dec ! "video/x-raw(memory:VASurface)" ! fpsdisplaysink video-sink=fakesink sync=false t. ! h264parse ! queue ! vaapih264dec ! "video/x-raw(memory:VASurface)" ! fpsdisplaysink video-sink=fakesink sync=false t. ! h264parse ! queue ! vaapih264dec ! "video/x-raw(memory:VASurface)" ! fpsdisplaysink video-sink=fakesink sync=false t. ! h264parse ! queue ! vaapih264dec ! "video/x-raw(memory:VASurface)" ! fpsdisplaysink video-sink=fakesink sync=false t. ! h264parse ! queue ! vaapih264dec ! "video/x-raw(memory:VASurface)" ! fpsdisplaysink video-sink=fakesink sync=false t. ! h264parse ! queue ! vaapih264dec ! "video/x-raw(memory:VASurface)" ! fpsdisplaysink video-sink=fakesink sync=false t. ! h264parse ! queue ! vaapih264dec ! "video/x-raw(memory:VASurface)" ! fpsdisplaysink video-sink=fakesink sync=false t. ! h264parse ! queue ! vaapih264dec ! "video/x-raw(memory:VASurface)" ! fpsdisplaysink video-sink=fakesink sync=false t. ! h264parse ! queue ! vaapih264dec ! "video/x-raw(memory:VASurface)" ! fpsdisplaysink video-sink=fakesink sync=false t. ! h264parse ! queue ! vaapih264dec ! "video/x-raw(memory:VASurface)" ! fpsdisplaysink video-sink=fakesink sync=false t. ! h264parse ! queue ! vaapih264dec ! "video/x-raw(memory:VASurface)" ! fpsdisplaysink video-sink=fakesink sync=false t. ! h264parse ! queue ! vaapih264dec ! "video/x-raw(memory:VASurface)" ! fpsdisplaysink video-sink=fakesink sync=false t. ! h264parse ! queue ! vaapih264dec ! "video/x-raw(memory:VASurface)" ! fpsdisplaysink video-sink=fakesink sync=false t. ! h264parse ! queue ! vaapih264dec ! "video/x-raw(memory:VASurface)" ! fpsdisplaysink video-sink=fakesink sync=false t. ! h264parse ! queue ! vaapih264dec ! "video/x-raw(memory:VASurface)" ! fpsdisplaysink video-sink=fakesink sync=false t. ! h264parse ! queue ! vaapih264dec ! "video/x-raw(memory:VASurface)" ! fpsdisplaysink video-sink=fakesink sync=false t. ! h264parse ! queue ! vaapih264dec ! "video/x-raw(memory:VASurface)" ! fpsdisplaysink video-sink=fakesink sync=false t. ! h264parse ! queue ! vaapih264dec ! "video/x-raw(memory:VASurface)" ! fpsdisplaysink video-sink=fakesink sync=false t. ! h264parse ! queue ! vaapih264dec ! "video/x-raw(memory:VASurface)" ! fpsdisplaysink video-sink=fakesink sync=false t. ! h264parse ! queue ! vaapih264dec ! "video/x-raw(memory:VASurface)" ! fpsdisplaysink video-sink=fakesink sync=false t. ! h264parse ! queue ! vaapih264dec ! "video/x-raw(memory:VASurface)" ! fpsdisplaysink video-sink=fakesink sync=false t. ! h264parse ! queue ! vaapih264dec ! "video/x-raw(memory:VASurface)" ! fpsdisplaysink video-sink=fakesink sync=false t. ! h264parse ! queue ! vaapih264dec ! "video/x-raw(memory:VASurface)" ! fpsdisplaysink video-sink=fakesink sync=false t. ! h264parse ! queue ! vaapih264dec ! "video/x-raw(memory:VASurface)" ! fpsdisplaysink video-sink=fakesink sync=false t. ! h264parse ! queue ! vaapih264dec ! "video/x-raw(memory:VASurface)" ! fpsdisplaysink video-sink=fakesink sync=false t. ! h264parse ! queue ! vaapih264dec ! "video/x-raw(memory:VASurface)" ! fpsdisplaysink video-sink=fakesink sync=false t. ! h264parse ! queue ! vaapih264dec ! "video/x-raw(memory:VASurface)" ! fpsdisplaysink video-sink=fakesink sync=false t. ! h264parse ! queue ! vaapih264dec ! "video/x-raw(memory:VASurface)" ! fpsdisplaysink video-sink=fakesink sync=false t. ! h264parse ! queue ! vaapih264dec ! "video/x-raw(memory:VASurface)" ! fpsdisplaysink video-sink=fakesink sync=false t. ! h264parse ! queue ! vaapih264dec ! "video/x-raw(memory:VASurface)" ! fpsdisplaysink video-sink=fakesink sync=false t. ! h264parse ! queue ! vaapih264dec ! "video/x-raw(memory:VASurface)" ! fpsdisplaysink video-sink=fakesink sync=false t. ! h264parse ! queue ! vaapih264dec ! "video/x-raw(memory:VASurface)" ! fpsdisplaysink video-sink=fakesink sync=false t. ! h264parse ! queue ! vaapih264dec ! "video/x-raw(memory:VASurface)" ! fpsdisplaysink video-sink=fakesink sync=false t. ! h264parse ! queue ! vaapih264dec ! "video/x-raw(memory:VASurface)" ! fpsdisplaysink video-sink=fakesink sync=false t. ! h264parse ! queue ! vaapih264dec ! "video/x-raw(memory:VASurface)" ! fpsdisplaysink video-sink=fakesink sync=false t. ! h264parse ! queue ! vaapih264dec ! "video/x-raw(memory:VASurface)" ! fpsdisplaysink video-sink=fakesink sync=false`

you will see DdiMediaBase::GetRenderTargetID cost about 2% cpu time.
![image](https://user-images.githubusercontent.com/6667546/66550735-99c5f100-eb78-11e9-883d-faaa04d55ec9.png)
This becuase gstreamer vaapi did not fill the entire reference list.

https://github.com/GStreamer/gstreamer-vaapi/blob/600aba57cfe91ea991c41f75f7ad347621ec4f5a/gst-libs/gst/vaapi/gstvaapidecoder_h264.c#L4171

But the driver will blindly fill entire reference list 

https://github.com/intel/media-driver/blob/cf6e2ca57cbd7b5c1aa743807d3a5cac8202cacb/media_driver/linux/common/codec/ddi/media_ddi_decode_avc.cpp#L116

Every surface id beyond num_ref_idx_l0_active_minus1  is invalid surface id. 
and DdiMediaBase::GetRenderTargetID will loop DDI_MEDIA_MAX_SURFACE_NUMBER_CONTEXT(127) times for an invalid id.
We support 2x32 reference frames for each slice. In the worst case, it will loop 2x32*127 time for each slice.
Please help change it.

**Comment by xuguangxin** [comment]
@XinfengZhang any eta for this?

**Comment by xuguangxin** [comment]
@XinfengZhang @wangyan42164, any feedback for this?
thanks

**Comment by wangyan-intel** [comment]
@xuguangxin Could you please try my PR: #986? Thanks

**Comment by xuguangxin** [comment]
@wangyan-intel In which condition we will return here?
https://github.com/intel/media-driver/blob/adc23261d4a4f60d6e113959cdb3acbed055fde9/media_driver/linux/common/codec/ddi/media_ddi_decode_avc.cpp#L832
In this condition,  we still loop the entire array, will it have problem?

thanks

**Comment by wangyan-intel** [comment]
> @wangyan-intel In which condition we will return here?
> https://github.com/intel/media-driver/blob/adc23261d4a4f60d6e113959cdb3acbed055fde9/media_driver/linux/common/codec/ddi/media_ddi_decode_avc.cpp#L832
> 
> 
> In this condition, we still loop the entire array, will it have problem?
> thanks

@xuguangxin IMHO, we don't know how many frames in avcPicParams->RefFrameList. So we have to search all elements for this slice. Do you think so?
https://github.com/intel/media-driver/blob/adc23261d4a4f60d6e113959cdb3acbed055fde9/media_driver/linux/common/codec/ddi/media_ddi_decode_avc.cpp#L127
https://github.com/intel/media-driver/blob/adc23261d4a4f60d6e113959cdb3acbed055fde9/media_driver/linux/common/codec/ddi/media_ddi_decode_avc.cpp#L141

**Comment by xuguangxin** [comment]
Array is not good for search. 
Is it possible use some std::map instead of Array.
else if platform supports compressed memory, we still have this high overhead.

**Comment by wangyan42164** [comment]
@xuguangxin 
Yes. It could be changed tree structure like std:map for searching. But it need more effort and test for avoid regression.

**Comment by xuguangxin** [comment]
@wangyan42164 let us merge your patch firstly. then we will measure the performance at TGL, create a new issues if we still see the problem.
thanks

**Comment by wangyan-intel** [comment]
@xuguangxin Sure. I have added verifying flag for #986.
