### ISSUE TITLE
userptr: can't create YUY2 surface

### ISSUE THREAD

**Issue by dvrogozh** [intel/media-driver#747]
As noted here:
https://github.com/intel/gmmlib/blob/master/Source/GmmLib/Texture/GmmGen9Texture.cpp#L869
gmmlib requires additional row + 16 bytes to be allocated after the plane for the packed YUV formats. The problem is that media driver does not have a way (no gmmlib uAPI) to say to gmmlib that there is additional space allocated after the plane. I.e. gmmlib has only BaseWidth and BaseHeight parameters to operate with having not ROI parameters which could specify region of valid data.

For example, creating 256x256 surface via userptr, the following information will go to gmmlib:
```
gmmParams.Type=2
gmmParams.Format=222
gmmParams.Flags.Gpu.MMC=0
gmmParams.Flags.Gpu.CCS=0
gmmParams.Flags.Gpu.UnifiedAuxSurface=0
gmmParams.Flags.Gpu.RenderTarget=0
gmmParams.Flags.Info.ExistingSysMem=1
gmmParams.Flags.Info.MediaCompressed=0
gmmParams.Flags.Info.TiledX=0
gmmParams.Flags.Info.LocalOnly=0
gmmParams.CpTag=0
gmmParams.BaseWidth=256
gmmParams.BaseHeight=264
gmmParams.OverridePitch=0
gmmParams.Depth=0
gmmParams.MaxLod=0
gmmParams.ArraySize=1
gmmParams.BaseAlignment=0
gmmParams.RotateInfo=0
gmmParams.pExistingSysMem=139830959534080
gmmParams.ExistingSysMemSize=135168
gmmParams.MaximumRenamingListLength=0
gmmParams.NoGfxMemory=0
gmmParams.pPreallocatedResInfo=(nil)
gmmParams.pExistingSysMem=<ptr>
```

`BaseHeigh=264` comes from the userptr requirement for the overall size to be page aligned. So, there is 8 padding rows available, but there is no way to say this to gmmlib.

Reported to gmmlib: intel/gmmlib#56

**Comment by XinfengZhang** [comment]
#169
