### ISSUE TITLE
Intel media driver installation Error

### ISSUE THREAD

**Issue by itssivashankar** [intel/media-driver#780]
As now i am working on ffmpeg transcoder process.we are trying to use intel quick sync with ffmpeg for hardware acceleration and to optimize cpu usage.
      I followed this documentation 
            https://github.com/intel/media-driver/tree/master
      As of now i had problem to init iHD driver in ubuntu 19.04.so kindly guide me to fix this problem.
![Screenshot from 2019-11-18 22-06-25](https://user-images.githubusercontent.com/40492271/69157026-56ad5500-0b0a-11ea-8335-08b0cb628f02.png)

**Comment by dmitryermilov** [comment]
It refers to incorrect driver name (and possibly path). 
Please do:
export LIBVA_DRIVER_NAME="iHD"
export LIBVA_DRIVERS_PATH="/path/to/directory/with/iHD_drv_video.so"

**Comment by dmitryermilov** [comment]
@itssivashankar , did it help?
