### ISSUE TITLE
Potential leak of memory pointed to by 'adjacencyListBegin'

### ISSUE THREAD

**Issue by QiAnXinCodeSafe** [intel/media-driver#782]
Memory is allocated here
https://github.com/intel/media-driver/blob/8a8b8ae263a04cb5dd384d4625215cf296d2cc59/media_driver/agnostic/common/heap_manager/memory_block_manager.cpp#L250

but at the end of function, the memory is not freed.

**Comment by XinfengZhang** [comment]
it is freed here: https://github.com/intel/media-driver/blob/8a8b8ae263a04cb5dd384d4625215cf296d2cc59/media_driver/agnostic/common/heap_manager/memory_block_manager.h#L223
