### ISSUE TITLE
[Doc] HEVC 8K encode failed on Gen10- platform iHD

### ISSUE THREAD

**Issue by FocusLuo** [intel/media-driver#789]
HEVC 8K encode failed on Gen10- platform, need to update the description on the doc
https://github.com/intel/media-driver/blob/master/docs/media_features.md

Codec | Type | BDW | SKL | BXT/APL | KBL | CFL | WHL | CML
-- | -- | -- | -- | -- | -- | -- | -- | --

HEVC 8bit | Input |   | NV12 | NV12 | NV12 | NV12 | NV12 | NV12 | 
-- | -- | -- | -- | -- | -- | -- | -- | -- | --
  | Max Res. |   | 8k | 8k | 8k | 8k | 8k | 8k |

**Comment by XinfengZhang** [comment]
let's reconsider this question , like:  whether still need check Gen10
