### ISSUE TITLE
Add DRI3 Support

### ISSUE THREAD

**Issue by Master0ne** [intel/media-driver#790]
> @akarshanbiswas said:
> For now you need to ask intel vaapi driver devs to add support for dri3. They had a PR but it is closed due to inactivity unfortunately.

I am trying to get HW video acceleration to work with [(ungoogled-)Chrom(ium) in GNOME on Wayland](https://github.com/jstkdng/ungoogled-chromium-archlinux/issues/6), which is what the (ungoogled-)chromium-ozone build is destined for, but it has been mentioned by someone with more insight that it may have to do with missing DRI3 support by the Intel driver.

I apologize for this unprofessional comment, I'm not a developer or programmer, but just a user.

CC: @jstkdng

**Comment by akarshanbiswas** [comment]
Refer: https://github.com/intel/intel-vaapi-driver/pull/369

Apparently this PR was closed due to inactivity and I'm not sure if iHD driver has dri3 support or not to work through xWayland.

**Comment by XinfengZhang** [comment]
media driver will not add support for display, so , no wayland support now. suppose DRI3 support should be added in vaapi level , such as https://github.com/intel/libva/pull/180?

**Comment by akarshanbiswas** [comment]
> media driver will not add support for display, so , no wayland support now. suppose DRI3 support should be added in vaapi level , such as [intel/libva#180](https://github.com/intel/libva/pull/180)?

Interesting. I wonder why that PR is closed as well. :/

**Comment by uartie** [comment]
> Interesting. I wonder why that PR is closed as well. :/

Those patches (intel/libva#180 and intel/intel-vaapi-driver#369) just need someone to take new ownership (i.e resubmit and follow through).  Volunteers?

**Comment by akarshanbiswas** [comment]
@uartie If no one takes it, I can try if you want(rebase and resubmit). However I don't know how everything works in libva so I will follow blindly.

Also there is an existing problem of libva unable to initialize the driver when run through xwayland if LIBVA_DRIVER_NAME is not set. I hope https://github.com/intel/libva/pull/180 will solve that as well.

**Comment by Jexu** [comment]
@XinfengZhang does it support from libva https://github.com/intel/libva/pull/614?

**Comment by XinfengZhang** [comment]
yes, we could close the PR , thanks 
new libva 2.17.0 support DRI3.
