### ISSUE TITLE
ICL PCI device IDs 0x8A70, 0x8A54 are missing

### ISSUE THREAD

**Issue by dvrogozh** [intel/media-driver#798]
Looks like we miss ICL PCI device IDs 0x8A70, 0x8A54, see around:
https://github.com/intel/media-driver/blob/cdc808429e6aa5ece91935d20eccba2397db5a62/media_driver/linux/gen11/ddi/media_sysinfo_g11.cpp#L379

They are known to the kernel:
* https://git.kernel.org/pub/scm/linux/kernel/git/stable/linux.git/tree/include/drm/i915_pciids.h?h=v5.4.2#n573
* https://git.kernel.org/pub/scm/linux/kernel/git/stable/linux.git/tree/include/drm/i915_pciids.h?h=v5.4.2#n575

**Comment by XinfengZhang** [comment]
will add 8A54, no media usage with 8A70

**Comment by dvrogozh** [comment]
8A70: fair enough. ok.

**Comment by XinfengZhang** [comment]
fixed by dfdffc0fee2b29071c48d674a6d61acc8765d438
