### ISSUE TITLE
CFL PCI device ID 0x87CA, 0x87C0, 0x591C, 0x9bc6, 0x9be6 are missing

### ISSUE THREAD

**Issue by dvrogozh** [intel/media-driver#799]
See:
* https://git.kernel.org/pub/scm/linux/kernel/git/stable/linux.git/tree/include/drm/i915_pciids.h?h=v5.4.2#n575
* https://git.kernel.org/pub/scm/linux/kernel/git/stable/linux.git/tree/include/drm/i915_pciids.h?h=v5.4.2#n439

**Comment by XinfengZhang** [comment]
these did is AML and CML, will add these

**Comment by XinfengZhang** [comment]
fixed by dfdffc0fee2b29071c48d674a6d61acc8765d438
