### ISSUE TITLE
HEVC ENC need to setting VA_RC_MB

### ISSUE THREAD

**Issue by mypopydev** [intel/media-driver#8]
User has to set VA_RC_MB when using VA_RC_CBR or VA_RC_VBR in HEVC ENC, but AVC encoding does not need to setting  VA_RC_MB for CBR/VBR mode.

**Comment by xinfengz** [comment]
MBBRC should come from mb_rate_control, and driver should only set VA_RC_CBR or VBR ---- in the structure VAEncMiscParameterTypeRateControl.  so driver only need to check VA_RC_CBR | m_encodeCtx->uiRCMethod
