### ISSUE TITLE
BDW device IDs 0x1636, 0x163B, 0x163E, 0x1632, 0x163A, 0x163D are missing

### ISSUE THREAD

**Issue by dvrogozh** [intel/media-driver#800]
See:
https://git.kernel.org/pub/scm/linux/kernel/git/stable/linux.git/tree/include/drm/i915_pciids.h?h=v5.4.2#n307

**Comment by XinfengZhang** [comment]
need to check whether these DID is valid

**Comment by XinfengZhang** [comment]
these DID should be spare.
