### ISSUE TITLE
16K support HEVC  low-power

### ISSUE THREAD

**Issue by alexelizarov** [intel/media-driver#809]
For HEVC low-power driver reports MaxPicWidth=16K and MaxPicHeight=16K but in fact only 8K is supported

**Comment by Xiaogangli-intel** [comment]
@alexelizarov HEVC low-power support 16K x 12K, please check the latest caps.

**Comment by alexelizarov** [comment]
Caps were checked. Yes, 16Kx12K reported. Looks like it valid caps.
