### ISSUE TITLE
[Encode][mb_rate_control] different behavior between VMEPAK and VDENC when setting to default

### ISSUE THREAD

**Issue by fulinjie** [intel/media-driver#824]
Could be verified using ffmpeg vaapi:

ffmpeg -hwaccel vaapi -vaapi_device /dev/dri/renderD128 -v verbose -r:v 30 -f rawvideo -s:v 352x288 -pix_fmt yuv420p -i MOBILE_352x288_30_orig_01_352x288_I420.yuv -vf format=nv12,hwupload -c:v hevc_vaapi -profile:v main -low_power 1 -b:v 100k -maxrate 100k -vframes 300 -y vaapi_lp.h265

If setting mb_rate_control = 0(default) :

In VMEPAK, the mb_rate_control will be disabled in driver. 

In VDENC, the mb_rate_control will be enabled in driver.

This affects the encoding quality.

**Comment by Xiaogangli-intel** [comment]
Please provide the platform information, thank you.

**Comment by XinfengZhang** [comment]
@Xiaogang-Li , lets check it on TGL, if no such issue, we could close it

**Comment by Xiaogangli-intel** [comment]
Close it, there's no such issue now.
