### ISSUE TITLE
Please provide hardware and version information in vendor string

### ISSUE THREAD

**Issue by fhvwy** [intel/media-driver#834]
Compare returns from vaQueryVendorString():

i965:
```Intel i965 driver for Intel(R) Coffee Lake - 2.4.0.pre1 (2.3.0-26-gc6c7cb5)```
Mesa:
```Mesa Gallium driver 19.3.3 for AMD Radeon (TM) RX 460 Graphics (POLARIS11, DRM 3.27.0, 4.19.0-2-amd64, LLVM 9.0.1)```
iHD:
```Intel iHD driver - 1.0.0```

This gets logged by user programs like ffmpeg in order to help developers to know exactly what software versions on what hardware is being used.  If would be very helpful if the iHD driver could provide a similar level of information to what the other drivers do.

**Comment by XinfengZhang** [comment]
agree!, we need a controllable, progressive, readable string to represent the version , will propose one to discuss. thanks a lot.
