### ISSUE TITLE
TGL: The display image is green with NV12 format

### ISSUE THREAD

**Issue by VUNNYSODHI** [intel/media-driver#843]
ENV:

- Media SDK and Samples: https://github.com/Intel-Media-SDK/MediaSDK/releases/tag/intel-mediasdk-19.4.0
- Driver: https://github.com/intel/media-driver/releases/tag/intel-media-19.4.0r
- Gmmlib: https://github.com/intel/gmmlib/releases/tag/intel-gmmlib-19.4.1
- libva: https://github.com/intel/libva/releases/tag/2.6.0

The display image is green when ran:

$GST_GL_PLATFORM=egl gst-launch-1.0 videotestsrc ! video/x-raw,format=NV12,width=1920,height=1080 ! msdkvpp ! 'video/x-raw(memory:DMABuf),format=NV12' ! glimagesink

Output:
![Green-Screen](https://user-images.githubusercontent.com/47618819/74515771-31ce4f80-4f4a-11ea-8f76-a15b358428f4.png)

**Comment by xhaihao** [comment]
I can reproduce this issue against the latest media driver (commit ba5db01) by using sample_vpp from https://github.com/Intel-Media-SDK/MediaSDK/ (commit 7802ba5) @XinfengZhang @FurongZhang

**Comment by xhaihao** [comment]
sample_vpp command:
$> sample_vpp -vaapi  -scc yuy2 -sw 1920 -sh 1080 -dcc nv12 -i input.yuv -o output.yuv

**Comment by FurongZhang** [comment]
@xhaihao  Do you know if this is a media driver regression?

**Comment by VUNNYSODHI** [comment]
Hi @FurongZhang, 
Its not regression, using "GST_GL_PLATFORM=egl gst-launch-1.0 videotestsrc ! video/x-raw,format=NV12,width=1920,height=1080 ! msdkvpp ! 'video/x-raw(memory:DMABuf),format=NV12' ! glimagesink" 
Corruption is seen on ICL platform also

**Comment by Jister** [comment]
Hi @VUNNYSODHI , could you help to dump VP HLT log and VP input/output surface according to https://github.com/intel/media-driver/wiki/Video-Processing-Debug-Tool ? Thanks very much.

**Comment by VUNNYSODHI** [comment]
Hi @Jister,
Attached dump on running with **GST_GL_PLATFORM=egl gst-launch-1.0 videotestsrc num-buffers=10 ! video/x-raw,format=NV12,width=1920,height=1080 ! msdkvpp ! 'video/x-raw(memory:DMABuf),format=NV12' ! glimagesink**
HLT logs [HLT-logs.txt](https://github.com/intel/media-driver/files/4244044/HLT-logs.txt) 
and VP dump  [vp_dump.tar.gz](https://github.com/intel/media-driver/files/4244045/vp_dump.tar.gz)

**Comment by Jister** [comment]
Hi @VUNNYSODHI , thanks for your dumps. As I check the driver dumps, the driver output looks correct, not show green as you described. So i think media driver should have no issue, I suppose it might be a midware issue.

**Comment by VUNNYSODHI** [comment]
Hi @Jister, if media driver dumps looks ok, then can we say gstreamer-vaapi parameters also correct?
Can we suspect on msdkvpp for Green color what shown on output surface?

**Comment by Jister** [comment]
Hi, @VUNNYSODHI , yes, suppose to be a msdkvpp issue.

**Comment by VUNNYSODHI** [comment]
Hi @Jister,
Green corruption seen with "sample_vpp -vaapi -scc yuy2 -sw 1920 -sh 1080 -dcc nv12 -i input.yuv -o output.yuv"

**Comment by xhaihao** [comment]
@Jister @FurongZhang @VUNNYSODHI @XinfengZhang 

It seems there are two different issues:

* The output of VPP is wrong, which can be reproduced by `sample_vpp -vaapi -scc yuy2 -sw 1920 -sh 1080 -dcc nv12 -i input.yuv -o output.yuv`.  With latest master HEAD (commit 7857d6bea214b755d610c1a478d4e1e23da31cdb), the output quality is better than before but I still see a black line at the bottom. In the past (commit ba5db0187f6017c9ed029b5fa5e257ff2f2bb045), I saw corrupted output.  I don't see the black line on ICL. 

* A video surface can not be shared between media driver and iris driver on TGL.  You will see an assertion failure with debug version of iris driver when running the command below:

` $> GST_GL_PLATFORM=egl gst-launch-1.0 videotestsrc ! video/x-raw,format=NV12,width=1920,height=1080 ! msdkvpp ! 'video/x-raw(memory:DMABuf),format=NV12' ! glimagesink ` 

> gst-launch-1.0: ../../mesa/src/gallium/drivers/iris/iris_resource.c:1030: iris_resource_from_handle: Assertion `isl_surf_created_successfully' failed.

This assertion failure indicates iris failed to create a surface from the handle shared from media driver. 

You will see green display image with release version of iris driver when running the above command on TGL. (assert() is ignored in release version, so the command can run)

This command works well on ICL even if I use iris driver for ICL.

**Comment by VUNNYSODHI** [comment]
Thanks @xhaihao for the update, even on my side with debug version of mesa i see same assertion error with gstreamer command and it fails to render anything.
**gst-launch-1.0: ../src/gallium/drivers/iris/iris_resource.c:1030: iris_resource_from_handle: Assertion `isl_surf_created_successfully' failed.
Aborted (core dumped)**
Could it be GEN12 iris specific issue for surface creation?

**Comment by xhaihao** [comment]
@VUNNYSODHI,  for the 2nd issue, I think it is a GEN12 specific issue for buffer sharing between media driver and iris driver.

**Comment by Jister** [comment]
@VUNNYSODHI can you help to debug into mesa driver to find the reason why surface creation failed? I also tried to reproduce the issue, i can see the corrupted output, but not green output, i synced with @xhaihao ,  seems  DMAbuf doesn't take effect,.
![image](https://user-images.githubusercontent.com/10471991/75680882-71789380-5ccd-11ea-8796-ceba49588e13.png)

**Comment by Jister** [comment]
@VUNNYSODHI @xhaihao I submit a PR for black line issue, please try #871

**Comment by xhaihao** [comment]
@Jister #871 fixed the black line issue.
