### ISSUE TITLE
[HDR][H2S] The input metadata doesn't work when doing tone-mapping

### ISSUE THREAD

**Issue by sunxinpeng** [intel/media-driver#849]
Whatever the metadata of input stream I change, the tone-mapping pipeline(HDR to SDR) always get the same ouput file(same md5 value).

**Comment by FurongZhang** [comment]
I am checking that.

**Comment by FurongZhang** [comment]
@sunxinpeng It is expected. The final output of H2S is SDR content. Hence, for all the SDR output, they should be same regardless of Input Image Luminance!

**Comment by sunxinpeng** [comment]
> @sunxinpeng It is expected. The final output of H2S is SDR content. Hence, for all the SDR output, they should be same regardless of Input Image Luminance!

@xhaihao Hi, haihao, could you help to check with this?

**Comment by FurongZhang** [comment]
The behavior is expected, hence I close the issue. Please reopen and comment it if any concern. Thanks a lot in advance!
