### ISSUE TITLE
tone-mapping doesn't work well on ICL

### ISSUE THREAD

**Issue by sunxinpeng** [intel/media-driver#861]
The tone-mapping pipeline can not work well on ICL.

From gstreamer-vaapi side, when performing tone mapping to sRGB output color standard, the VPP pipeline fails.  For bt709 or bt2020-10 output color standard, the YUV channels are all messed up (greenish tone).

From ffmpeg-vaapi side, when performing tone mapping on ICL, driver will return error message like: "Illegal Hdr cases on unsupported m_Platform, turn off HDR." and the pipeline fails, too. The related code in driver is as following:
```
if ((pRenderPassData->bHdrNeeded) && (!MEDIA_IS_SKU(m_pSkuTable, FtrHDR)))
    {
        eStatus = MOS_STATUS_SUCCESS;
        VPHAL_RENDER_ASSERTMESSAGE("Illegal Hdr cases on unsupported m_Platform, turn off HDR.");
        pRenderPassData->bHdrNeeded = false;
}
```
MEDIA_IS_SKU returns false on my ICL but returns true on my CFL.

**Comment by FurongZhang** [comment]
I will check that as soon as possible.

**Comment by uartie** [comment]
@FurongZhang Ping.  Any update?

**Comment by FurongZhang** [comment]
Fixed.
