### ISSUE TITLE
Minor README.md issues

### ISSUE THREAD

**Issue by eero-t** [intel/media-driver#864]
* Prerequisites: openbox?  (*)
* "Video Processing Features" section has few items marked with *, but there's no explanation on what * indicates
* "Please, refer to i915 kernel mode driver documentation to learn how to enable it" => kernel command line option "i915.enable_guc=2" for HuC loading can be set e.g. by doing `echo "options i915 enable_guc=2" > /etc/modprobe.d/i915.conf` (as root)
* TGL bug link is nowadays: https://gitlab.freedesktop.org/drm/intel/issues/643

(*) I use Ubuntu 19.10 container to build git versions of libdrm, libva, gmmlib & media-driver. Deps I use are:
autoconf automake libtool build-essential pkg-config cmake meson ninja-build valgrind git ca-certificates libpciaccess-dev

* libdrm is needed by libva
* ninja is to have faster make
* ca-certificates is needed for Git HTTPS access
* valgrind (headers) are there just to avoid lots of error being reported when valgrinding the resulting libraries

**Comment by XinfengZhang** [comment]
* libva already is dependency, and libdrm is dependency of libva, valgrind headers should be added to avoid noise, but need support in code and should related with #715 
* already was resolved https://github.com/intel/media-driver#video-processing-features
* fixed by #1007.
* it is closed.
