### ISSUE TITLE
Werror issue on fedora 

### ISSUE THREAD

**Issue by kwizart** [intel/media-driver#870]
Here a Warning turned into when building on fedora.

> 
> CMakeFiles/iHD_drv_video_OBJ.dir/linux/common/os/i915/xf86drm.c.o -c /builddir/build/BUILD/media-driver-intel-media-19.4.0/media_driver/linux/common/os/i915/xf86drm.c
> /builddir/build/BUILD/media-driver-intel-media-19.4.0/media_driver/linux/common/os/i915/xf86drm.c: In function 'int drmOpenByBusid(const char*, int)':
> /builddir/build/BUILD/media-driver-intel-media-19.4.0/media_driver/linux/common/os/i915/xf86drm.c:606:15: error: '%s' directive argument is null [-Werror=format-overflow=]
>   606 |         drmMsg("drmOpenByBusid: drmGetBusid reports %s\n", buf);
>       |         ~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
> cc1plus: all warnings being treated as errors

**Comment by dvrogozh** [comment]
We did not see this one building with gcc-9.2.1. Are you using gcc-10 which is under development? (I think I saw that in your logs)

**Comment by dvrogozh** [comment]
w/ self built gcc-10 (head of gcc tree) I see this:
```
/opt/intel/git/media-driver/media_driver/linux/ult/libdrm_mock/xf86drm_mock.c: In function 'int drmOpenByBusid(const char*, int)':
/opt/intel/git/media-driver/media_driver/linux/ult/libdrm_mock/xf86drm_mock.c:815:15: warning: '%s' directive argument is null [-Wformat-overflow=]
  815 |         drmMsg("drmOpenByBusid: drmGetBusid reports %s\n", buf);
      |         ~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
...
/opt/intel/git/media-driver/media_driver/linux/common/os/i915/xf86drm.c: In function 'int drmOpenByBusid(const char*, int)':
/opt/intel/git/media-driver/media_driver/linux/common/os/i915/xf86drm.c:606:15: error: '%s' directive argument is null [-Werror=format-overflow=]
  606 |         drmMsg("drmOpenByBusid: drmGetBusid reports %s\n", buf);
      |         ~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
```
