### ISSUE TITLE
[issuse of vpping on x86 whiskey platform]scaling one frame of nv12 format to yuyv display format memory. If the width and height of the display is relatively small, the display memory splash screen will appear

### ISSUE THREAD

**Issue by PiperWei** [intel/media-driver#874]
Zoom one frame of nv12 data to yuyv display memory. If the width and height of the display is relatively small, the display memory splash screen will appear

Who has encountered this problem？ and how to Solve？ thanks

**Comment by PiperWei** [comment]
Who has encountered this problem？ and how to Solve？ thanks

**Comment by joojler** [comment]
which version of driver are you using? Is your problem similar to attached picture? I'm put a  1080p NV12 frame to a display with YUYV and scaling down size such as 200x200. beside the 200x200 area, other places in the display buffer is full of garbege. 
![230497700](https://user-images.githubusercontent.com/3134283/76816631-acd1a100-683b-11ea-8cb3-6805025ef94e.jpg)

**Comment by Jister** [comment]
Dst rectangle area is correct, but background is garbage, seems colorfill is not done. App should set the background color parameter, i.e. output_background_color in VAProcPipelineParameterBuffer, otherwise, driver won’t fill the background. Could you check whether app set the output_background_color parameter? Thanks

**Comment by FurongZhang** [comment]
@PiperWei  Any progress on this? Please set  output_background_color in VAProcPipelineParameterBuffer as @Jister mentioned in the above message.

**Comment by FurongZhang** [comment]
Pending on @PiperWei feedback.

**Comment by joojler** [comment]
this issue has been solved by providing the background color to do the color fill of the surface, otherwise random data will be there.
