### ISSUE TITLE
vaInitialize failed with error code -1 (unknown libva error),exit

### ISSUE THREAD

**Issue by WhyDoWeWonder** [intel/media-driver#878]
I'm running on Arch Linux with a Core i7-9850H. I've set $LIBVA_DRIVER_NAME to iHD but hardware acceleration isn't working and vainfo returns `vaInitialize failed with error code -1 (unknown libva error),exit`

**Comment by FurongZhang** [comment]
Can you provide more information about this? It is so rough that I can not have the useful information.

**Comment by FurongZhang** [comment]
And the below wiki page is for your information: https://github.com/intel/media-driver/wiki/How-to-build-and-use-media-driver%3F.
Except this, please also pay attention to the version of libva and iHD driver(the version for both of them needs to be consistent).

**Comment by FurongZhang** [comment]
@WhyDoWeWonder  Do you still see the issues?

**Comment by FurongZhang** [comment]
@WhyDoWeWonder May I know if your issues are resolved or not?

**Comment by FurongZhang** [comment]
It has been 2 weeks. I did not get any response from the bug submitter. Hence, I will close the issue. Please feel free to reopen it if you still see the issue, thanks a lot in advance!
