### ISSUE TITLE
Ref list value is not correct on ICELake

### ISSUE THREAD

**Issue by HeJunyan** [intel/media-driver#880]
On ICElake VDEnc, VAConfigAttribEncMaxRefFrames query return ref0 is 3 and ref1 is 0. So, B frame is not supported. But the low-delay-b is required on this entrypoint, which just converts P to B. So we should support B with a valid ref list1 and then can support low-delay-b.

**Comment by XinfengZhang** [comment]
it is a capability report issue, so I transferred it to media_driver

**Comment by Xiaogangli-intel** [comment]
So you are asking if we support low-delay-b on ICL VDEnc, right?

**Comment by XinfengZhang** [comment]
@HeJunyan , could you have a try #1009
