### ISSUE TITLE
[TGL] GPU hang on hevc SCC decoder

### ISSUE THREAD

**Issue by HeJunyan** [intel/media-driver#894]
GPU get hang when run MSDK cmd:
sample_decode h265 -i Bipred_8by8_A_Qualcomm_2.bit -o scc_out.yuv
It's a HEVC SCC main stream.

**Comment by wangyan-intel** [comment]
@HeJunyan This is MSDK issue and has been fixed. Please try the latest MSDK.

**Comment by HeJunyan** [comment]
It's a random hang, you need to run it several times. And once hang, never come back

**Comment by XinfengZhang** [comment]
@wangyan-intel  , any update?

**Comment by wangyan-intel** [comment]
@HeJunyan 
I checked it with the latest iHD driver. The issue is gone. Could you please double check it?
Thanks.

**Comment by HeJunyan** [comment]
I checked and not hang now. If you can not find the root cause, we can reopen it when we find it again.

**Comment by wangyan-intel** [comment]
I think some SCC decoding patches fix of iHD driver this issue recently.
