### ISSUE TITLE
vaQuerySurfaceAttributes doesn't support ENC

### ISSUE THREAD

**Issue by mypopydev** [intel/media-driver#9]
vaQuerySurfaceAttributes support DEC and VPP, but doesn't support ENC

**Comment by xinfengz** [comment]
yes, not implemented for encoder, I wonder whether it is  "MUST SUPPORT"  , thanks

**Comment by mypopydev** [comment]
If user want to query ENC some information (e,g,  input pixel format, max size ... ) ,  vaQuerySurfaceAttributes is the only interface for this type query, and if ENC change some thing (e,g, maybe support YUV422 in feature， change the max size from 4K to 16K...), no other way to query the ENC, so I think it is "MUST SUPPORT".

**Comment by xinfengz** [comment]
input pixel format can be covered by VAConfigAttribRTFormat, max encode resolution can be supported by VAConfigAttribMaxPictureWidth VAConfigAttribMaxPictureHeight. vaQuerySurfaceAttributes can be used for surface attribute. for example: surface maxium width can be larger than encode ability resolution. they are different things.

**Comment by mypopydev** [comment]
Yes, when encoding, we need to use vaQuerySurfaceAttributes to get the surface constraints, and I don't think VAConfigAttribRTFormat can cover precise pixel format, e,g VA_RT_FORMAT_YUV420 means YUV420P or NV12?

**Comment by XinfengZhang** [comment]
please help to review  #29 , thanks
