### ISSUE TITLE
There is a problem with the cmake environment path setting

### ISSUE THREAD

**Issue by kppomzh** [intel/media-driver#901]
After I run the command like "cmake ../media_driver/",it returns these errors:
![image](https://user-images.githubusercontent.com/16862592/79066332-b985cf80-7ce9-11ea-925a-31e24bc25d4f.png)
These files do exist in the folder, but the path shown here is obviously incorrect.
In addition,when I built version 19.4.0,I could only using "cmake .."to build and install.It worked very well.

**Comment by XinfengZhang** [comment]
hi ,  cmake ../media_driver/?? the CMake top file should located in media-driver/

**Comment by kppomzh** [comment]
@XinfengZhang Well,I just follow the Readme.
![image](https://user-images.githubusercontent.com/16862592/79068686-5c931500-7cfb-11ea-8767-85359d7d729b.png)
