### ISSUE TITLE
TGL: GPU hang when encoding a 64x64 VP9 video

### ISSUE THREAD

**Issue by xhaihao** [intel/media-driver#913]
This issue can be reproduced by running the commands below:
```
$> sample_encode vp9 -p010 -msb10 -i input.p010.yuv -w 64 -h 64 -o output.ivf
```
```
$> sample_encode vp9 -nv12 -i input.nv12.yuv -w 64 -h 64 -o output.ivf
```
media-driver: 1478047
MediaSDK: c92b652bb0f9bb8504c54076a3a1db9fed3fa50e

The same commands work well on ICL.

**Comment by Xiaogangli-intel** [comment]
@xhaihao thank you, could you provide linux kernel version?

**Comment by xhaihao** [comment]
I used https://cgit.freedesktop.org/drm-tip on TGL.

**Comment by XinfengZhang** [comment]
minimum resolution of vp9 vdenc should be 128x96, will change the capability to report it.
