### ISSUE TITLE
Regression: image corruption since commit 1478047 when decoding a 4:4:4 JPEG file and VP9 10bit clips

### ISSUE THREAD

**Issue by xhaihao** [intel/media-driver#916]
Reproduce steps:
1.  
```
$> gst-launch-1.0 filesrc location=input.444P.jpeg ! jpegparse ! vaapijpegdec ! filesink location=output.yuv
```

2. View output.yuv in a yuv viewer, the format is 444P. 

I see this issue on ICL and TGL

**Comment by FurongZhang** [comment]
@XinfengZhang

**Comment by Jister** [comment]
@xhaihao could you provide the test file? Thanks

**Comment by xhaihao** [comment]
@Jister I have sent the clip to you by email

**Comment by Jister** [comment]
Please try #920

**Comment by xhaihao** [comment]
@Jister your patch works for me, thanks!

**Comment by FocusLuo** [comment]
This patch also caused almost all of ffmpeg-vaapi and gst-vaapi vp9 10bit decode test cases failed, which dropped down big pass rate on us
can you help to fix it ASAP?

**Comment by FocusLuo** [comment]
gst-launch-1.0 -vf filesrc location=./vp9_10bit_fastfood_64x64.ivf ! ivfparse ! vaapivp9dec ! videoconvert dither=0 ! video/x-raw,format=P010_10LE ! checksumsink2 file-checksum=false qos=false frame-checksum=false plane-checksum=false dump-output=true dump-location=test.yuv

**Comment by Jister** [comment]
@FocusLuo could you share the test file './vp9_10bit_fastfood_64x64.ivf' , thanks

**Comment by Jister** [comment]
@xhaihao Can we close the issue since the issue has been fixed? Thanks
