### ISSUE TITLE
[Regression] VP9 10bit decode still have some failed cases

### ISSUE THREAD

**Issue by FocusLuo** [intel/media-driver#922]
After applied the patch of "[VP] Add condition to use VP in GetImage #920", the test for VP9 10bit decode still have some 341 failed cases since commit 1478047
ref cmd line: 
gst-launch-1.0 -vf filesrc location=./vp9_10bit_fastfood_64x64.ivf ! ivfparse ! vaapivp9dec ! videoconvert dither=0 ! video/x-raw,format=P010_10LE ! checksumsink2 file-checksum=false qos=false frame-checksum=false plane-checksum=false dump-output=true dump-location=test.yuv

**Comment by Jister** [comment]
I updated the PR#920, please have a try again. Thanks

**Comment by FocusLuo** [comment]
it works now, thanks quick fixing
