### ISSUE TITLE
[VP] Miss some formats in DdiVp_GetColorSpaceFromMediaFormat

### ISSUE THREAD

**Issue by HeJunyan** [intel/media-driver#929]
It seems that DdiVp_GetColorSpaceFromMediaFormat misses some format such as Media_Format_A8B8G8R8 in the switch clause. Some CSC get 

[VP]:   CRITICAL - DdiVp_GetColorSpaceFromMediaFormat:2042: Get ColorSpace from media format: unknown format.

**Comment by Jister** [comment]
Please try patch #948
