### ISSUE TITLE
mediadriver build fails on 32 bit

### ISSUE THREAD

**Issue by bosepriy** [intel/media-driver#937]
Hi,

I am trying to build the media driver for 32 bit platform using  -DARCH=32 on 16.04.1-Ubuntu
I am getting errors as :

media-driver/media_driver/linux/common/os/i915/include/libdrm_macros.h:40:40: error: size of array is negative
       (void) sizeof(char [1 - 2*!(COND)]); \         
                                        ^
/home/bosepriy/Downloads/libva/media_driver/media-driver/media_driver/linux/common/os/i915/include/libdrm_macros.h:76:4: note: in expansion of macro ‘STATIC_ASSERT’
    STATIC_ASSERT(LARGE_OFF_T % 2147483629 == 721 &&

Is there some patch that we can use to make a build of media driver on 32bit platforms ?

**Comment by XinfengZhang** [comment]
@ljia5, could you help to take a look?

**Comment by XinfengZhang** [comment]
@bosepriy it is duplicate with #356

**Comment by XinfengZhang** [comment]
copied from #356 need to enable a special CXXFLAGS such as -D_FILE_OFFSET_BITS=64 or by default the value is 32.
