### ISSUE TITLE
Need GRAY8 format to handle YUV400 decode

### ISSUE THREAD

**Issue by HeJunyan** [intel/media-driver#941]
when chroma_format_idc is 0 in h264, it is a pure gray8 video format. And we should use GRAY8 surface as the RTFormat to decode this kind of stream. The current still use NV12 and set the UV plane to ignored value, which is not very good. According to @xhaihao , the HW supports the GRAY8 format and so should improve this.

**Comment by wangyan-intel** [comment]
@weizhu-intel Could you please check it? Thanks.

**Comment by weizhu-intel** [comment]
Yan, can you check which platform they are working on?

**Comment by wangyan-intel** [comment]
@HeJunyan What platform are your working? TGL?

**Comment by HeJunyan** [comment]
I test it on SKL/ICL. But seems all platform use NV12, no gray8 available.

**Comment by weizhu-intel** [comment]
Our HW can't use yuv400 directly.  If give yuv400,  we need to convert to nv12 in driver.
