### ISSUE TITLE
VAConfigAttribEncMaxSlices attribute return invalid for HEVC encoder on Gen12

### ISSUE THREAD

**Issue by HeJunyan** [intel/media-driver#963]
vaGetConfigAttributes with VAConfigAttribEncMaxSlices return -2147483648, which is an invalid value.

**Comment by wangyan-intel** [comment]
@tim-xie-in Could you please check it? Thanks

**Comment by fulinjie** [comment]
Seem to be related with https://github.com/intel/media-driver/pull/961 ?

**Comment by XinfengZhang** [comment]
fixed by #961 , commit 152008b6c95e56939d80e44f8a2023504b76ab62
