### ISSUE TITLE
[Regression] iHD driver build failed on Ubuntu Xenial (16.04)

### ISSUE THREAD

**Issue by FocusLuo** [intel/media-driver#965]
Media CI build failed log link: https://media-ci.ostc.intel.com/build/434645/overview

07:34:04,277 INFO  - /opt/media/build/intel-media-driver/media_driver/agnostic/gen12/codec/hal/codechal_decode_scalability_g12.cpp: In function 'MOS_STATUS CodecHalDecodeScalability_FEBESync_G12(PCODECHAL_DECODE_SCALABILITY_STATE, PMOS_COMMAND_BUFFER, bool)':
07:34:04,277 INFO  - /opt/media/build/intel-media-driver/media_driver/agnostic/gen12/codec/hal/codechal_decode_scalability_g12.cpp:750:109: error: 'curPipeInUse' may be used uninitialized in this function [-Werror=maybe-uninitialized]
07:34:04,277 INFO  - &pScalabilityState->resSemaMemBEsAdditional[CODECHAL_SCALABILITY_MAX_PIPE_INDEX_OF_TWO_PIPE - curPipeInUse],

**Comment by XinfengZhang** [comment]
should already been fixed by 3640b64c7f9e6406b3b6d520a76d96e364d228bc
