### ISSUE TITLE
pkg_config: require libva version 1.0 is not right.

### ISSUE THREAD

**Issue by xuguangxin** [intel/media-driver#976]
Currently, we require libva 1.0 to build.
https://github.com/intel/media-driver/blob/1e4cfae7c72cde426a93ebbbbfc2103cfe900216/media_driver/linux/ult/CMakeLists.txt#L46

But build with libva 1.0 will show compile errors. Many libva defines is not from 1.0 .
Could we change the requirement to the right libva version?

**Comment by XinfengZhang** [comment]
@ljia5 , please help to check and fix it
