### ISSUE TITLE
Please don't mention i915.force_probe in end-user documentation

### ISSUE THREAD

**Issue by danvet** [intel/media-driver#980]
Ping @XinfengZhang, we discussed in private a bit.

Preliminary hw support is only for UMD developers, never for end-users. As soon as end-users discover this option, they will use it, and upstream linux kernel will force us to provide full regression fixes support even for code we know isn't ready. That's why we have to rename this option every few years already because too many users have discovered it again.

Therefore please remove it from end-user documentation (especially the main README file), and hide it somewhere where only UMD developers will discover it. Same goes for kernel support matrices, preliminary support means "no support" for end-users.

**Comment by XinfengZhang** [comment]
close it, already was fixed by bcfaf0b43e02d14b373995523c1475d07442c1f9

**Comment by danvet** [comment]
Thanks for addressing this so quickly!
