### ISSUE TITLE
JPEG encode transcoding failed on EHL

### ISSUE THREAD

**Issue by xinyudox** [intel/media-driver#989]
os: ubuntu 18.04.3
kernel: 5.4.0-997-generic
platform: EHL
iHD commit id: 3640b64c7f9e6406b3b6d520a76d96e364d228bc
gstreamer vaapi commit id: 1c5f32b5cd0ba48f12201565f76aa550733e544a
libva commit id: b4e690fb33cbfb35a12cffe4b655a4045f71aa82

commond line:
gst-launch-1.0 filesrc location=input.mp4 ! qtdemux ! h264parse ! vaapih264dec ! tee name=t ! queue !  vaapijpegenc ! avimux! filesink location=/tmp/out.avi

log:
Setting pipeline to PAUSED ...
Pipeline is PREROLLING ...
Got context from element 'vaapiencodejpeg0': gst.vaapi.Display=context, gst.vaapi.Display=(GstVaapiDisplay)"\(GstVaapiDisplayGLX\)\ vaapidisplayglx0";
Redistribute latency...
Pipeline is PREROLLED ...
Setting pipeline to PLAYING ...
New clock: GstSystemClock
0:00:00.184487509   492 0x7fac50007a80 ERROR            vaapiencode gstvaapiencode.c:196:gst_vaapiencode_default_alloc_buffer: invalid GstVaapiCodedBuffer size (-1 bytes)
0:00:00.184564287   492 0x7fac50007a80 ERROR            vaapiencode gstvaapiencode.c:303:gst_vaapiencode_push_frame: failed to allocate encoded buffer in system memory
0:00:00.203630029   492 0x7fac50007a80 ERROR            vaapiencode gstvaapiencode.c:196:gst_vaapiencode_default_alloc_buffer: invalid GstVaapiCodedBuffer size (-1 bytes)
0:00:00.204139835   492 0x7fac50007a80 ERROR            vaapiencode gstvaapiencode.c:303:gst_vaapiencode_push_frame: failed to allocate encoded buffer in system memory
0:00:00.220391616   492 0x7fac50007a80 ERROR            vaapiencode gstvaapiencode.c:196:gst_vaapiencode_default_alloc_buffer: invalid GstVaapiCodedBuffer size (-1 bytes)
0:00:00.220419510   492 0x7fac50007a80 ERROR            vaapiencode gstvaapiencode.c:303:gst_vaapiencode_push_frame: failed to allocate encoded buffer in system memory

vainfo:
libva info: VA-API version 1.8.0
libva info: User environment variable requested driver 'iHD'
libva info: Trying to open /opt/X11R7/vpg_driver/lib/dri/iHD_drv_video.so
libva info: Found init function __vaDriverInit_1_8
libva info: va_openDriver() returns 0
vainfo: VA-API version: 1.8 (libva 2.8.0.pre1)
vainfo: Driver version: Intel iHD driver for Intel(R) Gen Graphics - 20.2.pre (3640b64c)
vainfo: Supported profile and entrypoints
      VAProfileNone                   :	VAEntrypointVideoProc
      VAProfileNone                   :	VAEntrypointStats
      VAProfileMPEG2Simple            :	VAEntrypointVLD
      VAProfileMPEG2Main              :	VAEntrypointVLD
      VAProfileH264Main               :	VAEntrypointVLD
      VAProfileH264Main               :	VAEntrypointEncSliceLP
      VAProfileH264High               :	VAEntrypointVLD
      VAProfileH264High               :	VAEntrypointEncSliceLP
      VAProfileVC1Simple              :	VAEntrypointVLD
      VAProfileVC1Main                :	VAEntrypointVLD
      VAProfileVC1Advanced            :	VAEntrypointVLD
      VAProfileJPEGBaseline           :	VAEntrypointVLD
      VAProfileJPEGBaseline           :	VAEntrypointEncPicture
      VAProfileH264ConstrainedBaseline:	VAEntrypointVLD
      VAProfileH264ConstrainedBaseline:	VAEntrypointEncSliceLP
      VAProfileVP8Version0_3          :	VAEntrypointVLD
      VAProfileHEVCMain               :	VAEntrypointVLD
      VAProfileHEVCMain               :	VAEntrypointEncSliceLP
      VAProfileHEVCMain10             :	VAEntrypointVLD
      VAProfileHEVCMain10             :	VAEntrypointEncSliceLP
      VAProfileVP9Profile0            :	VAEntrypointVLD
      VAProfileVP9Profile0            :	VAEntrypointEncSliceLP
      VAProfileVP9Profile1            :	VAEntrypointVLD
      VAProfileVP9Profile1            :	VAEntrypointEncSliceLP
      VAProfileVP9Profile2            :	VAEntrypointVLD
      VAProfileVP9Profile2            :	VAEntrypointEncSliceLP
      VAProfileVP9Profile3            :	VAEntrypointVLD
      VAProfileVP9Profile3            :	VAEntrypointEncSliceLP
      VAProfileHEVCMain422_10         :	VAEntrypointVLD
      VAProfileHEVCMain444            :	VAEntrypointVLD
      VAProfileHEVCMain444            :	VAEntrypointEncSliceLP
      VAProfileHEVCMain444_10         :	VAEntrypointVLD
      VAProfileHEVCMain444_10         :	VAEntrypointEncSliceLP

**Comment by XinfengZhang** [comment]
is there details, such as HW platform, vainfo messages, logs?

**Comment by xuguangxin** [comment]
@XinfengZhang any update on this?
thanks

**Comment by Sherry-Lin** [comment]
Could you please confirm whether it's workable for signal transcode in EHL with 5.4 kernel? As I know, EHL also require 5.7+ kernel version.

**Comment by xinyudox** [comment]
it's workable for signal transcode in EHL with 5.4 kernel.

**Comment by xuguangxin** [comment]
@Sherry-Lin any update on this?
thanks

**Comment by Xiaogangli-intel** [comment]
@xinyudox we checked this issue, the failure is caused by JPEG encoding, although with single JPEG encoding, it still failed.

But you mentioned, "it's workable for signal transcode in EHL with 5.4 kernel.", single H264? H265 or JPEG?

**Comment by XinfengZhang** [comment]
suppose it is same issue with #902 ?

**Comment by zcwang** [comment]
@XinfengZhang could you please to check issue #1030 for similar issue comparing to this issue? Thanks!

**Comment by Xiaogangli-intel** [comment]
@xinyudox Could you upgrade your Linux kernel?
The requirement already mentioned in README. (EHL/JSL/TGL: drm-tip, missed in <=5.4.3 kernels)

JPEG encoding works well if we don't run AVC encoding. So maybe some of the registers were not reset after run AVC encoding. This maybe related to KMD, so please try the KMD which supports EHL.

**Comment by zcwang** [comment]
@xinyudox May I know if it still could be reproduced after upgrade kernel to newer version >= 5.4.3 for my reference?

Thanks!
Gary

**Comment by xinyudox** [comment]
This issue can't be reproduced using kernel version 5.9.0-rc2+.
