### ISSUE TITLE
vaExportSurfaceHandle is broken for YV12 and I420

### ISSUE THREAD

**Issue by michaelolbrich** [intel/media-driver#995]
And probably other three-plane formats. The same offset is returned for the U and V planes.

From a quick look at the code, it seems that `DdiMedia_ExportSurfaceHandle()` does not handle 3 planes at all.

**Comment by XinfengZhang** [comment]
@Guangyao-Bai @Jister , please help to check the issue, when MMC is not enabled , it should support 3 planes , right?

**Comment by Jister** [comment]
please try #1000
