### ISSUE TITLE
vaQueryImageFormats does not return Y212 and Y412 format on TGL.

### ISSUE THREAD

**Issue by HeJunyan** [intel/media-driver#998]
Y212 and Y412 formats should be returned if we want to decode 12 bits 422 and 444 streams in HEVC.
The Y216 and Y416 are returned, but we need to use 12 bits format, it is more precise. And I also notice that the P012 is available. 

Please also make sure Y212 and Y412 are in the list of vaQuerySurfaceAttributes's VASurfaceAttribPixelFormat, then we can make these formats as RT surface format of encoder/decoder context.

**Comment by wangyan-intel** [comment]
@HeJunyan It should be similar with #921. Right? I can add them.

**Comment by HeJunyan** [comment]
Yes, please. And I notice the P012 is ready.

**Comment by wangyan42164** [comment]
@HeJunyan Could you please try #1002 which is dependent on https://github.com/intel/libva/pull/434? Thanks.

**Comment by FurongZhang** [comment]
Most of code changes are related to Codec.
